Repository keephq/keep, pull requests merged in 2023-11, with the labels that each got.

#453 feat: added aks provider
  docs/providers/documentation/aks-provider.mdx
  examples/workflows/aks_basic.yml
  keep-ui/public/aks.svg
  keep-ui/public/icons/aks-icon.png
  keep/providers/aks_provider/aks_provider.py
  poetry.lock
  pyproject.toml
Labels: 🙋 Bounty claim

#454 feat: twilio provider
  docs/mint.json
  docs/providers/documentation/twilio-provider.mdx
  keep-ui/public/icons/twilio-icon.png
  keep/providers/twilio_provider/twilio_provider.py
  poetry.lock
  pyproject.toml
Labels: 🙋 Bounty claim

#515 feat: kibana 8.1 alerts and connectors
  docs/images/kibana/api-keys.png
  docs/images/kibana/copy-created-key.png
  docs/images/kibana/create-api-key.png
  docs/images/kibana/kibana_host.png
  docs/mint.json
  docs/providers/documentation/kibana-provider.mdx
  keep-ui/app/alerts/alerts-table-body.tsx
  keep-ui/public/icons/kibana-icon.png
  keep/api/routes/alerts.py
  keep/api/routes/providers.py
  keep/providers/kibana_provider/__init__.py
  keep/providers/kibana_provider/kibana_provider.py
Labels: provider

#557 feat: added scopes-OpsGenie-provider
  keep/providers/opsgenie_provider/opsgenie_provider.py
Labels: 🙋 Bounty claim

#589 fix(ui): providers responsiveness
  keep-ui/app/providers/provider-tile.css
  keep-ui/app/providers/provider-tile.tsx
  keep-ui/app/providers/providers-tiles.css
  keep-ui/app/providers/providers-tiles.tsx
Labels: UI
