Repository keephq/keep, pull requests merged in 2024-10, with the labels that each got.

#2108 feat: smtp provider
  README.md
  docs/mint.json
  docs/providers/documentation/smtp-provider.mdx
  keep-ui/public/icons/smtp-icon.png
  keep/providers/smtp_provider/__init__.py
  keep/providers/smtp_provider/smtp_provider.py
Labels: 🙋 Bounty claim

#1977 feat: Added dashboard for Alert Quality
  keep-ui/app/alerts/alert-quality-table.tsx
  keep-ui/app/dashboard/GridItem.tsx
  keep-ui/app/dashboard/GridItemContainer.tsx
  keep-ui/app/dashboard/GridLayout.tsx
  keep-ui/app/dashboard/MenuButton.tsx
  keep-ui/app/dashboard/WidgetModal.tsx
  keep-ui/app/dashboard/[id]/dashboard.tsx
  keep-ui/app/dashboard/types.tsx
  keep-ui/components/filters/GenericFilters.tsx
  keep-ui/components/navbar/CustomPresetAlertLinks.tsx
  keep-ui/components/navbar/Search.tsx
  keep-ui/components/table/GenericTable.tsx
  keep-ui/utils/hooks/useAlertQuality.ts
  keep/api/core/db.py
  keep/api/routes/alerts.py
  keep/api/utils/time_stamp_helpers.py
Labels: 🙋 Bounty claim

#2271 fix(ui): cancel creates the rule
  keep-ui/app/deduplication/DeduplicationSidebar.tsx
  pyproject.toml
Labels: UI, size:XS, lgtm

#2275 fix(migrations): sqlite migration
  keep/api/models/db/migrations/versions/2024-10-22-10-38_8438f041ee0e.py
Labels: Bug, size:M, lgtm

#2276 fix(migrations): db's other than sqlite
  keep/api/models/db/migrations/versions/2024-10-22-10-38_8438f041ee0e.py
  pyproject.toml
Labels: Bug, size:S, lgtm

#2279 fix(zabbix): add ipaddress and hostname
  keep/providers/zabbix_provider/zabbix_provider.py
Labels: Provider, size:XS

#2286 fix: workflow last run time
  examples/workflows/cron-digest-alerts.yml
  keep/contextmanager/contextmanager.py
  keep/providers/keep_provider/keep_provider.py
  pyproject.toml
Labels: Bug, size:M, lgtm

#2288 docs: Fix typos on multiple pages of Keep Docs Site
  docs/deployment/configuration.mdx
  docs/deployment/ecs.mdx
  docs/deployment/stress-testing.mdx
  docs/overview/comparisons.mdx
  docs/overview/deduplication.mdx
Labels: Documentation, size:S, lgtm

#2291 fix(ui): incident add a comment uses old API
  keep-ui/app/incidents/[id]/incident-activity.tsx
Labels: UI, size:XS, lgtm

#2293 fix: alert enriching is always disposable (no matter query params)
  keep/api/routes/alerts.py
  pyproject.toml
Labels: Bug, size:M, lgtm

#2300 docs(k8s): read environment variable from secret
  docs/deployment/kubernetes/overview.mdx
  docs/deployment/secret-manager.mdx
Labels: Documentation, size:M, lgtm

#2304 docs: better docs on ingress
  docs/deployment/kubernetes/installation.mdx
Labels: Documentation, size:XS, lgtm

#2295 docs: Fix typos on certain pages of Keep Docs Site
  docs/overview/examples.mdx
  docs/overview/introduction.mdx
  docs/overview/keyconcepts.mdx
  docs/providers/adding-a-new-provider.mdx
  docs/providers/documentation/auth0-provider.mdx
  docs/workflows/state.mdx
  docs/workflows/syntax/basic-syntax.mdx
  docs/workflows/syntax/context-syntax.mdx
  docs/workflows/syntax/foreach-syntax.mdx
  docs/workflows/throttles/one-until-resolved.mdx
Labels: Documentation, size:M, lgtm

#2313 feat(ui): add azure svg to signin
  keycloak/docker-compose.yaml
  keycloak/themes/keep.jar
Labels: UI, size:XS, lgtm

#2311 feat: merge incidents list (frontend + severity update fix)
  keep-ui/app/alerts/alert-pagination.tsx
  keep-ui/app/globals.css
  keep-ui/app/incidents/[id]/incident-activity.tsx
  keep-ui/app/incidents/[id]/incident-alert-menu.tsx
  keep-ui/app/incidents/[id]/incident-alerts.tsx
  keep-ui/app/incidents/[id]/incident-chat.tsx
  keep-ui/app/incidents/[id]/incident-header.tsx
  keep-ui/app/incidents/[id]/incident-overview.tsx
  keep-ui/app/incidents/[id]/incident-timeline.tsx
  keep-ui/app/incidents/[id]/incident-workflow-table.tsx
  keep-ui/app/incidents/[id]/incident.tsx
  keep-ui/app/incidents/create-or-update-incident.tsx
  keep-ui/app/incidents/incident-candidate-actions.tsx
  keep-ui/app/incidents/incident-change-status-modal.tsx
  keep-ui/app/incidents/incident-list-error.tsx
  keep-ui/app/incidents/incident-list-placeholder.tsx
  keep-ui/app/incidents/incident-list.tsx
  keep-ui/app/incidents/incident-merge-modal.tsx
  keep-ui/app/incidents/incident-pagination.tsx
  keep-ui/app/incidents/incident-table-component.tsx
  keep-ui/app/incidents/incident-table-filters-context.tsx
  keep-ui/app/incidents/incidents-table.tsx
  keep-ui/app/incidents/models.ts
  keep-ui/app/incidents/page.tsx
  keep-ui/app/incidents/react-quill-override.css
  keep-ui/app/incidents/statuses.tsx
  keep-ui/app/incidents/vertical-rounded-list.css
  keep-ui/components/ui/table/utils.ts
  keep-ui/package-lock.json
  keep-ui/package.json
  keep-ui/tailwind.config.js
  keep-ui/utils/hooks/useIncidents.ts
  keep/api/core/db.py
  keep/api/models/db/migrations/versions/2024-10-23-15-21_89b4d3905d26.py
  tests/test_incidents.py
Labels: Feature, UI, size:XXL, lgtm

#2317 fix: hovering long dashboard names stretch NavBar
  keep-ui/components/navbar/DashboardLink.tsx
  keep-ui/components/navbar/DashboardLinks.tsx
Labels: UI, size:M, lgtm

#2309 fix: keycloak docs
  docs/deployment/authentication/keycloak-auth.mdx
  ee/identitymanager/identity_managers/keycloak/keycloak_authverifier.py
  keycloak/keycloak_entrypoint.sh
  keycloak/readme.md
Labels: Documentation, size:M, lgtm

#2217 fix: incident.alerts_count should return count of unique fingerprints instead of alerts
  keep/api/core/db.py
  keep/api/tasks/process_event_task.py
  tests/test_incidents.py
Labels: size:M, lgtm

#2328 fix(workflows): email template
  keep/api/routes/workflows.py
  keep/iohandler/iohandler.py
  pyproject.toml
Labels: Bug, size:XS, lgtm

#2305 feat: add Graylog Provider
  README.md
  docs/mint.json
  docs/providers/documentation/graylog-provider.mdx
  docs/providers/overview.mdx
  keep-ui/public/icons/graylog-icon.png
  keep/providers/graylog_provider/README.md
  keep/providers/graylog_provider/__init__.py
  keep/providers/graylog_provider/alerts_mock.py
  keep/providers/graylog_provider/docker-compose.yml
  keep/providers/graylog_provider/graylog_provider.py
Labels: Documentation, Feature, Provider, size:XL, lgtm

#2274 feat: merge incidents
  docs/api-ref/alerts/get-alert-quality.mdx
  docs/api-ref/incidents/add-comment.mdx
  docs/api-ref/incidents/get-future-incidents-for-an-incident.mdx
  docs/api-ref/incidents/get-incident-workflows.mdx
  docs/api-ref/incidents/get-incidents-meta.mdx
  docs/api-ref/incidents/merge-incidents.mdx
  docs/mint.json
  docs/openapi.json
  keep-ui/app/alerts/alert-pagination.tsx
  keep-ui/app/globals.css
  keep-ui/app/incidents/[id]/incident-activity.tsx
  keep-ui/app/incidents/[id]/incident-alert-menu.tsx
  keep-ui/app/incidents/[id]/incident-alerts.tsx
  keep-ui/app/incidents/[id]/incident-chat.tsx
  keep-ui/app/incidents/[id]/incident-header.tsx
  keep-ui/app/incidents/[id]/incident-overview.tsx
  keep-ui/app/incidents/[id]/incident-timeline.tsx
  keep-ui/app/incidents/[id]/incident-workflow-table.tsx
  keep-ui/app/incidents/[id]/incident.tsx
  keep-ui/app/incidents/create-or-update-incident.tsx
  keep-ui/app/incidents/incident-candidate-actions.tsx
  keep-ui/app/incidents/incident-change-status-modal.tsx
  keep-ui/app/incidents/incident-dropdown-menu.tsx
  keep-ui/app/incidents/incident-list-error.tsx
  keep-ui/app/incidents/incident-list-placeholder.tsx
  keep-ui/app/incidents/incident-list.tsx
  keep-ui/app/incidents/incident-merge-modal.tsx
  keep-ui/app/incidents/incident-pagination.tsx
  keep-ui/app/incidents/incident-table-component.tsx
  keep-ui/app/incidents/incident-table-filters-context.tsx
  keep-ui/app/incidents/incidents-table.tsx
  keep-ui/app/incidents/models.ts
  keep-ui/app/incidents/page.tsx
  keep-ui/app/incidents/react-quill-override.css
  keep-ui/app/incidents/statuses.tsx
  keep-ui/app/incidents/vertical-rounded-list.css
  keep-ui/components/ui/DropdownMenu/DropdownMenu.css
  keep-ui/components/ui/DropdownMenu/DropdownMenu.tsx
  keep-ui/components/ui/DropdownMenu/index.ts
  keep-ui/components/ui/table/utils.ts
  keep-ui/entities/incidents/model/useIncidentActions.tsx
  keep-ui/features/change-incident-status/index.ts
  keep-ui/features/change-incident-status/ui/incident-change-status-select.tsx
  keep-ui/package-lock.json
  keep-ui/package.json
  keep-ui/tailwind.config.js
  keep-ui/tsconfig.json
  keep-ui/utils/hooks/useIncidents.ts
  keep/api/core/db.py
  keep/api/models/alert.py
  keep/api/models/db/alert.py
  keep/api/models/db/migrations/versions/2024-10-23-15-21_89b4d3905d26.py
  keep/api/routes/incidents.py
  keep/api/utils/pluralize.py
  tests/test_incidents.py
Labels: Feature, UI, size:XXL, lgtm

#2308 feat: checkmk provider
  README.md
  docs/images/checkmk-provider_1.png
  docs/images/checkmk-provider_2.png
  docs/images/checkmk-provider_3.png
  docs/images/checkmk-provider_4.png
  docs/mint.json
  docs/providers/documentation/checkmk-provider.mdx
  docs/providers/overview.mdx
  keep-ui/public/icons/checkmk-icon.png
  keep/providers/checkmk_provider/README.md
  keep/providers/checkmk_provider/__init__.py
  keep/providers/checkmk_provider/alerts_mock.py
  keep/providers/checkmk_provider/checkmk_provider.py
  keep/providers/checkmk_provider/webhook-keep.py
Labels: Documentation, Feature, Provider, size:L, lgtm

#2335 refactor: move incident CRUD to `useIncidentActions()` hook, unify revalidation
  keep-ui/app/incidents/[id]/incident-chat.tsx
  keep-ui/app/incidents/create-or-update-incident.tsx
  keep-ui/app/incidents/incident-change-same-in-the-past.tsx
  keep-ui/app/incidents/incident-change-status-modal.tsx
  keep-ui/app/incidents/incident-dropdown-menu.tsx
  keep-ui/app/incidents/incident-list.tsx
  keep-ui/app/incidents/incident-merge-modal.tsx
  keep-ui/app/incidents/incidents-table.tsx
  keep-ui/entities/incidents/model/useIncidentActions.tsx
  keep-ui/utils/hooks/useIncidents.ts
Labels: size:XL, lgtm

#2336 feat: use server-side rendering for incident list
  keep-ui/.gitignore
  keep-ui/app/error.tsx
  keep-ui/app/incidents/incident-list.tsx
  keep-ui/app/incidents/page.tsx
  keep-ui/app/providers/page.client.tsx
  keep-ui/app/workflows/builder/builder-card.tsx
  keep-ui/entities/incidents/api/incidents.ts
  keep-ui/shared/lib/KeepApiError.ts
  keep-ui/tailwind.config.js
  keep-ui/tsconfig.json
  keep-ui/utils/fetcher.ts
  keep-ui/utils/hooks/useIncidents.ts
Labels: Feature, UI, size:L, lgtm

#2338 fix: migration messing link between alerts and incidents
  keep/api/models/db/migrations/versions/2024-10-29-18-37_991b30bcf0b9.py
Labels: size:M, lgtm

#2348 fix(smtp): username and password are not mandatory
  keep/providers/smtp_provider/smtp_provider.py
  pyproject.toml
Labels: Bug, size:M, lgtm

#2357 feat(ui): onboarding experience using Frigade
  keep-ui/app/frigade-provider.tsx
  keep-ui/app/layout.tsx
  keep-ui/app/settings/webhook-settings.tsx
  keep-ui/components/navbar/Navbar.tsx
  keep-ui/components/navbar/Onboarding.tsx
  keep-ui/components/navbar/UserInfo.tsx
  keep-ui/package-lock.json
  keep-ui/package.json
  keep/api/models/alert.py
Labels: Feature, UI, size:L, lgtm

#2235 fix: /incident/{incident-id}/alerts now return only alerts with unique fingerprints
  keep/api/core/db.py
  keep/api/tasks/process_event_task.py
  keep/providers/base/base_provider.py
  tests/test_incidents.py
  tests/test_rules_engine.py
Labels: size:M, lgtm

#2368 fix: limit and offset in incident alerts
  keep/api/core/db.py
Labels: Bug, size:XS, lgtm

#2369 feat: GCP logging and friends 🏄‍♂️
  docs/mint.json
  docs/providers/documentation/gcpmonitoring-provider.mdx
  docs/providers/documentation/openai-provider.mdx
  docs/providers/documentation/slack-provider.mdx
  docs/providers/overview.mdx
  examples/workflows/gcp_logging_open_ai.yaml
  keep-ui/public/icons/openai-icon.png
  keep/api/api.py
  keep/providers/gcpmonitoring_provider/gcpmonitoring_provider.py
  keep/providers/openai_provider/__init__.py
  keep/providers/openai_provider/openai_provider.py
  keep/providers/slack_provider/slack_provider.py
  poetry.lock
  pyproject.toml
Labels: Documentation, Feature, Provider, size:L, lgtm

#2211 fix: refactor the workflow execution component to reduce repaint/rend…
  keep-ui/app/alerts/alert-quality-table.tsx
  keep-ui/app/workflows/[workflow_id]/executions.tsx
  keep-ui/app/workflows/[workflow_id]/layout.tsx
  keep-ui/app/workflows/[workflow_id]/side-nav-bar.tsx
  keep-ui/app/workflows/[workflow_id]/workflow-overview.tsx
  keep-ui/app/workflows/builder/builder-modal.tsx
  keep-ui/components/ui/discolsure-section.tsx
  keep-ui/utils/hooks/useAlertQuality.ts
  keep-ui/utils/hooks/useWorkflowExecutions.ts
  keep/api/routes/workflows.py
Labels: size:XL, lgtm
