Repository keephq/keep, pull requests merged in 2024-12, with the labels that each got.

#2662 fix: fix sql to cel conversion
  keep-ui/app/(keep)/alerts/alerts-rules-builder.tsx
Labels: size:XS, lgtm

#2712 fix: introduce KEEP_ALERT_FIELDS_ENABLED
  keep/api/tasks/process_event_task.py
  pyproject.toml
Labels: size:M

#2715 fix: OnCall provider and docs
  docs/providers/documentation/grafana_oncall-provider.mdx
  keep/providers/grafana_oncall_provider/grafana_oncall_provider.py
Labels: Bug, Documentation, size:L, lgtm

#2714 chore: introduce auto release
  .github/workflows/auto-release.yml
Labels: size:M

#2718 fix: oauth2 not working due to providers caching
  docker/Dockerfile.api
  keep/entrypoint.sh
Labels: size:XS

#2721 fix: AI Table columns types
  keep/api/models/db/ai_external.py
  keep/api/models/db/migrations/versions/2024-12-01-16-40_3ad5308e7200.py
Labels: size:M

#2724 chore(deps): upgrade posthog to 1.194.1
  keep-ui/package-lock.json
  keep-ui/package.json
Labels: Dependencies, size:XS

#2473 feat: change relation between alerts and incidents to work with fingerprints instead of alert ids
  keep-ui/app/(keep)/alerts/alert-associate-incident-modal.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alert-menu.tsx
  keep-ui/entities/incidents/model/models.ts
  keep/api/bl/incidents_bl.py
  keep/api/core/db.py
  keep/api/models/db/alert.py
  keep/api/models/db/migrations/versions/2024-12-01-16-40_3ad5308e7200.py
  keep/api/models/db/migrations/versions/2024-12-02-13-36_bdae8684d0b4.py
  keep/api/routes/incidents.py
  keep/api/routes/workflows.py
  keep/api/tasks/process_event_task.py
  keep/api/utils/enrichment_helpers.py
  keep/rulesengine/rulesengine.py
  tests/conftest.py
  tests/test_incidents.py
  tests/test_metrics.py
  tests/test_rules_engine.py
Labels: Feature, size:XXL

#2730 fix: incident linking
  keep-ui/features/same-incidents-in-the-past/ui/change-same-incident-in-the-past-form.tsx
Labels: Bug, size:XS, lgtm

#2733 fix: Handle Duplication entry error in set_last_alert
  keep/api/core/db.py
Labels: size:M, lgtm

#2736 feat: microsoft teams provider add support for adaptivecards
  docs/providers/documentation/teams-provider.mdx
  examples/workflows/keep-teams-adaptive-cards.yaml
  keep-ui/package-lock.json
  keep-ui/package.json
  keep/providers/teams_provider/teams_provider.py
  pyproject.toml
Labels: Documentation, Feature, Provider, size:L

#2738 fix(pagerduty): incident creation priority support
  docs/providers/documentation/pagerduty-provider.mdx
  keep/providers/pagerduty_provider/pagerduty_provider.py
Labels: Documentation, size:M

#2741 fix(slack): message is not required with attachments
  keep/providers/slack_provider/slack_provider.py
  keep/providers/teams_provider/teams_provider.py
  pyproject.toml
Labels: Bug, size:L

#2742 fix: Use SELECT FOR UPDATE to prevent race conditions in set_last_alert
  keep/api/core/db.py
Labels: size:M, lgtm

#2745 fix(teams): attachements to list
  keep/providers/teams_provider/teams_provider.py
Labels: Provider, size:M

#2747 fix: small UI issue and victoriametrics best efforts
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep/providers/teams_provider/teams_provider.py
  keep/providers/victoriametrics_provider/victoriametrics_provider.py
Labels: Provider, UI, size:M

#2749 fix: sessions in /ai/stats
  keep/api/core/db.py
Labels: Bug, size:XS, lgtm

#2751 fix: jira provider `_host` attribute
  keep/providers/jira_provider/jira_provider.py
  keep/providers/victoriametrics_provider/victoriametrics_provider.py
Labels: Provider, size:S

#2739 feat(ui): dark mode detection
  keep-ui/app/(keep)/layout.tsx
  keep-ui/app/dark-mode-toggle.tsx
  keep-ui/app/globals.css
  keep-ui/components/LinkWithIcon.tsx
  keep-ui/components/navbar/UserInfo.tsx
  keep-ui/components/ui/DropdownMenu/DropdownMenu.tsx
  keep-ui/shared/constants.ts
  keep-ui/shared/ui/theme/ThemeControl.tsx
  keep-ui/shared/ui/theme/ThemeScript.tsx
  keep-ui/shared/ui/theme/WatchUpdateTheme.ts
Labels: Feature, UI, size:L, lgtm

#2754 feat: mapping page sidebar
  keep-ui/app/(keep)/extraction/create-or-update-extraction-rule.tsx
  keep-ui/app/(keep)/mapping/create-or-edit-mapping.tsx
  keep-ui/app/(keep)/mapping/layout.tsx
  keep-ui/app/(keep)/mapping/mapping.tsx
Labels: Feature, UI, size:L, lgtm

#2758 fix: Use alert fingerprints instead of ids to assign alerts to incidents
  keep/api/core/demo_mode.py
Labels: Bug, size:S, lgtm

#2638 feat: switch all alert queries to use lastalert
  keep/api/core/db.py
  keep/api/models/db/alert.py
  keep/api/models/db/migrations/versions/2024-12-02-20-42_c6e5594c99f8.py
  tests/conftest.py
Labels: Feature, size:L, lgtm

#2763 docs(contact): Create config.yml for GH contact
  .github/ISSUE_TEMPLATE/config.yml
Labels: Documentation, size:S

#2765 fix: revert validation for Slack provider to work with oauth
  keep/parser/parser.py
  keep/providers/slack_provider/slack_provider.py
Labels: Bug, size:XS, lgtm

#2752 fix: Minor quickstart fixes
  docs/development/getting-started.mdx
Labels: Documentation, size:S, lgtm

#2772 fix(ui): pointer-events-none to build info in dev mode
  keep-ui/app/(keep)/layout.tsx
  keep/entrypoint.sh
Labels: UI, size:S

#2773 fix: ee posthog
  keep/api/core/report_uptime.py
Labels: size:XS

#2778 fix(api): yaml breaklines
  keep/api/routes/workflows.py
  pyproject.toml
Labels: Bug, API, size:S, lgtm

#2781 fix(api): yaml breaklines
  keep/api/models/workflow.py
  keep/api/routes/workflows.py
  keep/workflowmanager/workflowstore.py
  pyproject.toml
Labels: Bug, API, size:S, lgtm

#2785 refactor: remove heavy frontend deps
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
  keep-ui/app/(keep)/providers/provider-tile.tsx
  keep-ui/package-lock.json
  keep-ui/package.json
  keep-ui/utils/helpers.ts
  keep-ui/utils/hooks/useWorkflowInitialization.ts
Labels: Dependencies, UI, size:L, lgtm

#2783 fix: remove curcular imports
  keep-ui/app/(keep)/alerts/alert-table-facet-dynamic.tsx
  keep-ui/app/(keep)/alerts/alert-table-facet-types.tsx
  keep-ui/app/(keep)/alerts/alert-table.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationForm.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationGroups.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationSidebarBody.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationSubmission.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/RuleFields.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/index.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/timeframe-constants.ts
  keep-ui/app/(keep)/rules/CorrelationSidebar/types.ts
  keep-ui/app/(keep)/rules/CorrelationTable.tsx
  keep-ui/app/(keep)/settings/auth/api-key-settings.tsx
  keep-ui/app/(keep)/settings/auth/types.ts
  keep-ui/app/(keep)/settings/create-api-key-modal.tsx
  keep-ui/app/(keep)/workflows/builder/CustomNode.tsx
  keep-ui/app/(keep)/workflows/builder/NodeMenu.tsx
  keep-ui/app/(keep)/workflows/builder/ReactFlowBuilder.tsx
  keep-ui/app/(keep)/workflows/builder/ReactFlowEditor.tsx
  keep-ui/app/(keep)/workflows/builder/ToolBox.tsx
  keep-ui/app/(keep)/workflows/builder/alert.tsx
  keep-ui/app/(keep)/workflows/builder/builder-validators.tsx
  keep-ui/app/(keep)/workflows/builder/builder.tsx
  keep-ui/app/(keep)/workflows/builder/editors.tsx
  keep-ui/app/(keep)/workflows/builder/types.ts
  keep-ui/app/(keep)/workflows/builder/types.tsx
  keep-ui/app/(keep)/workflows/builder/utils.tsx
  keep-ui/utils/hooks/useWorkflowInitialization.ts
  keep-ui/utils/reactFlow.ts
Labels: Bug, size:L, lgtm

#2789 fix: Postgres' json_agg return Null instead of empty list if no data
  keep/api/core/db.py
  tests/test_incidents.py
Labels: Bug, size:S, lgtm

#2787 feat: We can now set target RPS and workers amount for simulate_alerts
  keep/api/core/demo_mode.py
  scripts/simulate_alerts.py
Labels: Feature, size:L, lgtm

#2790 feat(api): unique id
  keep/api/routes/workflows.py
  keep/workflowmanager/workflowstore.py
  pyproject.toml
Labels: Feature, API, size:XS, lgtm

#2761 fix: Catch lastalert deadlocks
  keep/api/core/db.py
Labels: size:M, lgtm

#2795 fix: do not convert data to iso string if it's alredy an ISO string
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
Labels: Bug, UI, size:S

#2801 fix(ui): cel validation
  keep-ui/app/(keep)/alerts/alerts-rules-builder.tsx
  pyproject.toml
Labels: UI, size:S, lgtm

#2805 fix: body format on DELETE incidents/{id}/alerts
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alert-menu.tsx
Labels: Bug, size:XS

#2807 fix(api): datadog
  keep/providers/datadog_provider/datadog_provider.py
Labels: API, size:S, lgtm

#2816 fix(ui): websocket on port other than 80/443 on k8s
  keep-ui/utils/hooks/usePusher.ts
  pyproject.toml
Labels: UI, size:S

#2720 feat(provider): vector dev
  keep-ui/app/(keep)/providers/provider-tile.tsx
  keep-ui/app/(keep)/providers/providers-tiles.tsx
  keep-ui/public/icons/vectordev-icon.png
  keep/api/api.py
  keep/api/config.py
  keep/api/models/db/migrations/versions/2024-12-01-16-40_3ad5308e7200.py
  keep/api/tasks/process_event_task.py
  keep/providers/base/base_provider.py
  keep/providers/vectordev_provider/__init__.py
  keep/providers/vectordev_provider/vectordev_provider.py
  tests/fixtures/client.py
  tests/test_provisioning.py
Labels: Feature, Provider, size:L, lgtm

#2820 feat: healthcheck
  docs/deployment/monitoring.mdx
  docs/mint.json
  keep-ui/app/api/healthcheck/route.ts
Labels: Documentation, Feature, size:M

#2824 fix(kafka): lastReceived in ISO format
  keep/providers/base/base_provider.py
  pyproject.toml
Labels: Bug, size:S

#2775 feat: better visibility
  .github/workflows/test-pr-e2e.yml
  .github/workflows/test-pr.yml
  keep-ui/app/(keep)/alerts/alert-name.tsx
  keep/api/alert_deduplicator/alert_deduplicator.py
  keep/api/api.py
  keep/api/bl/enrichments_bl.py
  keep/api/config.py
  keep/api/core/db.py
  keep/api/core/db_on_start.py
  keep/api/core/db_utils.py
  keep/api/core/demo_mode.py
  keep/api/core/metrics.py
  keep/api/custom_worker.py
  keep/api/models/db/ai_external.py
  keep/api/models/db/alert.py
  keep/api/models/db/mapping.py
  keep/api/models/db/migrations/versions/2024-07-11-17-10_54c1252b2c8a.py
  keep/api/models/db/migrations/versions/2024-07-15-15-10_c37ec8f6db3e.py
  keep/api/models/db/migrations/versions/2024-07-16-12-16_37019ca3eb2e.py
  keep/api/models/db/migrations/versions/2024-08-11-17-38_9453855f3ba0.py
  keep/api/models/db/migrations/versions/2024-09-19-15-26_493f217af6b6.py
  keep/api/models/db/migrations/versions/2024-09-22-14-16_01ebe17218c0.py
  keep/api/models/db/migrations/versions/2024-10-31-18-01_273b29f368b7.py
  keep/api/models/db/migrations/versions/2024-12-02-13-36_bdae8684d0b4.py
  keep/api/models/db/migrations/versions/2024-12-02-20-42_c6e5594c99f8.py
  keep/api/models/db/migrations/versions/2024-12-08-16-24_55cc64020f6d.py
  keep/api/routes/alerts.py
  keep/api/routes/metrics.py
  keep/api/routes/providers.py
  keep/api/tasks/process_event_task.py
  keep/identitymanager/authverifierbase.py
  keep/providers/opsgenie_provider/opsgenie_provider.py
  keep/providers/providers_factory.py
  keep/providers/slack_provider/slack_provider.py
  poetry.lock
  pyproject.toml
  scripts/simulate_alerts.sh
  tests/conftest.py
  tests/e2e_tests/docker-compose-e2e-mysql.yml
  tests/e2e_tests/docker-compose-e2e-postgres.yml
  tests/fixtures/client.py
  tests/test_deduplications.py
  tests/test_enrichments.py
  tests/test_search_alerts.py
  tests/test_workflow_execution.py
Labels: Feature, size:XXL, lgtm

#2831 fix: incident id and datadog tags
  keep/api/core/db.py
  keep/providers/datadog_provider/datadog_provider.py
Labels: Bug, size:M

#2833 fix: datadog tags
  keep/providers/datadog_provider/datadog_provider.py
Labels: Provider, size:XS

#2667 chore: improve ticketing modal ux
  keep-ui/app/(keep)/alerts/alert-assign-ticket-modal.tsx
Labels: UI, size:M

#2835 fix: workflow executions in alert name
  keep-ui/app/(keep)/alerts/alert-name.tsx
  keep-ui/app/(keep)/alerts/models.tsx
  keep-ui/package-lock.json
  keep-ui/package.json
  keep/api/models/workflow.py
  keep/api/routes/workflows.py
Labels: Bug, size:M

#2837 fix(api): log 0 pending tasks
  keep/api/api.py
Labels: Bug, API, size:S

#2841 feat(ui): better wf execution page
  keep-ui/app/(keep)/workflows/builder/builder-workflow-testrun-modal.tsx
  keep-ui/app/(keep)/workflows/builder/builder.tsx
  keep-ui/app/(keep)/workflows/builder/types.ts
  keep-ui/app/(keep)/workflows/builder/workflow-execution-results.tsx
  keep-ui/app/(keep)/workflows/workflow-definition-yaml.tsx
  keep-ui/shared/api/ApiClient.ts
  keep-ui/utils/hooks/useWorkflowExecutions.ts
  keep/api/core/db.py
  keep/api/models/workflow.py
  keep/api/routes/workflows.py
  keep/providers/mysql_provider/mysql_provider.py
  keep/providers/openai_provider/openai_provider.py
  keep/providers/slack_provider/slack_provider.py
  keep/workflowmanager/workflowscheduler.py
Labels: Feature, UI, size:XL

#2843 fix: update preset to use UUID
  keep/api/core/db.py
  keep/api/routes/preset.py
Labels: Bug, size:XS

#2844 fix: import UUID
  keep/api/routes/preset.py
Labels: Bug, size:S

#2796 ci: speed up e2e: correct gitignore, cache playwright
  .github/workflows/test-pr-e2e.yml
  docker/Dockerfile.ui
  keep-ui/.dockerignore
Labels: Infrastructure, size:M, lgtm

#2847 fix: linked providers performance
  keep/api/core/db.py
Labels: Provider, size:M

#2849 fix(ui): add alert from UI
  keep-ui/app/(keep)/alerts/alert-push-alert-to-server-modal.tsx
Labels: UI, size:XS

#2854 fix(api): gcp timeout
  keep/providers/gcpmonitoring_provider/gcpmonitoring_provider.py
Labels: Bug, size:M, lgtm

#2855 fix(api): timeout
  keep/providers/gcpmonitoring_provider/gcpmonitoring_provider.py
Labels: Bug, size:S

#2856 fix(api): timeout
  keep/providers/gcpmonitoring_provider/gcpmonitoring_provider.py
Labels: Bug, size:XS

#2851 chore: opt-out for workflow email
  keep/api/core/db.py
  keep/api/models/db/migrations/versions/2024-12-17-12-48_3d20d954e058.py
  keep/api/models/db/workflow.py
  keep/contextmanager/contextmanager.py
  keep/parser/parser.py
  keep/workflowmanager/workflowscheduler.py
  pyproject.toml
  tests/conftest.py
Labels: size:L, lgtm

#2858 fix(api): timeout
  keep/providers/gcpmonitoring_provider/gcpmonitoring_provider.py
Labels: API, size:M, lgtm

#2863 docs: overall improvement
  docs/images/incident_edit.png
Labels: Documentation, size:XS, lgtm

#2859 fix: the `op.drop_column` is not working for sqlite
  keep/api/models/db/migrations/versions/2024-07-29-12-51_c91b348b94f2.py
Labels: Bug, size:M

#2838 docs: Add example of ELK integration using filebeat
  elk/README.md
  elk/docker-compose-elk.yml
  elk/filebeat.yml
  elk/logstash.conf
Labels: Documentation, size:L, lgtm

#2866 fix: k8s write secret proper exception
  keep/secretmanager/kubernetessecretmanager.py
  pyproject.toml
Labels: Bug, size:XS

#2869 fix: demo mode api key
  keep/api/core/demo_mode.py
Labels: Bug, size:XS

#2868 fix: Tests and fixes for IncidentBl
  keep/api/bl/incidents_bl.py
  keep/api/core/db.py
  keep/api/utils/enrichment_helpers.py
  poetry.lock
  pyproject.toml
  tests/test_incidents.py
Labels: Bug, size:XL

#2459 feat: add `/incidents/{id}/split` endpoint
  keep/api/core/db.py
  keep/api/core/dependencies.py
  keep/api/models/alert.py
  keep/api/routes/incidents.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_incidents.py
Labels: Feature, API, size:L

#2880 fix(api): update provider with json
  docs/api-ref/root.mdx
  docs/deployment/kubernetes/overview.mdx
  docs/incidents/overview.mdx
  docs/mint.json
  docs/overview/examples.mdx
  docs/platform/alerts.mdx
  docs/platform/overview.mdx
  docs/platform/settings.mdx
  docs/platform/support.mdx
  docs/providers/getting-started.mdx
  docs/providers/what-is-a-provider.mdx
  docs/workflows/syntax/state.mdx
  keep/api/routes/providers.py
  keep/providers/providers_service.py
  pyproject.toml
Labels: Provider, API, size:L

#2883 feat(api): add continue to workflows
  examples/workflows/ifelse.yml
  keep/api/core/db.py
  keep/contextmanager/contextmanager.py
  keep/step/step.py
  keep/workflowmanager/workflow.py
  pyproject.toml
  tests/test_workflow_execution.py
Labels: Feature, API, size:XL

#2846 feat: Add FRIGADE_DISABLED env to control Frigade intagration
  docker/Dockerfile.dev.api
  docs/deployment/configuration.mdx
  keep-ui/app/(keep)/settings/webhook-settings.tsx
  keep-ui/app/frigade-provider.tsx
  keep-ui/components/navbar/UserInfo.tsx
  keep-ui/shared/lib/server/getConfig.ts
  keep-ui/types/internal-config.ts
  tests/e2e_tests/docker-compose-e2e-mysql.yml
  tests/e2e_tests/docker-compose-e2e-postgres.yml
  tests/e2e_tests/docker-compose-e2e-redis.yml
Labels: Documentation, Feature, size:M, lgtm

#2797 feat(api): add grafana legacy
  docs/providers/documentation/grafana-provider.mdx
  ee/identitymanager/identity_managers/keycloak/keycloak_authverifier.py
  ee/identitymanager/identity_managers/keycloak/keycloak_identitymanager.py
  keep-ui/app/(keep)/providers/provider-form.tsx
  keep-ui/app/(keep)/providers/provider-logs.tsx
  keep-ui/utils/hooks/useProviderLogs.ts
  keep/api/core/db.py
  keep/api/core/elastic.py
  keep/api/logging.py
  keep/api/models/db/migrations/versions/2024-12-23-17-22_0c5e002094a9.py
  keep/api/models/db/provider.py
  keep/api/routes/providers.py
  keep/providers/base/base_provider.py
  keep/providers/grafana_provider/README.md
  keep/providers/grafana_provider/docker-compose.yml
  keep/providers/grafana_provider/grafana/grafana.ini
  keep/providers/grafana_provider/grafana/provisioning/access_control/custom_roles.yml
  keep/providers/grafana_provider/grafana/provisioning/alerting/alerts.yml
  keep/providers/grafana_provider/grafana/provisioning/dashboards/dashboards.yml
  keep/providers/grafana_provider/grafana/provisioning/dashboards/system.json
  keep/providers/grafana_provider/grafana/provisioning/datasources/datasource.yml
  keep/providers/grafana_provider/grafana/provisioning/notifiers/email.yml
  keep/providers/grafana_provider/grafana/provisioning/service_accounts/service_accounts.yml
  keep/providers/grafana_provider/grafana/provisioning/service_accounts/tokens.yml
  keep/providers/grafana_provider/grafana_provider.py
  keep/providers/grafana_provider/prometheus/prometheus.yml
  keep/providers/providers_service.py
  pyproject.toml
  tests/test_workflow_execution.py
Labels: Feature, Provider, size:XXL

#2885 fix(api): bigquery
  examples/workflows/bigquery.yml
  keep/providers/bigquery_provider/bigquery_provider.py
  pyproject.toml
Labels: Provider, size:M

#2871 feat: Add infra for cleaning up providers when deleted
  keep/contextmanager/contextmanager.py
  keep/providers/base/base_provider.py
  keep/providers/pagerduty_provider/pagerduty_provider.py
  keep/providers/providers_service.py
Labels: Feature, Provider, size:M, lgtm

#2889 chore: prefix metrics
  keep/api/core/metrics.py
  pyproject.toml
Labels: size:S

#2881 feat: split incidents UI
  keep-ui/app/(keep)/alerts/alert-associate-incident-modal.tsx
  keep-ui/app/(keep)/alerts/alert-change-status-modal.tsx
  keep-ui/app/(keep)/alerts/alert-pagination.tsx
  keep-ui/app/(keep)/alerts/alert-push-alert-to-server-modal.tsx
  keep-ui/app/(keep)/alerts/alerts-rules-builder.tsx
  keep-ui/app/(keep)/deduplication/DeduplicationSidebar.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alert-actions.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alert-table-body-skeleton.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
  keep-ui/app/(keep)/incidents/[id]/incident-tabs-navigation.tsx
  keep-ui/app/(keep)/settings/auth/users-sidebar.tsx
  keep-ui/app/(keep)/settings/create-api-key-modal.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/page.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-execution-table.tsx
  keep-ui/components/table/GenericTable.tsx
  keep-ui/components/table/Pagination.tsx
  keep-ui/components/ui/MultiSelect.tsx
  keep-ui/components/ui/Select.tsx
  keep-ui/entities/incidents/model/useIncidentActions.tsx
  keep-ui/entities/incidents/ui/IncidentIconName/IncidentIconName.tsx
  keep-ui/entities/incidents/ui/IncidentIconName/index.ts
  keep-ui/entities/incidents/ui/index.ts
  keep-ui/features/incident-list/ui/incident-pagination.tsx
  keep-ui/features/merge-incidents/ui/merge-incidents-modal.tsx
  keep-ui/features/same-incidents-in-the-past/ui/change-same-incident-in-the-past-form.tsx
  keep-ui/features/split-incident-alerts/index.ts
  keep-ui/features/split-incident-alerts/ui/split-incident-alerts-modal.tsx
  keep-ui/shared/ui/Select/Select.tsx
  keep-ui/shared/ui/Select/index.ts
  keep-ui/shared/ui/TablePagination/TablePagination.tsx
  keep-ui/shared/ui/VerticalRoundedList/VerticalRoundedList.tsx
  keep-ui/shared/ui/VerticalRoundedList/index.ts
  keep-ui/shared/ui/VerticalRoundedList/vertical-rounded-list.css
  keep-ui/shared/ui/index.ts
Labels: Feature, UI, size:XXL, lgtm

#2891 fix(opsgenie): retry for delete and silent failure
  keep/providers/opsgenie_provider/opsgenie_provider.py
  pyproject.toml
Labels: Bug, Provider, size:M

#2893 fix: Align documentation of PagerDuty
  docs/providers/documentation/pagerduty-provider.mdx
Labels: Documentation, size:XS

#2896 fix: Add check for None in providers provisioning form env var
  keep/parser/parser.py
Labels: Bug, size:XS, lgtm

#2727 feat: multiple alerts matching rules PoC
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationForm.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationSidebarBody.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/index.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/types.ts
  keep-ui/app/(keep)/rules/CorrelationTable.tsx
  keep-ui/utils/hooks/useRules.ts
  keep/api/bl/incidents_bl.py
  keep/api/core/db.py
  keep/api/core/demo_mode.py
  keep/api/models/db/alert.py
  keep/api/models/db/migrations/versions/2024-12-10-19-11_7297ae99cd21.py
  keep/api/models/db/rule.py
  keep/api/routes/rules.py
  keep/rulesengine/rulesengine.py
  scripts/simulate_alerts.py
  tests/test_rules_api.py
  tests/test_rules_engine.py
Labels: Feature, size:XL

#2900 chore: workflow builder: remove leftovers, unused imports, variables, css
  keep-ui/app/(keep)/workflows/[workflow_id]/executions.tsx
  keep-ui/app/(keep)/workflows/builder/BuilderChanagesTracker.tsx
  keep-ui/app/(keep)/workflows/builder/CustomEdge.tsx
  keep-ui/app/(keep)/workflows/builder/ReactFlowBuilder.tsx
  keep-ui/app/(keep)/workflows/builder/[workflowId]/page.tsx
  keep-ui/app/(keep)/workflows/builder/builder-card.tsx
  keep-ui/app/(keep)/workflows/builder/builder-modal.tsx
  keep-ui/app/(keep)/workflows/builder/builder-store.tsx
  keep-ui/app/(keep)/workflows/builder/builder-validators.tsx
  keep-ui/app/(keep)/workflows/builder/builder-workflow-testrun-modal.tsx
  keep-ui/app/(keep)/workflows/builder/builder.tsx
  keep-ui/app/(keep)/workflows/builder/legacy-workflow.types.ts
  keep-ui/app/(keep)/workflows/builder/loader.tsx
  keep-ui/app/(keep)/workflows/builder/page.client.tsx
  keep-ui/app/(keep)/workflows/builder/page.css
  keep-ui/app/(keep)/workflows/builder/page.tsx
  keep-ui/app/(keep)/workflows/builder/utils.tsx
  keep-ui/app/(keep)/workflows/workflow-menu.tsx
Labels: size:L

#2902 fix: frontend warnings
  keep-ui/features/incident-list/ui/incident-table-component.tsx
  keep-ui/features/incident-list/ui/incidents-table.tsx
  keep-ui/next.config.js
Labels: Bug, UI, size:M, lgtm

#2903 feat(api): simple rate limiting with slowapi
  docs/deployment/configuration.mdx
  keep/api/api.py
  keep/api/core/dependencies.py
  keep/api/core/limiter.py
  keep/api/core/metrics.py
  keep/api/routes/alerts.py
  keep/api/routes/metrics.py
  poetry.lock
  pyproject.toml
Labels: API, size:L, lgtm

#2913 fix: Round the provider form localhost warning corners
  keep-ui/app/(keep)/providers/provider-form.tsx
Labels: UI, size:XS, lgtm

#2908 feat(api): memory consumption and performance improvements
  .gitignore
  keep/api/alert_deduplicator/alert_deduplicator.py
  keep/api/core/demo_mode.py
  keep/api/core/metrics.py
  keep/api/logging.py
  keep/api/observability.py
  keep/api/routes/alerts.py
  keep/cli/cli.py
  keep/workflowmanager/workflowmanager.py
  keep/workflowmanager/workflowscheduler.py
  poetry.lock
  pyproject.toml
  tests/test_workflow_execution.py
  tests/test_workflowmanager.py
Labels: Feature, API, size:XL, lgtm

#2914 feat: Grafana + Prometheus with auto-provisioning of Keep dashboard
  .gitignore
  STRESS.md
  docker-compose.yml
  grafana/dashboards/keep.json
  grafana/provisioning/dashboards/keep.yml
  grafana/provisioning/datasources/prometheus.yml
  keep/api/api.py
  keep/providers/cilium_provider/cilium_provider.py
  keep/providers/providers_factory.py
  prometheus/prometheus.yml
Labels: Feature, Infrastructure, size:XL

#2921 fix(ui): keycloak
  keep-ui/auth.config.ts
  pyproject.toml
Labels: UI, size:XS, lgtm

#2919 fix(mapping): when using AND in matcher
  keep/api/bl/enrichments_bl.py
Labels: Bug, size:S, lgtm

#2923 fix: redirect on 401
  keep-ui/app/(keep)/providers/page.client.tsx
  keep-ui/app/(signin)/layout.tsx
  keep-ui/app/(signin)/signin/SignInForm.tsx
  keep-ui/features/incident-list/ui/incident-list-error.tsx
  keep-ui/middleware.ts
  keep-ui/shared/api/ApiClient.ts
  keep-ui/shared/api/server/createServerApiClient.ts
  keep-ui/shared/lib/hooks/useApi.tsx
  tests/e2e_tests/test_end_to_end.py
Labels: UI, API, size:L, lgtm

#2922 feat: Add soft-delete for incidents through the status
  keep-ui/app/(keep)/incidents/page.tsx
  keep-ui/entities/incidents/model/models.ts
  keep-ui/entities/incidents/ui/statuses.tsx
  keep-ui/features/change-incident-status/ui/incident-change-status-select.tsx
  keep-ui/features/incident-list/ui/incident-table-filters-context.tsx
  keep/api/bl/incidents_bl.py
  keep/api/core/db.py
  keep/api/models/alert.py
  tests/test_incidents.py
Labels: Feature, size:L, lgtm

#2926 fix(ui): service
  keep-ui/app/(keep)/topology/ui/map/getNodesAndEdgesFromTopologyData.ts
Labels: UI, size:XS, lgtm

#2924 feat: add AgroCD Provider
  README.md
  docs/mint.json
  docs/providers/documentation/argocd-provider.mdx
  docs/providers/overview.mdx
  keep-ui/app/(keep)/topology/ui/applications/applications-list.tsx
  keep-ui/app/(keep)/topology/ui/map/service-node.tsx
  keep-ui/public/icons/argocd-icon.png
  keep/api/models/db/topology.py
  keep/api/routes/preset.py
  keep/api/tasks/process_topology_task.py
  keep/providers/argocd_provider/README.md
  keep/providers/argocd_provider/__init__.py
  keep/providers/argocd_provider/applicationset.yaml
  keep/providers/argocd_provider/argocd_provider.py
  keep/topologies/topologies_service.py
Labels: Documentation, Feature, Provider, size:XL, lgtm

#2917 fix(hashicorp): Incorrect work with json in vault code
  keep/secretmanager/vaultsecretmanager.py
Labels: Bug, size:S, lgtm

#2932 feat(api): no auth for processing metrics
  keep/api/routes/metrics.py
  pyproject.toml
Labels: Feature, API, size:M, lgtm

#2934 fix(tests): hashicorp vault
  tests/test_secretmanager.py
Labels: size:XS

#2930 fix: Filter out deleted and resolved incidents from association form
  keep-ui/utils/hooks/useIncidents.ts
  keep/workflowmanager/workflowscheduler.py
Labels: size:XS

#2936 fix(opsgenie): retry on 404 as well
  keep/providers/opsgenie_provider/opsgenie_provider.py
Labels: Bug, size:XS, lgtm

#2937 fix(opsgenie): retry 404 again
  keep/providers/opsgenie_provider/opsgenie_provider.py
  pyproject.toml
Labels: Bug, Provider, size:M, lgtm

#2939 fix(ui): provider methods icon
  keep-ui/app/(keep)/alerts/alert-menu.tsx
Labels: UI, size:XS

#2941 fix(api): logs leak
  keep/api/logging.py
  pyproject.toml
Labels: Bug, API, size:XS, lgtm

#2942 feat: KEEP_CLI_IGNORE_SSL
  docs/cli/overview.mdx
  keep/cli/cli.py
Labels: CLI, size:XS

#2945 fix(api): postgres dashboards
  keep-ui/auth.config.ts
  keep/api/core/db.py
  pyproject.toml
Labels: Bug, size:M

#2947 fix(ui): sources
  keep-ui/tsconfig.json
Labels: UI, size:XS

#2949 fix(ui): keycloak
  keep-ui/auth.config.ts
  pyproject.toml
Labels: UI, size:XS, lgtm

#2956 fix: alert table theming and hover
  keep-ui/app/(keep)/alerts/alerts-table-body.tsx
  keep-ui/features/incident-list/ui/incident-table-component.tsx
Labels: Bug, size:S, lgtm
