Repository keephq/keep, pull requests merged in 2024-11, with the labels that each got.

#2377 feat(api): add index on alert table
  keep/api/models/db/alert.py
  keep/api/models/db/migrations/versions/2024-11-03-10-49_ef0b5b0df41c.py
  pyproject.toml
Labels: API, size:M, lgtm

#2333 feat(ai): correlate alerts into incidents
  docs/images/cilium_topology_map.png
  docs/mint.json
  docs/providers/documentation/cilium-provider.mdx
  docs/providers/overview.mdx
  examples/workflows/create_jira_ticket_upon_alerts.yml
  keep-ui/app/alerts/alert-actions.tsx
  keep-ui/app/alerts/alert-create-incident-ai-card.tsx
  keep-ui/app/alerts/alert-create-incident-ai-modal.tsx
  keep-ui/app/error.tsx
  keep-ui/app/incidents/incidents-table.tsx
  keep-ui/app/incidents/models.ts
  keep-ui/app/loading.tsx
  keep-ui/components/ui/Modal.tsx
  keep-ui/package-lock.json
  keep-ui/package.json
  keep-ui/pages/api/config.tsx
  keep-ui/public/icons/cilium-icon.png
  keep-ui/utils/apiUrl.ts
  keep-ui/utils/hooks/useConfig.ts
  keep/api/bl/ai_suggestion_bl.py
  keep/api/bl/incidents_bl.py
  keep/api/core/db.py
  keep/api/models/alert.py
  keep/api/models/db/ai_suggestion.py
  keep/api/models/db/migrations/env.py
  keep/api/models/db/migrations/versions/2024-10-31-18-01_273b29f368b7.py
  keep/api/routes/incidents.py
  keep/providers/base/base_provider.py
  keep/providers/cilium_provider/__init__.py
  keep/providers/cilium_provider/cilium_provider.py
  keep/providers/cilium_provider/generate_protobuf.py
  keep/providers/cilium_provider/grpc/__init__.py
  keep/providers/cilium_provider/grpc/flow/__init__.py
  keep/providers/cilium_provider/grpc/flow/flow.proto
  keep/providers/cilium_provider/grpc/flow/flow_pb2.py
  keep/providers/cilium_provider/grpc/flow/flow_pb2_grpc.py
  keep/providers/cilium_provider/grpc/google/protobuf/duration.proto
  keep/providers/cilium_provider/grpc/google/protobuf/timestamp.proto
  keep/providers/cilium_provider/grpc/google/protobuf/wrappers.proto
  keep/providers/cilium_provider/grpc/observer.proto
  keep/providers/cilium_provider/grpc/observer_pb2.py
  keep/providers/cilium_provider/grpc/observer_pb2_grpc.py
  keep/providers/cilium_provider/grpc/relay/__init__.py
  keep/providers/cilium_provider/grpc/relay/relay.proto
  keep/providers/cilium_provider/grpc/relay/relay_pb2.py
  keep/providers/cilium_provider/grpc/relay/relay_pb2_grpc.py
  keep/providers/cilium_provider/runtime_version.py
  keep/providers/providers_factory.py
  keep/providers/splunk_provider/splunk_provider.py
  scripts/docs_get_providers_list.py
  tests/test_incidents.py
Labels: Feature, Provider, UI, size:XXL, lgtm

#2366 feat: measure amount of running instances
  README.md
  docs/deployment/configuration.mdx
  keep-ui/.env.local.example
  keep/api/api.py
  keep/api/middlewares.py
  keep/cli/cli.py
  keep/posthog/posthog.py
  tests/fixtures/client.py
Labels: Feature, API, size:L, lgtm

#2384 fix: remove posthog from the app backend
  keep/api/api.py
  keep/api/middlewares.py
  keep/cli/cli.py
  keep/posthog/posthog.py
Labels: size:L

#2382 fix: don't call read_secret in pull_data_from_providers
  .github/workflows/test-pr.yml
  keep/api/routes/preset.py
  keep/providers/gcpmonitoring_provider/gcpmonitoring_provider.py
  tests/test_iohandler.py
  tests/test_workflow_execution.py
Labels: size:L, lgtm

#2390 feat(api): add version on startup logs
  keep/api/api.py
  pyproject.toml
Labels: Feature, API, size:S, lgtm

#2387 fix: One more attempt to return posthog
  keep/api/config.py
  keep/api/core/posthog.py
  keep/api/core/report_uptime.py
  keep/cli/cli.py
  tests/fixtures/client.py
Labels: Bug, size:L, lgtm

#2393 fix(provider): gcpmonitoring logs default severity
  keep/providers/gcpmonitoring_provider/gcpmonitoring_provider.py
Labels: Bug, Provider, size:S

#2397 chore(provider): zabbix from mediatype to script
  docs/images/pulling-enabled.png
  docs/images/pushing-enabled.png
  docs/overview/introduction.mdx
  docs/providers/overview.mdx
  keep-ui/next.config.js
  keep/api/routes/providers.py
  keep/providers/providers_service.py
  keep/providers/zabbix_provider/zabbix_provider.py
Labels: Documentation, Provider, size:L, lgtm

#2405 chore(ui): incident timeline dots animation
  keep-ui/app/incidents/[id]/timeline/incident-timeline.tsx
  keep-ui/components/navbar/InitPostHog.tsx
Labels: UI, size:S

#2396 feat(ui): add facets to alerts table
  keep-ui/app/alerts/alert-presets.tsx
  keep-ui/app/alerts/alert-severity-border.tsx
  keep-ui/app/alerts/alert-severity.tsx
  keep-ui/app/alerts/alert-table-facet.tsx
  keep-ui/app/alerts/alert-table-headers.tsx
  keep-ui/app/alerts/alert-table-utils.tsx
  keep-ui/app/alerts/alert-table.tsx
  keep-ui/app/alerts/alerts-table-body.tsx
  keep-ui/app/globals.css
Labels: Feature, UI, size:XL, lgtm

#2412 chore(version): bump to 0.28.2
  pyproject.toml
Labels: Dependencies, size:XS

#2421 fix: user-agent can be None
  keep/identitymanager/authverifierbase.py
  keep/providers/pagerduty_provider/pagerduty_provider.py
  keep/providers/sentry_provider/sentry_provider.py
Labels: size:S, lgtm

#2423 fix(api): when assignees is not a dict
  keep/api/models/alert.py
Labels: API, size:XS

#2425 fix: pagerduty provider default status
  keep/providers/pagerduty_provider/pagerduty_provider.py
Labels: Bug, Provider, size:XS

#2402 fix: overview rendering issue
  keep-ui/app/workflows/[workflow_id]/executions.tsx
  keep-ui/app/workflows/[workflow_id]/workflow-overview.tsx
Labels: Bug, UI, size:S, lgtm

#2427 fix: zabbix scopes permissions invalid parameter
  keep/providers/zabbix_provider/zabbix_provider.py
  pyproject.toml
Labels: Provider, size:S

#2432 fix(victoriametrics): support either full URL or host and port
  docs/providers/documentation/victoriametrics-provider.mdx
  keep/api/models/db/migrations/versions/2024-11-08-20-58_895fe80117aa.py
  keep/providers/victoriametrics_provider/victoriametrics_provider.py
Labels: Bug, Provider, size:L, lgtm

#2434 fix: disable pusher when env variables are not set
  keep/api/core/dependencies.py
  pyproject.toml
Labels: Bug, size:S

#2438 fix: pusher should not be disabled if host is not given
  keep/api/core/dependencies.py
  pyproject.toml
Labels: Bug, size:XS

#2443 fix: more indicative errors when connecting providers
  keep-ui/app/providers/provider-form.tsx
  keep/providers/pagerduty_provider/pagerduty_provider.py
Labels: Bug, Provider, size:S

#2394 feat: BaseIncidentProvider, PagerDuty incidents and process_incident
  docs/images/connect-to-pagerduty.png
  docs/images/pagerduty-account-scope.png
  docs/images/pagerduty-app-registration.png
  docs/images/pagerduty-oauth2-credentials.png
  docs/images/pagerduty-redirect-url.png
  docs/images/pagerduty-service-scope.png
  docs/providers/documentation/pagerduty-provider.mdx
  keep-ui/app/globals.css
  keep-ui/app/providers/filter-context/constants.ts
  keep-ui/app/providers/oauth2/[providerType]/page.tsx
  keep-ui/app/providers/provider-form.tsx
  keep-ui/app/providers/provider-tile.tsx
  keep-ui/app/providers/providers.tsx
  keep-ui/features/incident-list/ui/incident-table-component.tsx
  keep/api/arq_worker.py
  keep/api/bl/ai_suggestion_bl.py
  keep/api/bl/incidents_bl.py
  keep/api/core/db.py
  keep/api/models/alert.py
  keep/api/models/db/alert.py
  keep/api/models/db/migrations/versions/2024-11-10-13-06_620b6c048091.py
  keep/api/models/db/topology.py
  keep/api/models/provider.py
  keep/api/routes/incidents.py
  keep/api/routes/preset.py
  keep/api/routes/providers.py
  keep/api/routes/topology.py
  keep/api/tasks/process_event_task.py
  keep/api/tasks/process_incident_task.py
  keep/api/tasks/process_topology_task.py
  keep/identitymanager/rbac.py
  keep/providers/base/base_provider.py
  keep/providers/graylog_provider/graylog_provider.py
  keep/providers/pagerduty_provider/pagerduty_provider.py
  keep/providers/providers_factory.py
  keep/providers/sumologic_provider/sumologic_provider.py
  tests/test_pagerduty_provider.py
Labels: Feature, Provider, size:XL, lgtm

#2447 fix(pagerduty): ALERT_STATUS_MAP
  keep/providers/pagerduty_provider/pagerduty_provider.py
Labels: Provider, size:XS, lgtm

#2449 fix(pagerduty): backwards compatibility
  keep/providers/pagerduty_provider/pagerduty_provider.py
Labels: Bug, Provider, size:M, lgtm

#2450 fix: typo pagerduty
  keep/providers/pagerduty_provider/pagerduty_provider.py
Labels: size:XS, lgtm

#2453 fix(pd): another typo in PagerDuty
  keep/providers/pagerduty_provider/pagerduty_provider.py
Labels: size:XS

#2455 fix: bug alert history is not working trailing `/`
  keep-ui/app/providers/provider-form.tsx
  keep-ui/app/rules/CorrelationSidebar/CorrelationSidebarHeader.tsx
  keep-ui/utils/hooks/useAlerts.ts
Labels: Bug, UI, size:XS, lgtm

#2444 feat(api): better permisisons
  ee/identitymanager/identity_managers/keycloak/keycloak_identitymanager.py
  keep-ui/app/settings/auth/permissions-sidebar.tsx
  keep-ui/app/settings/auth/permissions-tab.tsx
  keep-ui/app/settings/auth/permissions-table.tsx
  keep-ui/app/settings/models.tsx
  keep-ui/app/settings/settings.client.tsx
  keep/api/core/db.py
  keep/api/models/user.py
  keep/api/routes/auth/permissions.py
  keep/api/routes/incidents.py
  pyproject.toml
Labels: Feature, UI, API, size:XL, lgtm

#2463 fix: do not fetch data twice due to wait for config
  keep-ui/app/config-provider.tsx
  keep-ui/app/layout.tsx
  keep-ui/app/posthog-provider.tsx
  keep-ui/components/navbar/InitPostHog.tsx
  keep-ui/components/navbar/Navbar.tsx
  keep-ui/shared/lib/server/getConfig.ts
  keep-ui/shared/ui/PostHogPageView.tsx
  keep-ui/utils/hooks/useConfig.ts
  keep-ui/utils/hooks/usePusher.ts
Labels: Bug, size:L, lgtm

#2471 fix: Hide excessive AI menu link (temporary)
  keep-ui/components/navbar/NoiseReductionLinks.tsx
Labels: Bug, UI, size:XS

#2475 chore(pagerduty): support event type in routing key
  keep/providers/pagerduty_provider/pagerduty_provider.py
  pyproject.toml
Labels: size:S

#2477 fix: extract base64 images from placeholder
  keep-ui/app/rules/CorrelationPlaceholder.tsx
  keep-ui/app/rules/PlaceholderSankey.tsx
  keep-ui/app/rules/ui/PlaceholderSankey.tsx
  keep-ui/public/rules-placeholder/image_0.png
  keep-ui/public/rules-placeholder/image_1.png
  keep-ui/public/rules-placeholder/image_2.png
  keep-ui/public/rules-placeholder/image_3.png
  keep-ui/public/rules-placeholder/image_4.png
  keep-ui/public/rules-placeholder/image_5.png
  keep-ui/public/rules-placeholder/image_6.png
Labels: Bug, size:L, lgtm

#2416 chore: add sentry to keep-ui
  docker-compose.common.yml
  docker-compose.dev.yml
  docker/Dockerfile.ui
  docs/deployment/configuration.mdx
  keep-ui/.gitignore
  keep-ui/app/error.tsx
  keep-ui/app/global-error.tsx
  keep-ui/components/navbar/Navbar.tsx
  keep-ui/components/navbar/SetSentryUser.tsx
  keep-ui/components/navbar/UserInfo.tsx
  keep-ui/instrumentation.ts
  keep-ui/middleware.tsx
  keep-ui/next.config.js
  keep-ui/package-lock.json
  keep-ui/package.json
  keep-ui/pages/_error.jsx
  keep-ui/sentry.client.config.ts
  keep-ui/sentry.edge.config.ts
  keep-ui/sentry.server.config.ts
  keep-ui/shared/lib/server/getConfig.ts
  keep-ui/shared/lib/useSetSentryUser.ts
  keep-ui/shared/lib/useSignOut.ts
  keep-ui/types/internal-config.ts
  tests/e2e_tests/docker-compose-e2e-mysql.yml
  tests/e2e_tests/docker-compose-e2e-postgres.yml
  tests/e2e_tests/docker-compose-e2e-redis.yml
Labels: UI, size:L, lgtm

#2480 fix(pd): dedup, severity and event_type derived from event context
  keep/contextmanager/contextmanager.py
  keep/providers/pagerduty_provider/pagerduty_provider.py
  pyproject.toml
Labels: Bug, size:M

#2483 fix: Resolved incidents can't be a target for RuleEngine
  keep/api/core/db.py
Labels: size:XS, lgtm

#2486 feat(ui): better time filtering
  keep-ui/app/alerts/TitleAndFilters.tsx
  keep-ui/app/alerts/alert-table-alert-facets.tsx
  keep-ui/app/alerts/alert-table-facet-utils.tsx
  keep-ui/app/alerts/alert-table.tsx
  keep-ui/components/ui/Calendar.tsx
  keep-ui/components/ui/DateRangePicker.tsx
Labels: Feature, UI, size:XL, lgtm

#2491 fix(servicenow): scopes
  keep/iohandler/iohandler.py
  keep/providers/servicenow_provider/servicenow_provider.py
Labels: Bug, Provider, size:S, lgtm

#2496 feat: Workflow Metrics
  docs/api-ref/dashboard/get-metric-widgets.mdx
  docs/api-ref/incidents/commit-with-ai.mdx
  docs/api-ref/incidents/create-incident.mdx
  docs/api-ref/incidents/create-with-ai.mdx
  docs/api-ref/incidents/receive-event.mdx
  docs/api-ref/root.mdx
  docs/api-ref/workflows/get-workflow-by-id-1.mdx
  docs/mint.json
  docs/openapi.json
  keep/api/api.py
  keep/api/core/db.py
  keep/api/routes/metrics.py
Labels: Documentation, size:M

#2484 fix: Local pusher & alert feed
  keep-ui/utils/hooks/usePusher.ts
  keep/api/tasks/process_event_task.py
Labels: Bug, size:M, lgtm

#2502 chore: servicenow should support oauth to obtain token
  keep/api/utils/email_utils.py
  keep/functions/__init__.py
  keep/iohandler/iohandler.py
  keep/providers/servicenow_provider/servicenow_provider.py
  keep/workflowmanager/workflowscheduler.py
Labels: size:L, lgtm

#2504 feat(docs): add docs for haproxy
  docs/deployment/kubernetes/installation.mdx
  pyproject.toml
Labels: Documentation, size:M, lgtm

#2501 feat: StatusCake Webhook integration
  docs/providers/documentation/statuscake-provider.mdx
  keep/providers/statuscake_provider/statuscake_provider.py
Labels: Documentation, Feature, Provider, size:L, lgtm

#2499 feat(api): read only
  keep-ui/app/layout.tsx
  keep-ui/app/read-only-banner.tsx
  keep-ui/shared/lib/server/getConfig.ts
  keep-ui/types/internal-config.ts
  keep/identitymanager/authverifierbase.py
Labels: Feature, API, size:M, lgtm

#2506 feat(docs): refactor readme
  README.md
  assets/connect_providers.gif
  assets/sneaknew.png
  assets/upload_workflow.gif
  assets/view_alerts.gif
Labels: Documentation, size:XL, lgtm

#2452 feat(api): support for graylog v4.x
  docs/providers/documentation/graylog-provider.mdx
  keep/providers/graylog_provider/README.md
  keep/providers/graylog_provider/docker-compose-v4.yml
  keep/providers/graylog_provider/graylog_provider.py
Labels: Documentation, Feature, Provider, size:L

#2509 chore: remove unused keep-ui's deps
  keep-ui/app/alerts/alert-table-headers.tsx
  keep-ui/app/config-provider.tsx
  keep-ui/app/incidents/[id]/incident-overview.tsx
  keep-ui/app/workflows/builder/ToolBox.tsx
  keep-ui/components/LinkWithIcon.tsx
  keep-ui/components/navbar/AlertsLinks.tsx
  keep-ui/components/navbar/CustomPresetAlertLinks.tsx
  keep-ui/components/navbar/IncidentLinks.tsx
  keep-ui/components/navbar/Navbar.tsx
  keep-ui/components/navbar/NoiseReductionLinks.tsx
  keep-ui/components/ui/discolsure-section.tsx
  keep-ui/middleware.tsx
  keep-ui/package-lock.json
  keep-ui/package.json
  keep-ui/tsconfig.json
  keep-ui/utils/fatigue.ts
Labels: size:XL

#2515 fix: render a11y stuff in a div outside of the <table/>
  keep-ui/app/alerts/alert-table-headers.tsx
  keep-ui/app/alerts/alert-table.tsx
Labels: Bug, size:S

#2519 fix: minor fix in gcp monitoring
  keep/providers/gcpmonitoring_provider/gcpmonitoring_provider.py
Labels: size:XS, lgtm

#2500 feat: provider appdynamics integration using access_token
  docs/providers/documentation/appdynamics-provider.mdx
  keep/providers/appdynamics_provider/appdynamics_provider.py
Labels: Feature, Provider, size:L

#2526 chore(release): new version 0.29.1
  pyproject.toml
Labels: size:XS

#2521 feat(ui): topology logos if possible
  keep-ui/app/topology/model/models.ts
  keep-ui/app/topology/ui/map/service-node.tsx
  keep-ui/public/icons/go-icon.png
  keep-ui/public/icons/nextjs-icon.png
  keep/api/utils/tenant_utils.py
Labels: UI, size:S, lgtm

#2532 fix: Response content for AppD
  keep/providers/appdynamics_provider/appdynamics_provider.py
Labels: Provider, size:XS

#2511 feat: skeleton loading state for alerts table
  keep-ui/app/alerts/[id]/page.tsx
  keep-ui/app/alerts/alert-table-alert-facets.tsx
  keep-ui/app/alerts/alert-table-facet-types.tsx
  keep-ui/app/alerts/alert-table-facet.tsx
  keep-ui/app/alerts/alert-table-utils.tsx
  keep-ui/app/alerts/alert-table.tsx
  keep-ui/app/alerts/alert-tabs.tsx
  keep-ui/app/alerts/alerts-table-body.tsx
  keep-ui/app/alerts/alerts.client.tsx
  keep-ui/app/alerts/alerts.tsx
  keep-ui/components/navbar/AlertsLinks.tsx
  keep-ui/components/navbar/CustomPresetAlertLinks.tsx
  keep-ui/components/navbar/UserInfo.tsx
  keep-ui/shared/lib/hooks/useMounted.tsx
  keep-ui/utils/hooks/useAlerts.ts
  keep-ui/utils/hooks/usePresets.ts
  tests/e2e_tests/test_end_to_end.py
Labels: Feature, UI, size:L, lgtm

#2531 fix(ui): styling in alert table when empty
  keep-ui/app/alerts/alerts-table-body.tsx
  keep/providers/servicenow_provider/servicenow_provider.py
Labels: UI, size:S, lgtm

#2529 fix(ui): auth type defaults to NOAUTH
  keep-ui/shared/lib/server/getConfig.ts
Labels: UI, size:XS, lgtm

#2547 feat: keep.join function for workflows
  keep/api/core/db.py
  keep/functions/__init__.py
  keep/iohandler/iohandler.py
  keep/providers/cloudwatch_provider/cloudwatch_provider.py
  poetry.lock
  pyproject.toml
Labels: Feature, size:M

#2550 fix: failing tests due to change in incident name
  keep/api/routes/preset.py
  keep/functions/__init__.py
  keep/providers/pagerduty_provider/pagerduty_provider.py
  tests/test_rules_engine.py
Labels: Bug, size:M

#2552 fix(pagerduty): enforce new format
  keep/providers/pagerduty_provider/pagerduty_provider.py
Labels: Provider, size:XS

#2554 chore: polish read-only banner
  keep-ui/app/read-only-banner.tsx
Labels: Feature, UI, size:M, lgtm

#2567 fix(nextauth): auth0
  keep-ui/auth.ts
Labels: size:XS, lgtm

#2561 feat: Demo mode v2 & moving background tasks outside of the server
  docker/Dockerfile.api
  docker/Dockerfile.dev.api
  docs/deployment/configuration.mdx
  keep/api/config.py
  keep/api/core/db.py
  keep/api/core/demo_mode.py
  keep/api/core/posthog.py
  keep/api/core/report_uptime.py
  keep/api/models/db/migrations/versions/2024-11-20-15-50_192157fd5788.py
  keep/api/models/db/system.py
  keep/entrypoint.sh
  keep/providers/cloudwatch_provider/alerts_mock.py
  keep/providers/datadog_provider/alerts_mock.py
  keep/providers/grafana_provider/alerts_mock.py
  keep/providers/prometheus_provider/alerts_mock.py
  keep/server_jobs_bg.py
  scripts/shoot_alerts_from_dump.py
  scripts/simulate_alerts.py
Labels: Documentation, Feature, size:XL, lgtm

#2573 chore(release): new version 0.29.3
  pyproject.toml
Labels: size:XS

#2572 feat(providers): added retry mechanism to google chat provider to overcome rate limiting
  keep/providers/google_chat_provider/google_chat_provider.py
Labels: Feature, Provider, size:M, lgtm

#2587 fix: feed counter
  keep-ui/app/(keep)/topology/api/index.ts
  keep-ui/app/(keep)/topology/model/useTopology.ts
  keep-ui/app/(keep)/topology/model/useTopologyApplications.ts
  keep-ui/utils/hooks/usePresets.ts
  keep-ui/utils/state.ts
  keep/api/core/db.py
  keep/api/routes/preset.py
  keep/api/tasks/process_event_task.py
Labels: Bug, size:L

#2571 refactor: migrate remaining API routes to App router
  keep-ui/app/(keep)/incidents/[id]/chat/page.client.tsx
  keep-ui/app/api/aws-marketplace/route.ts
  keep-ui/app/api/copilotkit/route.ts
  keep-ui/next-env.d.ts
  keep-ui/package-lock.json
  keep-ui/package.json
  keep-ui/pages/_error.jsx
  keep-ui/pages/api/aws-marketplace.tsx
  keep-ui/pages/api/copilotkit.ts
  keep-ui/shared/lib/server/getConfig.ts
  keep-ui/shared/ui/EmptyState/EmptyStateCard.tsx
  keep-ui/shared/ui/EmptyState/index.ts
  keep-ui/shared/ui/index.ts
  keep-ui/types/internal-config.ts
Labels: size:L, lgtm

#2516 fix(docs): readme
  README.md
Labels: Documentation, size:XS, lgtm

#2607 fix: Better Demo Alerts
  keep/api/core/demo_mode.py
  keep/providers/datadog_provider/alerts_mock.py
  keep/providers/prometheus_provider/alerts_mock.py
  keep/server_jobs_bg.py
Labels: size:M, lgtm

#2611 feat: consistent severity visuals
  keep-ui/app/(keep)/alerts/alert-assignee.tsx
  keep-ui/app/(keep)/alerts/alert-severity-border.tsx
  keep-ui/app/(keep)/alerts/alert-sidebar.tsx
  keep-ui/app/(keep)/alerts/alert-table-alert-facets.tsx
  keep-ui/app/(keep)/alerts/alert-table-facet-utils.tsx
  keep-ui/app/(keep)/alerts/alert-table-facet-value.tsx
  keep-ui/app/(keep)/alerts/alert-table-headers.tsx
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/app/(keep)/alerts/alert-table.tsx
  keep-ui/app/(keep)/alerts/alert-timeline.tsx
  keep-ui/app/(keep)/incidents/[id]/activity/incident-activity.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alert-menu.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
  keep-ui/app/(keep)/settings/auth/groups-sidebar.tsx
  keep-ui/app/(keep)/settings/auth/groups-tab.tsx
  keep-ui/app/(keep)/settings/auth/permissions-tab.tsx
  keep-ui/app/(keep)/settings/auth/users-settings.tsx
  keep-ui/components/navbar/UserAvatar.tsx
  keep-ui/entities/users/model/useUser.ts
  keep-ui/entities/users/model/useUsers.ts
  keep-ui/entities/users/ui/UserStatefulAvatar.tsx
  keep-ui/entities/users/ui/index.ts
  keep-ui/features/create-or-update-incident/ui/create-or-update-incident-form.tsx
  keep-ui/features/incident-list/ui/incidents-table.tsx
  keep-ui/package-lock.json
  keep-ui/package.json
  keep-ui/shared/lib/status-utils.ts
  keep-ui/shared/ui/FieldHeader.tsx
  keep-ui/shared/ui/Tooltip/Tooltip.tsx
  keep-ui/shared/ui/Tooltip/index.ts
  keep-ui/shared/ui/index.ts
  keep-ui/tailwind.config.js
Labels: Feature, UI, size:XL

#2576 feat(auth): azuread behind proxy
  docs/deployment/authentication/azuread-auth.mdx
  docs/images/azuread_3.png
  keep-ui/app/(keep)/alerts/alert-table.tsx
  keep-ui/app/(keep)/alerts/alerts-table-body.tsx
  keep-ui/app/(signin)/signin/SignInForm.tsx
  keep-ui/auth.ts
  keep-ui/middleware.tsx
  keep-ui/next.config.js
  keep-ui/package-lock.json
  keep-ui/package.json
  keep-ui/proxyFetch.node.ts
  keep-ui/proxyFetch.ts
  keep-ui/tsconfig.json
  keep-ui/types/auth.d.ts
  proxy/README.md
  proxy/docker-compose-proxy.yml
  pyproject.toml
Labels: Feature, UI, size:XL, lgtm

#2614 fix: docs tests in main
  .github/workflows/test-docs.yml
  docs/providers/documentation/gke-provider.mdx
  docs/providers/documentation/teams-provider.mdx
  docs/providers/overview.mdx
  scripts/docs_get_providers_list.py
Labels: Documentation, size:S, lgtm

#2619 fix(auth): fix preview environments
  keep-ui/app/api/auth/[...nextauth]/route.ts
  keep-ui/auth.config.ts
  keep-ui/auth.ts
  keep-ui/middleware.tsx
  proxy/squid.conf
Labels: size:XL, lgtm

#2625 chore(version): bump version
  pyproject.toml
Labels: size:XS, lgtm

#2581 feat: extraction side panel
  keep-ui/app/(keep)/extraction/create-or-update-extraction-rule.tsx
  keep-ui/app/(keep)/extraction/extraction.tsx
  keep-ui/app/(keep)/extraction/layout.tsx
  keep-ui/components/SidePanel.tsx
Labels: Feature, UI, size:L, lgtm

#2578 chore: reduce memory consumption and dockerfile size
  .gitignore
  docker/Dockerfile.api
  ee/experimental/__init__.py
  ee/experimental/ai_temp/.gitkeep
  ee/experimental/generative_utils.py
  ee/experimental/graph_utils.py
  ee/experimental/incident_utils.py
  ee/experimental/statistical_utils.py
  keep/api/api.py
  keep/api/arq_worker.py
  keep/api/bl/incidents_bl.py
  keep/api/config.py
  keep/api/consts.py
  keep/api/core/db.py
  keep/api/models/db/migrations/versions/2024-07-29-12-51_c91b348b94f2.py
  keep/api/routes/ai.py
  keep/api/routes/incidents.py
  keep/api/tasks/process_background_ai_task.py
  keep/api/utils/import_ee.py
  keep/cli/cli.py
  keep/identitymanager/identitymanagerfactory.py
  keep/providers/elastic_provider/elastic_provider.py
  keep/providers/grafana_provider/grafana_provider.py
  keep/providers/models/provider_config.py
  keep/providers/providers_factory.py
  keep/workflowmanager/workflowmanager.py
  poetry.lock
  pyproject.toml
  tests/test_alert_correlation.py
Labels: size:XXL

#2522 feat: pd service level operations
  docs/providers/documentation/pagerduty-provider.mdx
  keep/api/models/alert.py
  keep/providers/pagerduty_provider/pagerduty_provider.py
Labels: Documentation, Feature, size:M

#2630 fix(grafana): resolved status
  keep/providers/grafana_provider/grafana_provider.py
  pyproject.toml
Labels: Bug, size:XS, lgtm

#2559 feat: manually enrich alert
  keep-ui/app/(keep)/alerts/EnrichAlertSidePanel.tsx
  keep-ui/app/(keep)/alerts/alert-menu.tsx
  keep-ui/app/(keep)/alerts/alerts.tsx
  keep-ui/components/SidePanel.tsx
Labels: Feature, UI, size:L, lgtm

#2639 fix: move copilotkit initialization to the POST function
  keep-ui/app/api/copilotkit/route.ts
Labels: Bug, size:M, lgtm

#2641 feat(ui): better presets modal
  keep-ui/app/(keep)/alerts/alert-presets.tsx
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/app/(keep)/alerts/alert-table.tsx
  keep-ui/shared/lib/server/getConfig.ts
  keep-ui/utils/hooks/useSearchAlerts.ts
Labels: Feature, UI, size:L, lgtm

#2649 chore: alert timeline improvements
  keep-ui/app/(keep)/alerts/alert-actions.tsx
  keep-ui/app/(keep)/alerts/alert-menu.tsx
  keep-ui/app/(keep)/alerts/alert-name.tsx
  keep-ui/app/(keep)/alerts/alert-sidebar.tsx
  keep-ui/app/(keep)/alerts/alert-table-tab-panel.tsx
  keep-ui/app/(keep)/alerts/alert-table.tsx
  keep/api/core/demo_mode.py
  keep/api/routes/providers.py
  keep/providers/providers_factory.py
  pyproject.toml
Labels: UI, size:L, lgtm

#2650 feat: AI Plugins
  keep-ui/app/(keep)/ai/ai.tsx
  keep-ui/app/(keep)/ai/model.ts
  keep-ui/components/navbar/AILink.tsx
  keep-ui/components/navbar/NoiseReductionLinks.tsx
  keep-ui/public/keep_sleeping.png
  keep-ui/utils/hooks/useAI.ts
  keep/api/api.py
  keep/api/bl/incidents_bl.py
  keep/api/core/db.py
  keep/api/models/ai_external.py
  keep/api/models/db/ai_external.py
  keep/api/models/db/migrations/versions/2024-10-26-17-03_3f056d747d9e.py
  keep/api/routes/ai.py
  keep/api/routes/incidents.py
  tests/test_conditions.py
  tests/test_pagerduty_provider.py
  tests/test_topology.py
Labels: Feature, size:XL

#2657 chore: hide config in readonly mode
  keep/providers/providers_factory.py
Labels: size:XS

#2660 fix: override `authentication` in `provider_auth`
  keep/providers/providers_factory.py
Labels: Provider, size:S, lgtm

#2664 feat(api): add business hours
  examples/workflows/businesshours.yml
  keep-ui/shared/ui/utils/showErrorToast.tsx
  keep/api/tasks/notification_cache.py
  keep/api/tasks/process_event_task.py
  keep/functions/__init__.py
  keep/iohandler/iohandler.py
  keep/providers/prometheus_provider/alerts_mock.py
  poetry.lock
  pyproject.toml
  tests/test_functions.py
Labels: Feature, API, size:XL

#2668 fix:Multiple bypass keys
  keep/identitymanager/authverifierbase.py
Labels: Feature, size:XS, lgtm

#2671 fix: api client fix for read-only and empty responses
  keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
  keep-ui/shared/api/ApiClient.ts
Labels: API, size:M, lgtm

#2673 feat(ui): improve demo
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep/api/core/demo_mode.py
  keep/api/routes/providers.py
  keep/providers/cloudwatch_provider/alerts_mock.py
  keep/providers/cloudwatch_provider/cloudwatch_provider.py
  keep/providers/datadog_provider/alerts_mock.py
  keep/providers/datadog_provider/datadog_provider.py
  keep/providers/gcpmonitoring_provider/alerts_mock.py
  keep/providers/grafana_provider/alerts_mock.py
  keep/providers/grafana_provider/grafana_provider.py
  keep/providers/prometheus_provider/alerts_mock.py
  keep/providers/sentry_provider/alerts_mock.py
  tests/test_deduplications.py
Labels: UI, size:XXL

#2677 fix: polish scripts and workflows for readonly
  keep/api/core/demo_mode.py
  keep/parser/parser.py
  keep/providers/providers_factory.py
  keep/workflowmanager/workflowscheduler.py
Labels: size:S, lgtm

#2679 feat: AI Demo
  keep/api/core/demo_mode.py
  scripts/simulate_alerts.py
Labels: Feature, AI, size:L, lgtm

#2678 feat(ui): mobile
  keep-ui/app/(signin)/mobile/GithubButton.tsx
  keep-ui/app/(signin)/mobile/page.tsx
  keep-ui/middleware.tsx
  keep-ui/next.config.js
Labels: Feature, size:M, lgtm

#2682 fix(ui): typo in mapping page - enrich instead of enirch
  keep-ui/app/(keep)/mapping/layout.tsx
  keep-ui/next.config.js
Labels: UI, size:XS

#2684 fix(ui): typo worfklows to workflows
  README.md
  keep-ui/app/(keep)/workflows/[workflow_id]/table-filters.tsx
  keep-ui/app/(keep)/workflows/noworkflows.tsx
  keep-ui/app/(keep)/workflows/workflows.client.tsx
Labels: UI, size:XS, lgtm

#2675 feat(ui): alerts table search polish
  keep-ui/app/(keep)/alerts/alert-presets.tsx
  keep-ui/app/(keep)/alerts/alert-table.tsx
  keep-ui/app/(keep)/alerts/alerts-rules-builder.tsx
Labels: UI, size:L, lgtm

#2622 feat: parallel tests execution with xdist
  .github/workflows/test-pr.yml
  keep/api/routes/topology.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
Labels: Enhancement, Feature, size:M, lgtm

#2690 fix: add severity to vm
  keep/providers/victoriametrics_provider/victoriametrics_provider.py
  pyproject.toml
Labels: Bug, size:XS

#2687 fix: log str process events
  keep/api/tasks/process_event_task.py
Labels: size:XS

#2691 chore(slack): support attachments
  keep/providers/slack_provider/slack_provider.py
  pyproject.toml
Labels: size:L

#2695 feat(api): more verbose
  keep/api/core/dependencies.py
  keep/api/routes/alerts.py
  keep/api/tasks/process_event_task.py
  keep/identitymanager/identitymanagerfactory.py
  pyproject.toml
Labels: Feature, API, size:M, lgtm

#2699 fix(pagerduty): body is not hash
  keep-ui/app/(keep)/incidents/[id]/timeline/incident-timeline.tsx
  keep/providers/pagerduty_provider/pagerduty_provider.py
Labels: Bug, Provider, size:XS, lgtm

#2706 feat: better analytics
  keep/api/core/db.py
  keep/api/core/report_uptime.py
Labels: Feature, size:S

#2709 fix: alert formatting for AzureMonitoring provider
  keep/providers/azuremonitoring_provider/azuremonitoring_provider.py
Labels: Provider, size:XS, lgtm
