Repository keephq/keep, pull requests merged in 2025-08, with the labels that each got.

#5231 fix: any alert will always enriched with mapping rule with empty Machers
  keep/api/bl/enrichments_bl.py
Labels: Bug, size:XS, lgtm

#5243 feat: pagerduty provider override routing key in workflow #5242
  docs/snippets/providers/http-snippet-autogenerated.mdx
  docs/snippets/providers/pagerduty-snippet-autogenerated.mdx
  examples/workflows/pagerduty.yml
  keep/providers/pagerduty_provider/pagerduty_provider.py
Labels: Documentation, Feature, Provider, size:M, lgtm

#5256 feat: maint windows
  docs/deployment/configuration.mdx
  docs/overview/maintenance-windows.mdx
  keep/api/api.py
  keep/api/arq_worker.py
  keep/api/bl/maintenance_windows_bl.py
  keep/api/consts.py
  keep/api/core/db.py
  keep/api/models/action_type.py
  keep/api/models/alert.py
  keep/api/tasks/process_event_task.py
  keep/api/tasks/process_watcher_task.py
  keep/rulesengine/rulesengine.py
  tests/conftest.py
  tests/test_incidents.py
  tests/test_maintenance_windows_bl.py
Labels: Documentation, Feature, size:XL, lgtm

#5270 fix: dismiss until
  keep/api/bl/dismissal_expiry_bl.py
  keep/api/models/action_type.py
  keep/api/tasks/process_watcher_task.py
  pyproject.toml
  tests/test_dismissal_expiry_bug.py
  tests/test_maintenance_windows_bl.py
Labels: Bug, size:XXL, lgtm

#5279 fix: Bootstrap the default single tenant on when we are using onelogin as an IDP
  keep/api/config.py
Labels: Enhancement, Provider, size:XS, lgtm

#5281 fix: dismiss until
  keep-ui/next_build.sh
  keep/api/api.py
  keep/api/bl/dismissal_expiry_bl.py
  pyproject.toml
  tests/test_dismissal_expiry_bug.py
Labels: Bug, size:L, lgtm

#5286 feat: graf
  keep/providers/grafana_provider/grafana_provider.py
  keep/providers/kibana_provider/kibana_provider.py
  pyproject.toml
Labels: Feature, Provider, size:S, lgtm
