Repository keephq/keep, pull requests merged in 2025-03, with the labels that each got.

#3775 feat: compact rows
  keep-ui/app/(keep)/alerts/ColumnSelection.tsx
  keep-ui/app/(keep)/alerts/RowStyleSelection.tsx
  keep-ui/app/(keep)/alerts/SettingsSelection.tsx
  keep-ui/app/(keep)/alerts/ThemeSelection.tsx
  keep-ui/app/(keep)/alerts/TitleAndFilters.tsx
  keep-ui/app/(keep)/alerts/alert-grouped-row.tsx
  keep-ui/app/(keep)/alerts/alert-pagination-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/app/(keep)/alerts/alert-table.tsx
  keep-ui/app/(keep)/alerts/alerts-table-body.tsx
  keep-ui/entities/alerts/ui/AlertName/AlertName.tsx
Labels: Feature, size:XL, lgtm

#3762 feat: bulk delete (incidents)
  keep-ui/entities/incidents/model/useIncidentActions.tsx
  keep-ui/features/incident-list/ui/incidents-table.tsx
  keep/api/bl/incidents_bl.py
  keep/api/routes/incidents.py
Labels: Feature, size:M, lgtm

#3778 fix: dense
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
Labels: Bug, size:S, lgtm

#3780 feat: adjustable time
  keep-ui/app/(keep)/alerts/alert-table-headers.tsx
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-table-time-format.tsx
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/app/(keep)/alerts/alert-table.tsx
Labels: Feature, UI, size:L, lgtm

#3782 feat(ui): alert action tray
  keep-ui/app/(keep)/alerts/ActionTraySelection.tsx
  keep-ui/app/(keep)/alerts/SettingsSelection.tsx
  keep-ui/app/(keep)/alerts/alerts-table-body.tsx
  keep-ui/entities/alerts/ui/AlertName/AlertName.tsx
Labels: Feature, UI, size:L, lgtm

#3638 fix: yaml strings should stay the same after frontend parsed and stringified
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-detail-page.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-overview.tsx
  keep-ui/app/(keep)/workflows/workflow-tile.tsx
  keep-ui/app/(keep)/workflows/workflows.client.tsx
  keep-ui/app/raw/workflows/[workflow_filename]/route.ts
  keep-ui/entities/workflows/lib/__tests__/yaml-utils.test.ts
  keep-ui/entities/workflows/lib/parser.ts
  keep-ui/entities/workflows/lib/yaml-utils.ts
  keep-ui/entities/workflows/model/types.ts
  keep-ui/entities/workflows/model/useWorkflowActions.ts
  keep-ui/features/workflow-execution-results/ui/WorkflowDefinitionYAML.tsx
  keep-ui/jest.config.ts
  keep-ui/next.config.js
  keep-ui/package-lock.json
  keep-ui/package.json
  keep-ui/shared/ui/YAMLCodeblock/ui/MonacoYAMLEditor.tsx
  keep-ui/widgets/workflow-builder/workflow-builder-card.tsx
  keep-ui/widgets/workflow-builder/workflow-builder-widget.tsx
  keep-ui/widgets/workflow-builder/workflow-builder.tsx
  keep/functions/cyaml.py
  tests/conftest.py
  tests/e2e_tests/test_end_to_end.py
  tests/e2e_tests/workflow-quotes-sample.yaml
  tests/test_cyaml.py
Labels: Bug, UI, size:XXL, lgtm

#3784 chore: posthog ai assistant events
  keep-ui/app/(keep)/incidents/[id]/chat/incident-chat.tsx
  keep-ui/features/workflows/ai-assistant/ui/WorkflowBuilderChat.tsx
  keep-ui/shared/ui/PostHogPageView.tsx
Labels: UI, size:S, lgtm

#3788 fix: Validate and handle non-integer max_tokens input.
  keep/providers/deepseek_provider/deepseek_provider.py
Labels: size:XS, lgtm

#3785 fix: Make header change sort direction upon clicking
  keep-ui/app/(keep)/alerts/alert-table-headers.tsx
  tests/conftest.py
  tests/e2e_tests/test_filtering_sort_search_on_alerts.py
Labels: Bug, UI, size:S

#3791 fix: Fix slowness in sqlite when hard limit is involved
  keep/api/core/alerts.py
Labels: Bug, size:XS

#3794 feat(ui): improvements for action tray for alert
  docs/images/linked-providers.png
  docs/mint.json
  docs/providers/linked-providers.mdx
  keep-ui/app/(keep)/alerts/alert-grouped-row.tsx
  keep-ui/app/(keep)/alerts/alert-menu.tsx
  keep-ui/app/(keep)/alerts/alert-pagination-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/app/(keep)/alerts/alert-table.tsx
  keep-ui/app/(keep)/alerts/alerts-table-body.tsx
  keep-ui/entities/alerts/ui/AlertName/AlertName.tsx
  keep-ui/shared/ui/utils/table-utils.ts
  tests/e2e_tests/test_topology.py
Labels: UI, size:XL, lgtm

#3799 fix: add provider id to webhook template if provider is connected
  keep-ui/app/(keep)/providers/provider-semi-automated.tsx
  keep/api/routes/providers.py
Labels: Provider, size:S

#3807 fix(ui): add `/alerts/query` to allowed urls
  keep-ui/shared/api/ApiClient.ts
Labels: UI, size:XS

#3808 fix: Handle both dashed and non-dashed alert_id formats.
  keep-ui/app/(keep)/extraction/[rule_id]/executions/[execution_id]/page.tsx
  keep-ui/app/(keep)/mapping/[rule_id]/executions/[execution_id]/page.tsx
Labels: Bug, size:S, lgtm

#3816 feat: log groups for CW
  keep/providers/cloudwatch_provider/cloudwatch_provider.py
  pyproject.toml
Labels: Feature, Provider, size:S, lgtm

#3824 docs: fix enrich_alert example in blogpost.yml
  examples/workflows/blogpost.yml
Labels: Documentation, size:S

#3827 fix: multiline strings starting with "|"
  keep-ui/entities/workflows/lib/__tests__/yaml-utils.test.ts
  keep/functions/cyaml.py
  tests/test_cyaml.py
Labels: Bug, size:M, lgtm

#3837 feat: enrich from modal
  keep-ui/app/(keep)/alerts/ViewAlertModal.tsx
Labels: Feature, UI, size:XL, lgtm

#3818 fix: Clear filters in incidents does not reset default facets
  keep-ui/features/filter/facet-panel-server-side.tsx
  keep-ui/features/filter/facets-panel.tsx
  keep-ui/features/filter/models.tsx
  keep-ui/features/incident-list/ui/incident-list.tsx
Labels: Bug, UI, size:M

#3838 fix: Cel query gets empty after opening alert modal in keep UI
  keep-ui/app/(keep)/alerts/alert-history.tsx
  keep-ui/app/(keep)/alerts/alert-menu.tsx
  keep-ui/app/(keep)/alerts/alerts.tsx
Labels: Bug, UI, size:M

#3841 fix: universal EmptyStateCard and more helpful ErrorComponent
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/app/(keep)/alerts/alerts-table-body.tsx
  keep-ui/app/(keep)/extraction/extraction.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
  keep-ui/app/(keep)/incidents/[id]/chat/incident-chat.tsx
  keep-ui/app/(keep)/incidents/[id]/timeline/incident-timeline.tsx
  keep-ui/app/(keep)/incidents/[id]/workflows/incident-workflow-empty.tsx
  keep-ui/app/(keep)/maintenance/maintenance.tsx
  keep-ui/app/(keep)/mapping/mapping.tsx
  keep-ui/app/(keep)/providers/provider-logs.tsx
  keep-ui/app/(keep)/rules/CorrelationPlaceholder.tsx
  keep-ui/app/(keep)/topology/ui/applications/applications-list.tsx
  keep-ui/app/(keep)/topology/ui/map/topology-map.tsx
  keep-ui/app/(keep)/workflows/noworkflows.tsx
  keep-ui/app/(keep)/workflows/workflows.client.tsx
  keep-ui/components/icons/index.tsx
  keep-ui/components/ui/EmptyStateCard.tsx
  keep-ui/components/ui/index.ts
  keep-ui/features/incident-list/ui/incident-list.tsx
  keep-ui/features/incident-list/ui/incidents-not-found.tsx
  keep-ui/shared/lib/hooks/useHealth.ts
  keep-ui/shared/ui/EmptyState/EmptyStateCard.tsx
  keep-ui/shared/ui/ErrorComponent/ErrorComponent.tsx
  keep-ui/shared/ui/PageSubtitle.tsx
  keep-ui/shared/ui/PageTitle.tsx
Labels: UI, size:XL, lgtm

#3845 fix: alert menu
  keep-ui/app/(keep)/alerts/alert-menu.tsx
  keep-ui/app/(keep)/alerts/alert-sidebar.tsx
Labels: Bug, UI, size:S, lgtm

#3839 fix: Workflow manual run modal improvements
  keep-ui/app/(keep)/workflows/manual-run-workflow-modal.tsx
  keep-ui/entities/workflows/ui/WorkflowTriggerBadge.tsx
Labels: UI, size:L, lgtm

#3828 feat: friendly Cloudwatch response format (breaking change) + fix for rendering of if keep.functions
  examples/workflows/retrieve_cloudwatch_logs.yaml
  keep/functions/__init__.py
  keep/iohandler/iohandler.py
  keep/providers/cloudwatch_provider/cloudwatch_provider.py
  keep/step/step.py
  pyproject.toml
  tests/conftest.py
  tests/test_steps.py
Labels: Feature, Provider, size:L, lgtm

#3852 feat: list of addresses for SMTP
  keep/providers/smtp_provider/smtp_provider.py
  pyproject.toml
Labels: Feature, Provider, size:XS

#3856 fix: Refactor timestamp handling for incident alerts
  keep/api/core/db.py
  tests/conftest.py
  tests/test_incidents.py
Labels: Bug, size:M

#3868 feat: better mails and mapping
  keep-ui/app/(keep)/mapping/create-or-edit-mapping.tsx
  keep/api/bl/enrichments_bl.py
  keep/api/models/db/mapping.py
  keep/api/routes/mapping.py
  keep/api/tasks/process_event_task.py
  keep/providers/mailgun_provider/mailgun_provider.py
Labels: Feature, size:L, lgtm

#3870 fix: pagination
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
Labels: Bug, UI, size:XS

#3873 fix(api): strip
  keep/api/tasks/process_event_task.py
Labels: API, size:XS, lgtm

#3877 feat: list format
  keep-ui/app/(keep)/alerts/alert-table-headers.tsx
  keep-ui/app/(keep)/alerts/alert-table-list-format.tsx
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/app/(keep)/alerts/alert-table.tsx
Labels: Feature, UI, size:L

#3880 fix: smtp
  examples/workflows/send_smtp_email.yml
  keep/providers/smtp_provider/smtp_provider.py
  pyproject.toml
Labels: Bug, size:M, lgtm

#3883 fix: webhook provider
  examples/workflows/webhook_example.yml
  keep/providers/vectordev_provider/vectordev_provider.py
  keep/providers/webhook_provider/webhook_provider.py
  pyproject.toml
Labels: Bug, Provider, size:M, lgtm

#3848 refactor: remove tabs from presets
  keep-ui/app/(keep)/alerts/alert-tab-modal.tsx
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-table.tsx
  keep-ui/app/(keep)/alerts/alert-tabs.tsx
Labels: size:L, lgtm

#3875 feat: ai correlation on empty screens
  keep-ui/app/(keep)/alerts/alert-actions.tsx
  keep-ui/app/(keep)/alerts/alert-pagination-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-push-alert-to-server-modal.tsx
  keep-ui/app/(keep)/alerts/alert-table-headers.tsx
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-table-tab-panel-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-table.tsx
  keep-ui/app/(keep)/alerts/alerts-table-body.tsx
  keep-ui/app/(keep)/deduplication/DeduplicationTable.tsx
  keep-ui/app/(keep)/extraction/extractions-table.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
  keep-ui/app/(keep)/incidents/[id]/workflows/incident-workflow-table.tsx
  keep-ui/app/(keep)/incidents/page.tsx
  keep-ui/app/(keep)/incidents/predicted-incidents-table.tsx
  keep-ui/app/(keep)/maintenance/maintenance-rules-table.tsx
  keep-ui/app/(keep)/mapping/rules-table.tsx
  keep-ui/app/(keep)/rules/CorrelationTable.tsx
  keep-ui/components/navbar/IncidentLinks.tsx
  keep-ui/entities/incidents/model/models.ts
  keep-ui/features/incident-list/ui/incident-list.tsx
  keep-ui/features/incident-list/ui/incidents-not-found.tsx
  keep-ui/shared/lib/state-utils.ts
  keep-ui/shared/ui/TablePagination/TablePagination.tsx
  keep-ui/utils/hooks/useAlerts.ts
  keep-ui/utils/hooks/useIncidents.ts
  tests/e2e_tests/test_end_to_end.py
  tests/e2e_tests/test_filtering_sort_search_on_alerts.py
Labels: Feature, UI, AI, size:XL, lgtm

#3854 fix: provider docs links
  keep-ui/app/(keep)/providers/provider-form.tsx
Labels: Bug, Provider, size:M

#3893 fix: resource not accessible by integration problem
  .github/workflows/lint-pr.yml
Labels: Bug, size:XS

#3894 fix: save `if` on steps and actions when converting back to yaml,
  keep-ui/entities/workflows/lib/__tests__/parser.test.ts
  keep-ui/entities/workflows/lib/parser.ts
  keep-ui/entities/workflows/model/validation.ts
  keep-ui/features/workflows/builder/ui/Editor/StepEditor.tsx
Labels: Bug, UI, size:XL, lgtm

#3895 fix(sentry): issue url
  keep/providers/sentry_provider/sentry_provider.py
Labels: size:XS, lgtm

#3905 fix: webhook provider ignore certain kwargs
  keep/providers/webhook_provider/webhook_provider.py
  pyproject.toml
Labels: Provider, size:S

#3900 feat: incident link from alert table
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep/api/routes/alerts.py
  keep/api/utils/enrichment_helpers.py
Labels: Feature, UI, size:M, lgtm

#3910 fix(ui): correlation rule fields
  keep-ui/app/(keep)/rules/CorrelationPlaceholder.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/RuleFields.tsx
Labels: UI, size:S, lgtm

#3912 fix: Refactor alert fingerprint logging for consistency.
  keep/api/core/db.py
Labels: size:M, lgtm

#3914 fix: Add `resolve_on` field to incident creation for grouping rule
  keep/api/core/db.py
  tests/test_rules_engine.py
Labels: Bug, size:L, lgtm

#3921 fix(ui): incident name ai generated
  examples/workflows/webhook_example_foreach.yml
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep/providers/webhook_provider/webhook_provider.py
Labels: UI, size:M, lgtm

#3925 fix: update available fields
  keep-ui/app/(keep)/rules/CorrelationSidebar/RuleFields.tsx
Labels: size:S, lgtm

#3926 fix: Fixes ArgoCD applications that have multiple sources
  keep/providers/argocd_provider/argocd_provider.py
Labels: Bug, size:S, lgtm

#3740 feat: Filtering/search workflows
  keep-ui/app/(keep)/workflows/page.tsx
  keep-ui/app/(keep)/workflows/workflows.client.tsx
  keep-ui/features/filter/index.ts
  keep-ui/features/filter/pagination.tsx
  keep-ui/features/filter/search-input.tsx
  keep-ui/utils/hooks/useWorkflows.ts
  keep-ui/utils/hooks/useWorkflowsV2.ts
  keep/api/core/cel_to_sql/sql_providers/mysql.py
  keep/api/core/cel_to_sql/sql_providers/postgresql.py
  keep/api/core/cel_to_sql/sql_providers/sqlite.py
  keep/api/core/db.py
  keep/api/core/workflows.py
  keep/api/routes/facets.py
  keep/api/routes/workflows.py
  keep/workflowmanager/workflowstore.py
  tests/cel_to_sql/cel-to-sql-test-cases.json
Labels: Feature, size:XXL

#3927 feat: resolve manual incidents automatically
  keep/api/bl/incidents_bl.py
  keep/api/tasks/process_event_task.py
  keep/rulesengine/rulesengine.py
Labels: Feature, size:L

#3930 feat: librenms provider
  README.md
  docs/images/librenms-provider_1.png
  docs/images/librenms-provider_2.png
  docs/images/librenms-provider_3.png
  docs/images/librenms-provider_4.png
  docs/images/librenms-provider_5.png
  docs/images/librenms-provider_6.png
  docs/mint.json
  docs/providers/documentation/libre_nms-provider.mdx
  docs/providers/overview.mdx
  keep-ui/public/icons/libre_nms-icon.png
  keep/providers/libre_nms_provider/README.md
  keep/providers/libre_nms_provider/__init__.py
  keep/providers/libre_nms_provider/alerts_mock.py
  keep/providers/libre_nms_provider/libre_nms_provider.py
Labels: Documentation, Feature, Provider, size:XL, lgtm

#3929 refactor: incident to its own files
  keep/api/bl/ai_suggestion_bl.py
  keep/api/bl/enrichments_bl.py
  keep/api/bl/incidents_bl.py
  keep/api/bl/maintenance_windows_bl.py
  keep/api/core/db.py
  keep/api/core/incidents.py
  keep/api/models/action_type.py
  keep/api/models/alert.py
  keep/api/models/alert_audit.py
  keep/api/models/db/alert.py
  keep/api/models/db/enrichment_event.py
  keep/api/models/db/helpers.py
  keep/api/models/db/incident.py
  keep/api/models/incident.py
  keep/api/models/severity_base.py
  keep/api/routes/alerts.py
  keep/api/routes/incidents.py
  keep/api/routes/workflows.py
  keep/api/tasks/process_event_task.py
  keep/api/tasks/process_incident_task.py
  keep/api/utils/pagination.py
  keep/providers/base/base_provider.py
  keep/providers/pagerduty_provider/pagerduty_provider.py
  keep/rulesengine/rulesengine.py
  keep/topologies/topology_processor.py
  keep/workflowmanager/workflowmanager.py
  keep/workflowmanager/workflowscheduler.py
  tests/test_enrichments.py
  tests/test_functions.py
  tests/test_incidents.py
  tests/test_pagerduty_provider.py
  tests/test_rules_engine.py
  tests/test_search_alerts.py
  tests/test_workflow_execution.py
Labels: size:XXL

#3943 fix: Remove unnecessary effect from facets panel
  keep-ui/features/filter/facets-panel.tsx
Labels: Bug, UI, size:S

#3935 fix: Fixes after workflow facets merge
  keep-ui/app/(keep)/workflows/workflows.client.tsx
  keep/api/core/workflows.py
Labels: Bug, size:M

#3646 feat: Incidents report
  keep-ui/features/incident-list/ui/incident-list.tsx
  keep-ui/features/incident-list/ui/incidents-report/generate-report-modal.tsx
  keep-ui/features/incident-list/ui/incidents-report/incident-severity-metric.tsx
  keep-ui/features/incident-list/ui/incidents-report/incidents-report.tsx
  keep-ui/features/incident-list/ui/incidents-report/index.ts
  keep-ui/features/incident-list/ui/incidents-report/models.ts
  keep-ui/features/incident-list/ui/incidents-report/pie-chart.tsx
  keep-ui/features/incident-list/ui/incidents-report/use-report-data.ts
  keep-ui/features/incident-list/ui/incidents-table.tsx
  keep-ui/package-lock.json
  keep-ui/package.json
  keep/api/bl/incident_reports.py
  keep/api/bl/incidents_bl.py
  keep/api/routes/incidents.py
Labels: Feature, UI, javascript, Incident, size:XL

#3947 fix: Fix bug in case insensitive search CEL query using mysql
  keep-ui/app/(keep)/workflows/workflows.client.tsx
  keep/api/core/cel_to_sql/sql_providers/mysql.py
  tests/cel_to_sql/cel-to-sql-test-cases.json
Labels: Bug, size:M

#3949 fix: cli installation instructions
  docs/cli/installation.mdx
Labels: Documentation, size:S

#3946 fix(ui): incident col and netbox provider
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep/providers/netbox_provider/netbox_provider.py
Labels: Provider, UI, size:L

#3879 feat: custom image
  .github/workflows/auto-resolve-keep.yml
  docker/Dockerfile.api
  keep-ui/app/(keep)/alerts/alert-menu.tsx
  keep-ui/app/(keep)/alerts/alert-push-alert-to-server-modal.tsx
  keep-ui/app/(keep)/alerts/alert-sidebar.tsx
  keep-ui/app/(keep)/alerts/alert-table-facet-value.tsx
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/app/(keep)/alerts/alert-timeline.tsx
  keep-ui/app/(keep)/deduplication/DeduplicationTable.tsx
  keep-ui/app/(keep)/providers/provider-tile.tsx
  keep-ui/app/(keep)/settings/provider-images/page.tsx
  keep-ui/app/(keep)/settings/provider-images/provider-image-list.tsx
  keep-ui/app/(keep)/settings/provider-images/provider-image-uploader.tsx
  keep-ui/app/(keep)/settings/provider-images/provider-images-settings.tsx
  keep-ui/app/(keep)/settings/settings.client.tsx
  keep-ui/components/ui/DynamicProviderIcon.tsx
  keep-ui/components/ui/ImagePreviewTooltip.tsx
  keep-ui/entities/provider-images/model/useProviderImages.ts
  keep-ui/middleware.ts
  keep/api/api.py
  keep/api/core/db.py
  keep/api/models/db/migrations/versions/2025-03-05-15-55_0b80bda47ee2.py
  keep/api/models/db/provider_image.py
  keep/api/routes/provider_images.py
  tests/e2e_tests/test_filtering_sort_search_on_alerts.py
Labels: Feature, UI, size:XL

#3948 fix: Fix bug when not all workflows have been displayed
  keep-ui/app/(keep)/workflows/workflows.client.tsx
  keep/api/core/workflows.py
Labels: Bug, size:M

#3952 fix: unique execution number to include workflow id
  keep/workflowmanager/workflowscheduler.py
Labels: Bug, size:S, lgtm

#3956 fix: we forgot provider image on facets
  keep-ui/features/incident-list/ui/incident-list.tsx
Labels: UI, size:XS

#3951 fix: Fix broken sorting in workflow query
  keep/api/core/workflows.py
Labels: Bug, size:XS, lgtm

#3955 fix: workflow ui removes conditions and foreach
  keep-ui/entities/workflows/lib/__tests__/parser.test.ts
  keep-ui/entities/workflows/lib/parser.ts
Labels: Bug, UI, size:L

#3968 fix: Refactor incident resolution and improve database handling.
  keep/api/bl/incidents_bl.py
  keep/api/tasks/process_event_task.py
  keep/rulesengine/rulesengine.py
Labels: size:M, lgtm

#3967 fix: Change join order in alerts query to prevent duplicated alerts
  keep/api/core/alerts.py
  keep/api/core/facets.py
Labels: Bug, size:M, lgtm

#3970 fix: several issues in incidents and correlation rule builder
  keep-ui/app/(keep)/alerts/alerts-rules-builder.tsx
  keep-ui/app/(keep)/incidents/[id]/activity/incident-activity.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/RuleFields.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/RuleGroup.tsx
  keep-ui/app/(keep)/rules/CorrelationTable.tsx
  keep-ui/entities/presets/model/usePresetActions.ts
  keep-ui/features/change-incident-status/ui/incident-change-status-select.tsx
  keep-ui/package-lock.json
  keep-ui/package.json
  keep/api/bl/enrichments_bl.py
  keep/api/core/db.py
  keep/api/routes/alerts.py
  keep/api/routes/incidents.py
Labels: Bug, UI, size:L

#3973 fix(ui): incidents name
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
Labels: UI, size:XS, lgtm

#3975 fix(ui): overflow none to incident field
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
Labels: UI, size:S, lgtm

#3977 fix: manual workflow modal
  keep-ui/app/(keep)/workflows/manual-run-workflow-modal.tsx
  keep-ui/utils/hooks/useWorkflows.ts
Labels: Bug, UI, size:S

#3974 fix: handle duplicated row ids in alerts table rendering
  keep-ui/app/(keep)/alerts/alerts-table-body.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
Labels: Bug, UI, size:M

#3980 feat: fixes and improvements for the demo
  keep-ui/app/(keep)/alerts/alert-menu.tsx
  keep-ui/app/(keep)/incidents/[id]/chat/incident-chat.tsx
  keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
  keep-ui/components/ui/RootCauseAnalysis.tsx
  keep/api/bl/enrichments_bl.py
  keep/providers/cilium_provider/cilium_provider.py
  keep/providers/github_provider/github_provider.py
  keep/providers/postgres_provider/postgres_provider.py
  pyproject.toml
Labels: UI, size:M, lgtm

#3959 feat: Add incident handling and enrichment improvements
  keep/api/core/alerts.py
  keep/api/core/db.py
  keep/providers/slack_provider/slack_provider.py
  keep/workflowmanager/workflowmanager.py
  keep/workflowmanager/workflowscheduler.py
Labels: Incident, size:S, lgtm

#3981 feat: adding flashduty provider
  README.md
  docs/images/flashduty_1.png
  docs/images/flashduty_2.png
  docs/images/flashduty_3.png
  docs/mint.json
  docs/providers/documentation/flashduty-provider.mdx
  examples/workflows/flashduty_example.yml
  keep-ui/public/icons/flashduty-icon.png
  keep/providers/flashduty_provider/__init__.py
  keep/providers/flashduty_provider/flashduty_provider.py
Labels: Documentation, Provider, size:L, lgtm

#3990 fix(mattermost): attachments
  docs/providers/overview.mdx
  keep/providers/mattermost_provider/mattermost_provider.py
Labels: Bug, Provider, size:S

#3992 feat: incident prefix with running number
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationForm.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationSidebarBody.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/index.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/types.ts
  keep-ui/app/(keep)/rules/CorrelationTable.tsx
  keep-ui/utils/hooks/useRules.ts
  keep/api/core/db.py
  keep/api/models/db/incident.py
  keep/api/models/db/migrations/versions/2025-03-12-13-22_ab333148350e.py
  keep/api/models/db/rule.py
  keep/api/routes/rules.py
  keep/rulesengine/rulesengine.py
  tests/test_rules_engine.py
Labels: Feature, size:L, lgtm

#3620 feat: Workflow Secrets
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-detail-page.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-secrets.tsx
  keep-ui/entities/workflows/model/types.ts
  keep-ui/entities/workflows/ui/NodeTriggerIcon.tsx
  keep-ui/shared/lib/hooks/useApi.tsx
  keep-ui/utils/hooks/useWorkFlowSecrets.ts
  keep/api/routes/workflows.py
  keep/contextmanager/contextmanager.py
  keep/parser/parser.py
  keep/workflowmanager/workflow.py
Labels: Feature, 🙋 Bounty claim, size:L, lgtm

#3993 feat: AI docs
  docs/deployment/authentication/auth0-auth.mdx
  docs/deployment/authentication/azuread-auth.mdx
  docs/deployment/authentication/keycloak-auth.mdx
  docs/deployment/authentication/oauth2proxy-auth.mdx
  docs/images/ai-correlation-1.png
  docs/images/ai-correlation-2.png
  docs/images/ai-semi-automatic-correlation.png
  docs/images/ai-workflow-assistant.png
  docs/mint.json
  docs/overview/ai-correlation.mdx
  docs/overview/ai-in-workflows.mdx
  docs/overview/ai-incident-assistant.mdx
  docs/overview/ai-semi-automatic-correlation.mdx
  docs/overview/ai-workflow-assistant.mdx
  docs/overview/correlation-rules.mdx
Labels: Documentation, Feature, size:L, lgtm

#3987 fix: Add migration to remove and prevent multiple enrichments per fingerprint
  keep/api/models/db/migrations/versions/2025-03-11-16-54_16309df224d1.py
  keep/api/models/db/migrations/versions/2025-03-12-14-36_9f11356d8ed9.py
Labels: Bug, size:L

#3996 fix(ui): icons missing from TriggerIcon
  keep-ui/entities/workflows/ui/TriggerIcon.tsx
Labels: UI, size:XS

#4002 fix: enrichment.db_session
  keep/api/bl/enrichments_bl.py
  pyproject.toml
Labels: Bug, size:XS, lgtm

#4004 fix: comments for a few endpoints
  keep/api/routes/providers.py
Labels: size:S

#4009 fix: Refactor incident status change logic to incident_bl.
  keep/api/bl/enrichments_bl.py
  keep/api/bl/incidents_bl.py
  keep/api/routes/incidents.py
Labels: size:L

#4015 fix: Update concurrency group in workflow files for tests
  .github/workflows/test-pr-e2e.yml
  .github/workflows/test-pr-integrations.yml
  .github/workflows/test-pr-ut-ui.yml
  .github/workflows/test-pr-ut.yml
Labels: Infrastructure, size:S

#3896 feat: processing event error UX
  .github/workflows/test-pr-e2e.yml
  docker-compose.common.yml
  keep-ui/app/(keep)/alerts/alert-error-event-modal.tsx
  keep-ui/app/(keep)/alerts/alert-preset-manager.tsx
  keep-ui/app/(signin)/signin/SignInForm.tsx
  keep-ui/app/actions/authactions.ts
  keep-ui/auth.config.ts
  keep-ui/next.config.js
  keep-ui/utils/hooks/useAlerts.ts
  keep/api/core/db.py
  keep/api/models/alert.py
  keep/api/models/db/alert.py
  keep/api/models/db/migrations/env.py
  keep/api/models/db/migrations/versions/2025-03-12-14-46_ca74b4a04371.py
  keep/api/routes/alerts.py
  keep/api/tasks/process_event_task.py
  keep/identitymanager/identity_managers/noauth/noauth_authverifier.py
  keep/identitymanager/identity_managers/noauth/noauth_identitymanager.py
  tests/conftest.py
  tests/e2e_tests/docker-compose-e2e-mysql.yml
  tests/e2e_tests/docker-compose-e2e-postgres.yml
  tests/e2e_tests/test_end_to_end.py
  tests/e2e_tests/test_end_to_end_db_auth.py
  tests/e2e_tests/test_filtering_sort_search_on_alerts.py
  tests/e2e_tests/test_grafana_provider.py
  tests/e2e_tests/test_pushing_prometheus_alerts.py
  tests/e2e_tests/test_topology.py
  tests/e2e_tests/utils.py
Labels: Feature, UI, size:XXL

#4017 fix: add retry package and retries for deadlocks and integrity problems
  keep/api/core/db.py
  keep/api/models/db/incident.py
  poetry.lock
  pyproject.toml
Labels: Bug, size:L

#4003 fix: api key errors
  keep/api/models/db/migrations/versions/2025-03-13-14-08_c0e70149c9ec.py
  keep/api/models/db/tenant.py
  keep/api/routes/settings.py
  keep/api/utils/tenant_utils.py
  tests/test_settings_api.py
Labels: Bug, API, size:L

#4022 fix: migrations
  keep/api/models/db/migrations/versions/2025-03-13-14-08_c0e70149c9ec.py
Labels: Bug, size:XS

#4013 fix: Refactor incident processing to use IncidentBl with sessions
  keep/api/bl/incidents_bl.py
  keep/api/core/db.py
  keep/api/tasks/process_incident_task.py
Labels: Incident, size:L

#4020 fix: postgreqsql migration problem
  keep/api/models/db/migrations/versions/2025-03-12-14-46_ca74b4a04371.py
  tests/e2e_tests/test_pushing_prometheus_alerts.py
Labels: Bug, size:L, lgtm

#4026 fix(cloudwatch): http protocol support
  keep/providers/cloudwatch_provider/cloudwatch_provider.py
  pyproject.toml
Labels: Bug, size:S

#4027 fix(pagerduty): update incident
  keep/providers/pagerduty_provider/pagerduty_provider.py
Labels: Bug, Provider, size:M

#4031 fix: e2e run for contributors
  .github/workflows/test-pr-e2e.yml
Labels: size:XS, lgtm

#4029 fix: Last received sort fix
  keep/api/core/alerts.py
  tests/e2e_tests/test_filtering_sort_search_on_alerts.py
Labels: Bug, size:S, lgtm

#4035 feat: allow insecure vm
  keep/providers/victorialogs_provider/victorialogs_provider.py
  keep/providers/victoriametrics_provider/victoriametrics_provider.py
  pyproject.toml
Labels: Feature, Provider, size:L, lgtm

#4039 fix: Support multiple group_by keys in alert formatting
  keep/providers/openobserve_provider/openobserve_provider.py
Labels: size:S

#4034 feat: status as column like source
  keep-ui/app/(keep)/alerts/alert-table-headers.tsx
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/app/(keep)/alerts/alert-table.tsx
  tests/e2e_tests/test_filtering_sort_search_on_alerts.py
  tests/e2e_tests/test_pushing_prometheus_alerts.py
  tests/e2e_tests/utils.py
Labels: Feature, UI, size:L, lgtm

#4041 fix(provider): pagerduty update status and resolution
  keep/providers/pagerduty_provider/pagerduty_provider.py
Labels: Provider, size:S

#3940 feat: grafana incident provider pull, create, update incidents
  docs/providers/documentation/grafana_incident-provider.mdx
  examples/workflows/create-new-incident-grafana-incident.yaml
  examples/workflows/update-incident-grafana-incident.yaml
  keep/providers/grafana_incident_provider/grafana_incident_provider.py
Labels: Feature, Provider, size:XL, lgtm

#3918 fix: Replace `is_confirmed` with `is_candidate` and `is_visible`
  docs/incidents/facets.mdx
  keep-ui/app/(keep)/alerts/alert-associate-incident-modal.tsx
  keep-ui/app/(keep)/alerts/alert-create-incident-ai-modal.tsx
  keep-ui/app/(keep)/alerts/alert-table-facet-value.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alert-action-tray.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
  keep-ui/app/(keep)/incidents/[id]/incident-header.tsx
  keep-ui/app/(keep)/incidents/page.tsx
  keep-ui/components/navbar/IncidentLinks.tsx
  keep-ui/entities/incidents/api/incidents.ts
  keep-ui/entities/incidents/model/models.ts
  keep-ui/features/incident-list/ui/incident-list.tsx
  keep-ui/features/same-incidents-in-the-past/ui/change-same-incident-in-the-past-form.tsx
  keep-ui/features/split-incident-alerts/ui/split-incident-alerts-modal.tsx
  keep-ui/utils/hooks/useIncidents.ts
  keep/api/bl/ai_suggestion_bl.py
  keep/api/bl/incident_reports.py
  keep/api/bl/incidents_bl.py
  keep/api/core/db.py
  keep/api/core/incidents.py
  keep/api/models/db/incident.py
  keep/api/models/db/migrations/versions/2025-03-14-15-52_f3ecc7411f38.py
  keep/api/models/incident.py
  keep/api/routes/incidents.py
  keep/api/routes/metrics.py
  keep/providers/pagerduty_provider/pagerduty_provider.py
  keep/rulesengine/rulesengine.py
  keep/topologies/topology_processor.py
  tests/test_incidents.py
  tests/test_rules_engine.py
  tests/test_workflow_execution.py
Labels: UI, API, size:L

#4044 fix: theme selection
  keep-ui/app/globals.css
  tests/e2e_tests/test_end_to_end.py
  tests/e2e_tests/test_end_to_end_theme.py
  tests/e2e_tests/test_pushing_prometheus_alerts.py
  tests/e2e_tests/utils.py
Labels: Bug, size:L, lgtm

#4046 feat(ui): expand
  keep-ui/app/(keep)/alerts/SettingsSelection.tsx
  keep-ui/app/(keep)/alerts/alert-menu.tsx
  keep-ui/app/(keep)/alerts/alert-preset-manager.tsx
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/app/(keep)/alerts/alert-table.tsx
  keep-ui/app/(keep)/alerts/alerts-table-body.tsx
  keep-ui/entities/alerts/ui/AlertName/AlertName.tsx
  keep-ui/utils/hooks/useExpandedRows.ts
  pyproject.toml
  tests/conftest.py
  tests/e2e_tests/test_end_to_end_theme.py
Labels: Feature, UI, size:L, lgtm

#4048 fix: monaco onprem
  keep-ui/app/(keep)/alerts/ViewAlertModal.tsx
  keep-ui/app/(keep)/mapping/create-or-edit-mapping.tsx
  keep-ui/app/(keep)/settings/webhook-settings.tsx
  keep-ui/features/workflow-execution-results/ui/WorkflowExecutionLogs.tsx
  keep-ui/features/workflows/ai-assistant/ui/StepPreview.tsx
  keep-ui/features/workflows/builder/ui/Editor/StepTest.tsx
  keep-ui/shared/ui/YAMLCodeblock/ui/MonacoYAMLEditor.tsx
  pyproject.toml
Labels: Bug, UI, size:M, lgtm

#4051 feat(elasticsearch): username / password auth
  keep/providers/elastic_provider/elastic_provider.py
Labels: Feature, Provider, size:M, lgtm

#4053 fix: none is not allowed
  keep/api/routes/alerts.py
Labels: Bug, size:XS, lgtm

#4056 feat: Add ability to assign incident severity during creation
  keep-ui/entities/incidents/model/useIncidentActions.tsx
  keep-ui/features/change-incident-severity/index.ts
  keep-ui/features/change-incident-severity/ui/incident-change-severity-select.tsx
  keep-ui/features/change-incident-severity/ui/incident-severity-select.tsx
  keep-ui/features/create-or-update-incident/ui/create-or-update-incident-form.tsx
  keep-ui/tailwind.config.js
  keep/api/core/db.py
  keep/api/models/incident.py
Labels: Feature, UI, size:L, lgtm

#4060 fix: suppress
  keep-ui/app/(keep)/maintenance/create-or-update-maintenance-rule.tsx
  keep-ui/app/(keep)/maintenance/model.ts
Labels: Bug, size:XS

#4063 fix: minor oddities on the incident page
  keep-ui/app/(keep)/incidents/[id]/incident-header.tsx
  keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
Labels: Bug, UI, size:XS

#3988 fix: Improve Incident Report performance
  keep-ui/features/incident-list/ui/incidents-report/pie-chart.tsx
  keep/api/bl/incident_reports.py
Labels: size:L

#4065 feat: multi level mapping and correlation
  keep-ui/app/(keep)/extraction/[rule_id]/executions/page.tsx
  keep-ui/app/(keep)/mapping/[rule_id]/executions/page.tsx
  keep-ui/app/(keep)/mapping/create-or-edit-mapping.tsx
  keep-ui/app/(keep)/mapping/mapping.tsx
  keep-ui/app/(keep)/mapping/models.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationForm.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationSidebarBody.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/RuleFields.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/index.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/types.ts
  keep-ui/app/(keep)/rules/CorrelationTable.tsx
  keep-ui/components/table/ExecutionsTable.tsx
  keep-ui/package-lock.json
  keep-ui/package.json
  keep-ui/shared/api/enrichment-events.ts
  keep-ui/utils/hooks/useEnrichmentEvents.ts
  keep-ui/utils/hooks/useMappingRules.ts
  keep-ui/utils/hooks/useRules.ts
  keep-ui/utils/hooks/useTenantConfiguration.ts
  keep/api/bl/enrichments_bl.py
  keep/api/core/db.py
  keep/api/core/tenant_configuration.py
  keep/api/models/db/mapping.py
  keep/api/models/db/migrations/versions/2025-03-16-11-08_aff0128aa8f1.py
  keep/api/models/db/rule.py
  keep/api/routes/mapping.py
  keep/api/routes/rules.py
  keep/api/routes/settings.py
  keep/rulesengine/rulesengine.py
Labels: Feature, UI, Correlation, size:XL, lgtm

#4070 fix: webhook provider
  keep/providers/webhook_provider/webhook_provider.py
  keep/secretmanager/kubernetessecretmanager.py
  pyproject.toml
Labels: Provider, size:S, lgtm

#4074 fix(ui): drawer instead of dialog
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationSidebarBody.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationSidebarHeader.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/index.tsx
Labels: UI, size:M, lgtm

#4076 fix: add workflows/facets/options query to read-only allowed URLs
  keep-ui/shared/api/ApiClient.ts
Labels: Bug, size:XS, lgtm

#4079 fix: k8s
  keep/secretmanager/kubernetessecretmanager.py
  pyproject.toml
Labels: Bug, size:M, lgtm

#4084 feat: allow elastic provider self signed
  keep/providers/elastic_provider/elastic_provider.py
  pyproject.toml
Labels: Feature, Provider, size:M

#4081 fix: remove outdated 'react-loading'
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-sync-status.tsx
  keep-ui/features/workflows/builder/ui/Editor/StepTest.tsx
  keep-ui/features/workflows/test-run/ui/builder-workflow-testrun-modal-content.tsx
  keep-ui/package-lock.json
  keep-ui/package.json
  keep-ui/widgets/workflow-builder/workflow-builder-widget.tsx
  tests/e2e_tests/test_end_to_end.py
Labels: UI, javascript, size:M, lgtm

#4086 fix: elastic verify
  keep/providers/elastic_provider/elastic_provider.py
  pyproject.toml
Labels: Bug, size:S, lgtm

#3954 fix: better explanation for provider installation with missing scopes
  keep-ui/app/(keep)/providers/provider-form-scopes.tsx
Labels: Provider, UI, size:S

#4098 fix: remove removing of incidents
  keep/api/core/demo_mode.py
Labels: size:M

#4108 fix: migrations fallback & few other things
  keep-ui/app/(keep)/providers/provider-form-scopes.tsx
  keep/api/models/db/migrations/env.py
  keep/api/models/db/migrations/versions/2024-10-22-10-38_8438f041ee0e.py
  keep/api/models/db/migrations/versions/2025-03-12-14-46_ca74b4a04371.py
Labels: Bug, size:XS

#4110 fix: migrations
  keep/api/models/db/migrations/versions/2025-03-16-11-08_aff0128aa8f1.py
Labels: Bug, size:XS

#4072 fix: use expanded
  keep-ui/utils/hooks/useExpandedRows.ts
  pyproject.toml
Labels: Bug, size:XS, lgtm

#4107 feat: switch tenants
  docker/Dockerfile.ui
  ee/identitymanager/identity_managers/auth0/auth0_authverifier.py
  keep-ui/auth.config.ts
  keep-ui/auth.ts
  keep-ui/components/navbar/Menu.tsx
  keep-ui/components/navbar/Navbar.tsx
  keep-ui/components/navbar/Search.tsx
  keep-ui/next.config.js
  keep-ui/types/auth.d.ts
  keep-ui/utils/hooks/usePusher.ts
  keep/identitymanager/identity_managers/noauth/noauth_authverifier.py
  pyproject.toml
  tests/test_auth_new.py
Labels: Feature, UI, size:XL, lgtm

#4105 fix: monaco from npm by default, CDN version in dev mode with turbopack
  keep-ui/app/(keep)/alerts/ViewAlertModal.tsx
  keep-ui/app/(keep)/mapping/create-or-edit-mapping.tsx
  keep-ui/app/(keep)/settings/webhook-settings.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-sync-status.tsx
  keep-ui/entities/workflows/model/types.ts
  keep-ui/entities/workflows/model/workflow-store.ts
  keep-ui/features/workflow-execution-results/ui/WorkflowExecutionLogs.tsx
  keep-ui/features/workflows/ai-assistant/ui/StepPreview.tsx
  keep-ui/features/workflows/builder/ui/Editor/StepTest.tsx
  keep-ui/next.config.js
  keep-ui/package.json
  keep-ui/shared/lib/server/getConfig.ts
  keep-ui/shared/ui/ErrorComponent/ErrorComponent.tsx
  keep-ui/shared/ui/MonacoEditor/MonacoEditorCDN.tsx
  keep-ui/shared/ui/MonacoEditor/MonacoEditorNPM.tsx
  keep-ui/shared/ui/MonacoEditor/index.ts
  keep-ui/shared/ui/MonacoEditor/index.turbopack.ts
  keep-ui/shared/ui/YAMLCodeblock/ui/MonacoYAMLEditor.tsx
  keep-ui/shared/ui/index.ts
  keep-ui/utils/hooks/useConfig.ts
  tests/e2e_tests/test_end_to_end.py
Labels: UI, javascript, size:L, lgtm

#4119 fix: minor regex problem
  keep-ui/auth.ts
  pyproject.toml
Labels: Bug, size:XS, lgtm

#4127 fix: navbar in smaller screens is broken
  keep-ui/components/navbar/Menu.tsx
  keep-ui/components/navbar/Search.tsx
Labels: Bug, UI, size:M, lgtm

#4126 feat: add firing counter
  keep-ui/app/(keep)/alerts/alert-table-column-rename.tsx
  keep-ui/app/(keep)/alerts/alert-table-headers.tsx
  keep-ui/app/(keep)/alerts/alert-table-rename.tsx
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep/api/models/alert.py
  keep/api/tasks/process_event_task.py
  keep/api/utils/enrichment_helpers.py
  keep/parser/parser.py
  tests/test_counting.py
  tests/test_counting_integration.py
Labels: Feature, UI, size:XL, lgtm

#4129 fix: explicit alert creation in workflows
  examples/workflows/create_alert_in_keep.yml
  keep/providers/keep_provider/keep_provider.py
Labels: size:XS, lgtm

#4117 fix: Add batch alert enrichment functionality
  keep-ui/app/(keep)/alerts/alert-dismiss-modal.tsx
  keep/api/core/db.py
  keep/api/models/alert.py
  keep/api/models/db/migrations/versions/2025-03-12-14-46_ca74b4a04371.py
  keep/api/models/db/migrations/versions/2025-03-16-11-08_aff0128aa8f1.py
  keep/api/routes/alerts.py
  keep/providers/grafana_incident_provider/grafana_incident_provider.py
  tests/conftest.py
  tests/test_enrichments.py
Labels: Feature, UI, API, size:L

#4090 feat: add Airflow provider integration and documentation
  README.md
  docs/images/airflow_1.png
  docs/images/airflow_2.png
  docs/mint.json
  docs/providers/documentation/airflow-provider.mdx
  docs/providers/overview.mdx
  keep-ui/app/(keep)/providers/components/providers-categories/providers-categories.tsx
  keep-ui/public/icons/airflow-icon.png
  keep-ui/shared/api/providers.ts
  keep/providers/airflow_provider/__init__.py
  keep/providers/airflow_provider/airflow_provider.py
  keep/providers/base/base_provider.py
Labels: Documentation, Feature, Provider, size:L, lgtm, hacktoberfest-accepted

#4131 fix: readme
  README.md
Labels: Documentation, size:M, lgtm

#4058 fix: incident merging
  keep/api/core/db.py
  keep/api/models/incident.py
  keep/api/routes/incidents.py
Labels: Bug, Incident, size:S, lgtm

#4114 fix: snow topology
  keep/providers/servicenow_provider/.gitignore
  keep/providers/servicenow_provider/servicenow_provider.py
  pyproject.toml
Labels: Provider, size:M

#4133 fix: Set database columns for incident names to TEXT
  keep/api/models/db/incident.py
  keep/api/models/db/migrations/versions/2025-03-20-09-37_c0880e315ebe.py
Labels: size:M, lgtm

#4102 fix: logs not showing for test runs
  .gitignore
  keep-ui/entities/workflows/lib/yaml-utils.ts
  keep-ui/entities/workflows/model/useWorkflowActions.ts
  keep-ui/features/workflow-execution-results/ui/WorkflowExecutionLogs.tsx
  keep-ui/features/workflow-execution-results/ui/WorkflowExecutionResults.tsx
  keep-ui/features/workflows/builder/ui/Editor/StepTest.tsx
  keep-ui/features/workflows/test-run/ui/builder-workflow-testrun-modal-content.tsx
  keep-ui/features/workflows/test-run/ui/workflow-test-run-modal.tsx
  keep-ui/shared/api/workflow-executions.ts
  keep-ui/utils/hooks/useWorkflowExecutions.ts
  keep/api/core/db.py
  keep/api/models/db/migrations/versions/2025-03-18-14-54_971abbbf0a2c.py
  keep/api/models/db/workflow.py
  keep/api/models/workflow.py
  keep/api/routes/workflows.py
  keep/parser/parser.py
  keep/providers/mongodb_provider/mongodb_provider.py
  keep/workflowmanager/workflow.py
  keep/workflowmanager/workflowmanager.py
  keep/workflowmanager/workflowscheduler.py
  tests/test_workflowmanager.py
Labels: Bug, size:XL

#4134 fix: Refactor provider parsing and add workflow metadata tests
  keep/parser/parser.py
  keep/workflowmanager/workflowstore.py
  tests/test_workflowstore.py
Labels: size:L

#4142 fix: incorrect isCandidate prop in IncidentAlerts component
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
Labels: Bug, size:XS, lgtm

#4085 fix: Mitigate sort by last_received impact
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-table-tab-panel-server-side.tsx
  keep-ui/app/(keep)/alerts/alerts.tsx
  keep-ui/components/navbar/AlertsLinks.tsx
  keep-ui/components/navbar/CustomPresetAlertLinks.tsx
  keep-ui/features/filter/facet-panel-server-side.tsx
  keep-ui/features/filter/hooks.tsx
  keep-ui/features/incident-list/ui/incident-list.tsx
  keep-ui/utils/hooks/useAlerts.ts
  keep-ui/utils/hooks/useIncidents.ts
  keep/api/core/alerts.py
  keep/api/core/cel_to_sql/properties_mapper.py
  keep/api/core/cel_to_sql/properties_metadata.py
  keep/api/core/cel_to_sql/sql_providers/base.py
  keep/api/core/facets.py
Labels: Bug, size:XL, lgtm

#4144 fix: flickering provider icons
  keep-ui/app/(keep)/alerts/alert-push-alert-to-server-modal.tsx
  keep-ui/app/(keep)/alerts/alert-table-facet-value.tsx
  keep-ui/app/(keep)/alerts/alert-table-headers.tsx
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/components/ui/DynamicProviderIcon.tsx
  keep-ui/entities/provider-images/model/useProviderImages.ts
  keep-ui/features/incident-list/ui/incident-list.tsx
Labels: Bug, UI, size:L, lgtm

#4147 feat: incident alerts table is compact now
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alert-action-tray.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
  keep-ui/entities/incidents/model/useIncidentActions.tsx
Labels: Feature, UI, size:L, lgtm

#4151 fix: csv preview
  keep-ui/app/(keep)/mapping/[rule_id]/executions/page.tsx
Labels: Bug, size:XS, lgtm

#4149 feat: add formatting for telegram messages
  docs/providers/documentation/telegram-provider.mdx
  examples/workflows/send-message-telegram-with-htmlmd.yaml
  keep/providers/telegram_provider/telegram_provider.py
Labels: Documentation, Feature, Provider, size:M, lgtm

#4145 feat: asana provider
  README.md
  docs/images/asana-provider_1.png
  docs/images/asana-provider_2.png
  docs/images/asana-provider_3.png
  docs/mint.json
  docs/providers/documentation/asana-provider.mdx
  docs/providers/overview.mdx
  examples/workflows/create-task-in-asana.yaml
  examples/workflows/update-task-in-asana.yaml
  keep-ui/public/icons/asana-icon.png
  keep/providers/asana_provider/__init__.py
  keep/providers/asana_provider/asana_provider.py
Labels: Documentation, Feature, Provider, size:L, lgtm, hacktoberfest-accepted

#4156 fix: Add safe_run_worker to handle Redis connection errors
  keep/api/api.py
  keep/api/arq_worker.py
Labels: Bug, API, size:S, lgtm

#4159 fix: Refactor incident resolution logic to handle active statuses.
  keep/api/core/db.py
  keep/api/models/db/incident.py
  keep/api/tasks/process_event_task.py
  tests/test_incidents.py
Labels: Bug, size:L, lgtm

#4153 fix: Handle StaleDataError with retries in database updates.
  keep/api/core/db.py
Labels: Bug, size:M, lgtm

#4161 fix: retry loops by adding break statements after commits
  keep/api/bl/incidents_bl.py
  keep/api/core/db.py
  keep/api/tasks/process_event_task.py
Labels: Bug, size:XS, lgtm

#4163 fix: prevent expire on commit during event processing
  keep/api/bl/incidents_bl.py
  keep/api/tasks/process_event_task.py
  keep/rulesengine/rulesengine.py
Labels: Bug, size:M, lgtm

#4172 fix: use "test" instead of null
  keep/api/core/db.py
  keep/api/models/db/migrations/versions/2025-03-18-14-54_971abbbf0a2c.py
  keep/api/models/db/workflow.py
Labels: Bug, size:L

#4169 fix: Refactor incident ID reference to prevent nested exception
  keep/api/core/db.py
Labels: Bug, size:XS, lgtm

#4062 fix: Add filter/sort e2e for incidents page
  keep-ui/features/filter/add-facet-modal-with-suggestions.tsx
  keep-ui/features/filter/add-facet-modal.tsx
  keep-ui/features/incident-list/ui/incident-table-component.tsx
  tests/e2e_tests/incidents_alerts_setup.py
  tests/e2e_tests/test_filtering_sort_search_on_alerts.py
  tests/e2e_tests/test_filtering_sort_search_on_incidents.py
Labels: size:XL

#4174 fix: dummy workflow for fk integrity
  keep/api/models/db/migrations/versions/2025-03-18-14-54_971abbbf0a2c.py
Labels: size:S
