Repository keephq/keep, pull requests merged in 2025-02, with the labels that each got.

#3254 docs(support): revert support page
  docs/mint.json
  docs/overview/support.mdx
Labels: Documentation, size:S, lgtm

#3067 docs: improvements to incidents and providers
  docs/deployment/configuration.mdx
  docs/deployment/local-llm/keep-with-litellm.mdx
  docs/images/correlation-topology.png
  docs/images/provider-methods-assistant.png
  docs/images/provider-methods-menu.png
  docs/images/provider-methods-modal.png
  docs/mint.json
  docs/overview/correlation-rules.mdx
  docs/overview/correlation-topology.mdx
  docs/overview/servicetopology.mdx
  docs/providers/documentation/datadog-provider.mdx
  docs/providers/overview.mdx
  docs/providers/provider-methods.mdx
  keep/topologies/topology_processor.py
  keep/workflowmanager/workflowmanager.py
  scripts/docs_get_providers_list.py
Labels: Documentation, size:L, lgtm

#3054 feat: add e2e tests
  .github/workflows/test-pr-e2e.yml
  tests/e2e_tests/docker-compose-e2e-mysql.yml
  tests/e2e_tests/docker-compose-e2e-postgres.yml
  tests/e2e_tests/grafana.ini
  tests/e2e_tests/test_end_to_end.py
  tests/e2e_tests/test_grafana_provider.py
  tests/e2e_tests/test_pushing_prometheus_alerts.py
  tests/e2e_tests/utils.py
  tests/e2e_tests/workflow-sample.yaml
Labels: Feature, size:XL, lgtm

#3258 fix(iohandler): handle tuple
  .github/workflows/test-pr.yml
  keep/functions/__init__.py
  keep/iohandler/iohandler.py
  keep/providers/providers_factory.py
  pyproject.toml
  tests/test_iohandler.py
Labels: Bug, size:M, lgtm

#3256 feat(api): better wf logs
  examples/workflows/webhook_example.yml
  keep-ui/features/workflow-execution-results/lib/logs-utils.ts
  keep-ui/features/workflow-execution-results/ui/WorkflowDefinitionYAML.tsx
  keep-ui/features/workflow-execution-results/ui/WorkflowExecutionLogs.tsx
  keep-ui/features/workflow-execution-results/ui/WorkflowExecutionResults.tsx
  keep-ui/shared/ui/YAMLCodeblock/ui/MonacoYAMLEditor.tsx
  keep/api/logging.py
  keep/contextmanager/contextmanager.py
  keep/identitymanager/identitymanager.py
  keep/parser/parser.py
  keep/providers/base/base_provider.py
  keep/providers/console_provider/console_provider.py
  keep/secretmanager/secretmanager.py
  keep/step/step.py
  keep/workflowmanager/workflow.py
  keep/workflowmanager/workflowmanager.py
  tests/test_workflow_execution.py
Labels: Feature, API, size:XL, lgtm

#3263 fix: enable prom metrics for docker-compose
  docker-compose.yml
Labels: size:XS, lgtm

#3268 fix(api): logs
  keep/api/logging.py
Labels: API, size:XS, lgtm

#3270 fix(api): logs
  keep/api/logging.py
Labels: Bug, API, size:XS, lgtm

#3271 fix(api): logs
  keep/api/config.py
Labels: API, size:S

#3272 fix(api): logs
  keep/api/config.py
  keep/api/core/db.py
  keep/api/logging.py
Labels: Bug, size:M, lgtm

#3273 fix(api): logs
  keep/api/core/db.py
Labels: API, size:XS, lgtm

#3274 fix(api): logs
  keep/api/core/db.py
Labels: Bug, size:S, lgtm

#3275 fix(api): logs
  keep/api/core/db.py
Labels: Bug, API, size:S

#3276 fix(api): logs
  keep/api/logging.py
Labels: Bug, API, size:XS, lgtm

#3269 fix: incident list horizontal scroll
  keep-ui/features/filter/facets-panel.tsx
  keep-ui/features/incident-list/ui/incident-list.tsx
  keep-ui/features/incident-list/ui/incident-table-component.tsx
  keep-ui/features/incident-list/ui/incidents-table.tsx
Labels: UI, size:L

#3279 fix(api): LastAlertToIncident force str for fingerprint
  keep/api/core/db.py
Labels: Bug, API, size:XS

#3284 fix: Fix buggy incident facets
  keep-ui/features/filter/facets-panel.tsx
  keep-ui/utils/hooks/useIncidents.ts
Labels: Bug, UI, size:M, lgtm

#3282 fix(ui): time represntation to locale time
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/app/(keep)/alerts/alert-timeline.tsx
  keep/api/bl/enrichments_bl.py
  keep/api/tasks/process_event_task.py
Labels: UI, size:S, lgtm

#3285 fix(api): event_id to fingerprint
  keep/api/bl/ai_suggestion_bl.py
Labels: Bug, API, size:XS

#3290 fix(auth): add callbackUrl parameter for redirect after sign-in
  keep-ui/app/(signin)/signin/SignInForm.tsx
  keep-ui/app/(signin)/signin/page.tsx
  keep-ui/middleware.ts
Labels: size:S

#3302 feat: vllm and clickhouse
  docs/mint.json
  docs/providers/documentation/clickhouse-provider.mdx
  docs/providers/documentation/vllm-provider.mdx
  docs/providers/overview.mdx
  examples/workflows/enrich_using_structured_output_from_vllm_qwen.yaml
  keep-ui/public/icons/vllm-icon.png
  keep/providers/clickhouse_provider/clickhouse_provider.py
  keep/providers/vllm_provider/__init__.py
  keep/providers/vllm_provider/vllm_provider.py
Labels: Documentation, Feature, Provider, size:L

#3304 chore(version): bump
  poetry.lock
Labels: Dependencies, size:XS

#3306 fix: Revert "chore(version): bump"
  poetry.lock
Labels: Dependencies, size:XS

#3308 chore(version): bump
  pyproject.toml
Labels: Dependencies, size:XS

#3298 fix(ui): oauth
  keep-ui/app/(keep)/providers/oauth2/[providerType]/page.tsx
Labels: UI, size:XS, lgtm

#3281 fix: more compact incident list table
  keep-ui/features/incident-list/ui/incidents-table.tsx
Labels: UI, size:XS

#3065 feat(providers): Wazuh Provider
  README.md
  docs/mint.json
  docs/providers/documentation/wazuh-provider.mdx
  docs/providers/overview.mdx
  keep-ui/public/icons/wazuh-icon.png
  keep/providers/wazuh_provider/__init__.py
  keep/providers/wazuh_provider/alerts_mock.py
  keep/providers/wazuh_provider/custom-keep
  keep/providers/wazuh_provider/custom-keep.py
  keep/providers/wazuh_provider/wazuh_provider.py
Labels: Documentation, Feature, Provider, size:L, lgtm

#3295 feat: dash0 provider
  README.md
  docs/images/dash0-provider_1.png
  docs/images/dash0-provider_2.png
  docs/images/dash0-provider_3.png
  docs/images/dash0-provider_4.png
  docs/images/dash0-provider_5.png
  docs/images/dash0-provider_6.png
  docs/images/keep-apikey-1.png
  docs/images/keep-apikey-2.png
  docs/images/keep-apikey-3.png
  docs/images/keep-apikey-4.png
  docs/mint.json
  docs/providers/documentation/dash0-provider.mdx
  docs/providers/overview.mdx
  keep-ui/public/icons/dash0-icon.png
  keep/providers/dash0_provider/__init__.py
  keep/providers/dash0_provider/alerts_mock.py
  keep/providers/dash0_provider/dash0_provider.py
Labels: Documentation, Feature, Provider, 🙋 Bounty claim, size:L, lgtm

#3312 fix(api): rules engine
  keep/rulesengine/rulesengine.py
  pyproject.toml
  tests/test_rules_engine.py
Labels: API, size:L, lgtm

#3313 fix(api): example
  examples/workflows/clickhouse_multiquery.yml
  keep/providers/servicenow_provider/servicenow_provider.py
  tests/test_incidents.py
Labels: API, size:L, lgtm

#3316 fix(api): at_sign
  keep/rulesengine/rulesengine.py
  pyproject.toml
  tests/test_rules_engine.py
Labels: Bug, API, size:S, lgtm

#3319 fix: Update SelectItem values to use more descriptive keys
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationForm.tsx
Labels: UI, size:XS

#3320 chore: 3318 bug rules created via UI has wrong resolve on values
  keep/api/models/db/migrations/versions/2025-02-05-15-46_e343054ae740.py
Labels: Bug, UI, size:M, lgtm

#3323 fix: Filter out deleted and resolved incidents in navbar links.
  keep-ui/components/navbar/IncidentLinks.tsx
  keep/api/models/db/migrations/versions/2025-02-05-15-46_e343054ae740.py
Labels: Bug, UI, size:XS

#3327 fix(api): save button
  keep-ui/shared/ui/YAMLCodeblock/ui/MonacoYAMLEditor.tsx
  pyproject.toml
Labels: API, size:S

#3336 fix(ui): saving workflow doesn't refresh cache
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-detail-page.tsx
  keep-ui/app/(keep)/workflows/workflows.client.tsx
  keep-ui/entities/workflows/model/useWorkflowActions.ts
  keep-ui/features/workflow-execution-results/ui/WorkflowExecutionResults.tsx
  keep-ui/shared/ui/YAMLCodeblock/ui/MonacoYAMLEditor.tsx
  keep-ui/utils/hooks/useWorkflowDetail.ts
  keep-ui/utils/hooks/useWorkflowsV2.ts
  pyproject.toml
Labels: Bug, UI, size:L, lgtm

#3261 feat: netbox provider
  README.md
  docs/images/netbox-provider_1.png
  docs/images/netbox-provider_10.png
  docs/images/netbox-provider_2.png
  docs/images/netbox-provider_3.png
  docs/images/netbox-provider_4.png
  docs/images/netbox-provider_5.png
  docs/images/netbox-provider_6.png
  docs/images/netbox-provider_7.png
  docs/images/netbox-provider_8.png
  docs/images/netbox-provider_9.png
  docs/mint.json
  docs/providers/documentation/netbox-provider.mdx
  docs/providers/overview.mdx
  keep-ui/public/icons/netbox-icon.png
  keep/providers/netbox_provider/README.md
  keep/providers/netbox_provider/__init__.py
  keep/providers/netbox_provider/alerts_mock.py
  keep/providers/netbox_provider/netbox_provider.py
Labels: Documentation, Feature, Provider, 🙋 Bounty claim, size:L, lgtm, hacktoberfest-accepted

#3344 fix: readme broken
  README.md
Labels: Documentation, size:S, lgtm

#3236 feat: Server side filtering for alerts
  keep-ui/app/(keep)/alerts/TitleAndFilters.tsx
  keep-ui/app/(keep)/alerts/[id]/page.tsx
  keep-ui/app/(keep)/alerts/alert-change-status-modal.tsx
  keep-ui/app/(keep)/alerts/alert-dismiss-modal.tsx
  keep-ui/app/(keep)/alerts/alert-menu.tsx
  keep-ui/app/(keep)/alerts/alert-method-modal.tsx
  keep-ui/app/(keep)/alerts/alert-pagination-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-preset-manager.tsx
  keep-ui/app/(keep)/alerts/alert-push-alert-to-server-modal.tsx
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-table-tab-panel-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/app/(keep)/alerts/alerts-rules-builder.tsx
  keep-ui/app/(keep)/alerts/alerts.tsx
  keep-ui/app/(keep)/incidents/page.tsx
  keep-ui/components/LinkWithIcon.tsx
  keep-ui/components/navbar/AlertsLinks.tsx
  keep-ui/components/navbar/CustomPresetAlertLinks.tsx
  keep-ui/components/ui/ShortNumber.tsx
  keep-ui/components/ui/index.ts
  keep-ui/features/create-or-update-preset/ui/alerts-count-badge.tsx
  keep-ui/features/filter/add-facet-modal-with-suggestions.tsx
  keep-ui/features/filter/add-facet-modal.tsx
  keep-ui/features/filter/api.ts
  keep-ui/features/filter/facet-panel-server-side.tsx
  keep-ui/features/filter/facet-value.tsx
  keep-ui/features/filter/facet.tsx
  keep-ui/features/filter/facets-panel.tsx
  keep-ui/features/filter/hooks.tsx
  keep-ui/features/filter/models.tsx
  keep-ui/utils/hooks/useAlerts.ts
  keep/api/api.py
  keep/api/core/alerts.py
  keep/api/core/cel_to_sql/cel_ast_converter.py
  keep/api/core/cel_to_sql/properties_mapper.py
  keep/api/core/cel_to_sql/properties_metadata.py
  keep/api/core/cel_to_sql/sql_providers/base.py
  keep/api/core/cel_to_sql/sql_providers/mysql.py
  keep/api/core/cel_to_sql/sql_providers/postgresql.py
  keep/api/core/cel_to_sql/sql_providers/sqlite.py
  keep/api/core/facets.py
  keep/api/core/incidents.py
  keep/api/models/facet.py
  keep/api/routes/alerts.py
  keep/api/routes/facets.py
  keep/api/routes/incidents.py
  tests/cel_to_sql/cel-to-sql-test-cases.json
  tests/cel_to_sql/test_cel_to_sql.py
Labels: Feature, size:XXL, lgtm

#3346 fix(api): Fix bug when order by was broken on alerts query endpoint
  keep/api/core/alerts.py
Labels: Bug, API, size:XS, lgtm

#3350 chore(coralogix): better handling of fields
  keep/providers/coralogix_provider/coralogix_provider.py
Labels: Provider, size:M, lgtm

#3352 fix(ui): assignee to show on hover
  examples/workflows/opsgenie-create-alert.yml
  keep-ui/components/navbar/UserAvatar.tsx
  keep-ui/entities/users/ui/UserStatefulAvatar.tsx
  keep/providers/coralogix_provider/coralogix_provider.py
  tests/test_workflow_execution.py
Labels: UI, size:M, lgtm

#3361 feat: release 0.36
  pyproject.toml
Labels: size:XS, lgtm

#3354 fix: logging uptime for posthog reporting
  keep/api/core/report_uptime.py
Labels: size:S

#3368 fix(api): strip enrichment fields
  keep/api/bl/enrichments_bl.py
  keep/api/routes/settings.py
  keep/rulesengine/rulesengine.py
Labels: Bug, API, size:S, lgtm

#3364 docs(site24x7): add remark of using correct account uri
  docs/providers/documentation/site24x7-provider.mdx
Labels: Documentation, size:XS, lgtm

#3365 fix: Improve handling of quotes/double-quotes during CEL to SQL translation
  keep/api/core/alerts.py
  keep/api/core/cel_to_sql/sql_providers/base.py
  keep/api/core/cel_to_sql/sql_providers/get_cel_to_sql_provider_for_dialect.py
  keep/api/core/cel_to_sql/sql_providers/mysql.py
  keep/api/core/cel_to_sql/sql_providers/postgresql.py
  keep/api/core/cel_to_sql/sql_providers/sqlite.py
  keep/api/core/facets.py
  keep/api/core/incidents.py
  tests/cel_to_sql/cel-to-sql-test-cases.json
  tests/cel_to_sql/test_cel_to_sql.py
Labels: Bug, size:L, lgtm

#3374 fix(api): linked provider slowliness
  keep/api/core/db.py
  keep/api/models/db/alert.py
Labels: Bug, API, size:S, lgtm

#3380 fix(api): site24x7
  keep/providers/site24x7_provider/site24x7_provider.py
  pyproject.toml
Labels: Bug, API, size:S, lgtm

#3381 chore: loosen validation on host url of grafana-incident
  keep/providers/grafana_incident_provider/grafana_incident_provider.py
Labels: Provider, size:XS, lgtm

#3383 chore: workflow full sync
  .github/workflows/auto-resolve-keep.yml
  examples/workflows/update_workflows_from_s3.yml
  keep/cli/cli.py
  keep/providers/keep_provider/keep_provider.py
Labels: CLI, size:M

#3390 fix: Adding not existing in Incident table facet causes app to crash
  keep-ui/features/filter/facets-panel.tsx
  keep-ui/features/incident-list/ui/incident-list.tsx
  keep/api/core/cel_to_sql/properties_metadata.py
  keep/api/core/facets.py
Labels: Bug, size:M, lgtm

#3394 fix(ui): incident status change is cut
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/app/(keep)/incidents/[id]/incident-tabs-navigation.tsx
  keep-ui/shared/ui/TabLinkNavigation/TabLinkNavigation.tsx
  pyproject.toml
Labels: Bug, UI, size:S

#3396 fix: sidebar menu clicks to close sidebar
  keep-ui/app/(keep)/alerts/alert-menu.tsx
  keep-ui/app/(keep)/alerts/alert-sidebar.tsx
  keep/providers/coralogix_provider/coralogix_provider.py
Labels: Bug, UI, size:M, lgtm

#3397 feat: keep function for dropping dictionary keys by prefix
  keep/functions/__init__.py
  pyproject.toml
  tests/test_functions.py
Labels: Feature, size:M, lgtm

#3391 fix: timeouts for workflows
  keep/api/core/db.py
  keep/providers/clickhouse_provider/clickhouse_provider.py
  keep/workflowmanager/workflowscheduler.py
Labels: Bug, size:L

#3407 chore: update github actions cache to latest version
  .github/workflows/test-docs.yml
  .github/workflows/test-pr-e2e.yml
  .github/workflows/test-pr.yml
  keep/api/models/workflow.py
Labels: size:S

#3410 fix(api): last alert hash
  keep/api/core/db.py
  pyproject.toml
Labels: API, size:XS, lgtm

#3409 fix(ui): source maps disabled in production
  keep-ui/next.config.js
Labels: UI, size:S

#3386 feat: Add E2E tests for alerts page - filter/search/sort
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/features/filter/facet-value.tsx
  keep-ui/features/filter/facet.tsx
  keep-ui/features/filter/facets-panel.tsx
  keep/api/core/cel_to_sql/properties_mapper.py
  keep/api/core/cel_to_sql/sql_providers/base.py
  keep/api/core/cel_to_sql/sql_providers/postgresql.py
  keep/api/core/cel_to_sql/sql_providers/sqlite.py
  tests/cel_to_sql/cel-to-sql-test-cases.json
  tests/e2e_tests/test_filtering_sort_search_on_alerts.py
Labels: Bug, Feature, size:XL, lgtm

#3415 fix: facet options in Keep readonly mode
  keep-ui/shared/api/ApiClient.ts
Labels: Bug, size:XS, lgtm

#3408 fix(ui): version overlapping with content
  keep-ui/app/(health)/layout.tsx
Labels: UI, 🙋 Bounty claim, size:S, lgtm

#3398 feat(api): adjustable names
  .github/workflows/test-pr-integrations.yml
  .github/workflows/test-pr-ut.yml
  docs/overview/correlation-rules.mdx
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationForm.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationSidebarBody.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/index.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/types.ts
  keep-ui/app/(keep)/rules/CorrelationTable.tsx
  keep-ui/app/(keep)/rules/FormattedQueryCell.tsx
  keep-ui/utils/hooks/useRules.ts
  keep/api/core/alerts.py
  keep/api/core/cel_to_sql/properties_mapper.py
  keep/api/core/cel_to_sql/sql_providers/base.py
  keep/api/core/cel_to_sql/sql_providers/mysql.py
  keep/api/core/cel_to_sql/sql_providers/postgresql.py
  keep/api/core/cel_to_sql/sql_providers/sqlite.py
  keep/api/core/db.py
  keep/api/models/db/rule.py
  keep/api/routes/rules.py
  keep/iohandler/iohandler.py
  keep/rulesengine/rulesengine.py
  keep/searchengine/searchengine.py
  pyproject.toml
  tests/cel_to_sql/cel-to-sql-test-cases.json
  tests/conftest.py
  tests/test_alert_evaluation.py
  tests/test_rules_engine.py
Labels: Feature, UI, size:XXL, lgtm

#3412 feat: new mapping experience
  docs/overview/enrichment/mapping.mdx
  keep-ui/app/(keep)/mapping/[rule_id]/executions/[execution_id]/page.tsx
  keep-ui/app/(keep)/mapping/[rule_id]/executions/page.tsx
  keep-ui/app/(keep)/mapping/[rule_id]/mapping-execution-table.tsx
  keep-ui/app/(keep)/mapping/create-or-edit-mapping.tsx
  keep-ui/app/(keep)/mapping/mapping.tsx
  keep-ui/app/(keep)/mapping/models.tsx
  keep-ui/app/(keep)/mapping/rules-table.tsx
  keep-ui/app/(keep)/mapping/run-mapping-modal.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-execution-table.tsx
  keep-ui/components/LogViewer.tsx
  keep-ui/components/ui/CreateableSearchSelect.tsx
  keep-ui/shared/api/enrichment-events.ts
  keep-ui/types/react-table.d.ts
  keep-ui/utils/hooks/useEnrichmentEvents.ts
  keep/api/bl/enrichments_bl.py
  keep/api/core/db.py
  keep/api/models/db/enrichment_event.py
  keep/api/models/db/mapping.py
  keep/api/models/db/migrations/versions/2024-07-11-17-10_54c1252b2c8a.py
  keep/api/models/db/migrations/versions/2025-02-11-12-59_21d314490e6a.py
  keep/api/routes/mapping.py
  keep/api/utils/pagination.py
  keep/functions/__init__.py
  tests/test_enrichments.py
  tests/test_incidents.py
  tests/test_search_alerts.py
  tests/test_workflow_execution.py
Labels: Feature, UI, size:XXL

#3426 fix: revision
  keep/api/models/db/migrations/versions/2025-02-13-09-54_cfe08cc46950.py
  pyproject.toml
Labels: size:M, lgtm

#3363 fix: Refactor banners and health page logic.
  keep-ui/app/(health)/health/check.tsx
  keep-ui/app/(health)/health/opengraph-image.png
  keep-ui/app/(health)/health/page.tsx
  keep-ui/app/(health)/layout.tsx
  keep-ui/app/(keep)/layout.tsx
  keep-ui/components/banners/BannerBase.tsx
  keep-ui/components/banners/health-page-banner.tsx
  keep-ui/components/banners/read-only-banner.tsx
Labels: UI, size:L, lgtm

#3419 feat: enrich incident
  examples/workflows/incident-enrich.yaml
  keep-ui/app/(keep)/alerts/ViewAlertModal.tsx
  keep-ui/app/(keep)/alerts/alert-run-workflow-modal.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alert-action-tray.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
  keep-ui/app/(keep)/incidents/[id]/chat/incident-chat.css
  keep-ui/app/(keep)/incidents/[id]/incident-header.tsx
  keep-ui/app/(keep)/incidents/[id]/incident-layout-client.tsx
  keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
  keep-ui/app/(keep)/workflows/manual-run-workflow-modal.tsx
  keep-ui/components/ui/ResizableColumns.tsx
  keep-ui/shared/ui/YAMLCodeblock/ui/MonacoYAMLEditor.tsx
  keep/api/bl/incidents_bl.py
  keep/api/core/db.py
  keep/api/models/db/enrichment_event.py
  keep/api/routes/workflows.py
  keep/functions/__init__.py
  keep/providers/base/base_provider.py
  keep/workflowmanager/workflowscheduler.py
  pyproject.toml
  tailwind.config.js
  tests/test_functions.py
Labels: UI, size:XL, lgtm

#3431 fix: logs
  keep/api/tasks/process_event_task.py
Labels: Bug, size:S, lgtm

#3433 fix: remove animation
  tailwind.config.js
Labels: size:S, lgtm

#3435 fix: sentry remove source maps after upload
  keep-ui/next.config.js
Labels: size:XS, lgtm

#3437 fix: logs wip
  keep/api/tasks/process_event_task.py
Labels: Bug, size:S, lgtm

#3442 fix: fix
  keep/api/tasks/process_event_task.py
Labels: Bug, size:XS, lgtm

#3440 fix(ui): version overlapping with content
  keep-ui/app/(health)/layout.tsx
  keep-ui/app/(keep)/layout.tsx
Labels: UI, size:M, lgtm

#3454 fix: clean workflow
  keep/providers/keep_provider/keep_provider.py
  pyproject.toml
Labels: size:S

#3461 fix: add headers on server side requests
  keep-ui/shared/api/ApiClient.ts
  keep-ui/shared/api/server/createServerApiClient.ts
  pyproject.toml
Labels: Bug, size:M, lgtm

#3465 fix: dynatrace webhook
  keep/providers/dynatrace_provider/dynatrace_provider.py
  pyproject.toml
Labels: Bug, Provider, size:XS, lgtm

#3459 feat: grafana loki provider
  README.md
  docs/mint.json
  docs/providers/documentation/grafana_loki-provider.mdx
  docs/providers/overview.mdx
  examples/workflows/query_grafana_loki.yaml
  keep-ui/public/icons/grafana_loki-icon.png
  keep/providers/grafana_loki_provider/README.md
  keep/providers/grafana_loki_provider/__init__.py
  keep/providers/grafana_loki_provider/grafana_loki_provider.py
Labels: Documentation, Feature, Provider, size:L, lgtm

#3468 fix: unix timestamp
  keep/api/models/alert.py
  tests/test_alert_dto.py
Labels: Bug, size:L, lgtm

#3469 fix: 401 error east-west from frontend to backend
  keep-ui/shared/api/server/createServerApiClient.ts
  oauth2proxy/docker-compose-oauth2proxy.yml
  oauth2proxy/nginx.conf
  pyproject.toml
Labels: Bug, size:L, lgtm

#3472 fix: Restrict incident creation to firing alerts only
  keep/rulesengine/rulesengine.py
  tests/test_rules_engine.py
Labels: Bug, size:L, lgtm

#3475 fix: JSON loading in migration script
  keep/api/models/db/migrations/versions/2025-02-11-12-59_21d314490e6a.py
Labels: Bug, size:XS, lgtm

#3471 docs: oauth2 proxy
  docs/deployment/authentication/oauth2proxy-auth.mdx
Labels: Documentation, size:XS, lgtm

#3480 fix: checkly docs
  docs/providers/documentation/checkly-provider.mdx
Labels: Documentation, size:S, lgtm

#3474 feat: Add support for linking new incidents to past resolved incidents
  keep/api/core/db.py
  keep/rulesengine/rulesengine.py
  tests/test_rules_engine.py
Labels: Feature, size:L, lgtm

#3482 feat: add logs
  keep/identitymanager/authverifierbase.py
Labels: Feature, size:XS, lgtm

#3478 feat: added webhook integration for axiom
  docs/images/axiom-provider-1.png
  docs/images/axiom-provider-2.png
  docs/images/axiom-provider-3.png
  docs/images/axiom-provider-4.png
  docs/images/axiom-provider-5.png
  docs/images/axiom-provider-6.png
  docs/images/axiom-provider-7.png
  docs/providers/documentation/axiom-provider.mdx
  keep/providers/axiom_provider/alerts_mock.py
  keep/providers/axiom_provider/axiom_provider.py
Labels: Documentation, Feature, Provider, size:L, lgtm

#3488 fix: Add pulling availability support for providers
  keep-ui/app/(keep)/providers/provider-form.tsx
  keep-ui/app/(keep)/providers/providers.tsx
  keep/api/models/provider.py
  keep/providers/providers_factory.py
Labels: Provider, UI, size:M, lgtm

#3492 fix: Refactor `_get_or_create_incident` to return tuple of incident and creation flag
  keep/rulesengine/rulesengine.py
Labels: size:S

#3494 feat: extraction executions
  keep-ui/app/(keep)/extraction/[rule_id]/executions/[execution_id]/page.tsx
  keep-ui/app/(keep)/extraction/[rule_id]/executions/page.tsx
  keep-ui/app/(keep)/extraction/extraction-action-tray.tsx
  keep-ui/app/(keep)/extraction/extractions-table.tsx
  keep-ui/app/(keep)/extraction/run-extraction-modal.tsx
  keep-ui/utils/hooks/useEnrichmentEvents.ts
  keep/api/bl/enrichments_bl.py
  keep/api/core/db.py
  keep/api/models/db/alert.py
  keep/api/routes/extraction.py
Labels: Feature, UI, size:XL

#3500 fix: logs enrichment
  examples/workflows/mustache-paths-example.yml
  keep-ui/features/workflow-execution-results/ui/WorkflowExecutionLogs.tsx
  keep/api/bl/enrichments_bl.py
  keep/providers/python_provider/python_provider.py
Labels: size:L, lgtm

#3477 fix: Wrap alert descriptions properly in the sidebar.
  keep-ui/app/(keep)/alerts/alert-sidebar.tsx
Labels: UI, size:XS

#3476 fix: Add whitespace handling to Markdown rendering in incidents
  keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
Labels: Bug, UI, size:XS, lgtm

#3506 fix: revert tz
  keep/api/models/alert.py
  tests/test_alert_dto.py
Labels: size:XS

#3326 feat: manual topology manipulation
  keep-ui/app/(keep)/topology/model/models.ts
  keep-ui/app/(keep)/topology/model/useTopologyApplications.ts
  keep-ui/app/(keep)/topology/topology-client.tsx
  keep-ui/app/(keep)/topology/ui/map/AddEditNodeSidePanel.tsx
  keep-ui/app/(keep)/topology/ui/map/getNodesAndEdgesFromTopologyData.ts
  keep-ui/app/(keep)/topology/ui/map/manage-selection.tsx
  keep-ui/app/(keep)/topology/ui/map/service-node.tsx
  keep-ui/app/(keep)/topology/ui/map/topology-map.tsx
  keep-ui/components/SidePanel.tsx
  keep/api/models/db/migrations/versions/2025-01-26-15-25_8176d7153747.py
  keep/api/models/db/topology.py
  keep/api/routes/topology.py
  keep/topologies/topologies_service.py
  tests/e2e_tests/test_topology.py
  tests/test_enrichments.py
Labels: Feature, UI, size:XXL, lgtm

#3511 fix: 500 on incident status change
  keep/api/core/db.py
  keep/api/routes/incidents.py
Labels: Bug, size:S

#3509 fix: Refactor incident resolution to remove rule dependency
  keep/rulesengine/rulesengine.py
Labels: size:S, lgtm

#3505 fix: Add optional 'predicted' filter support in useIncidents hook
  keep-ui/app/(keep)/alerts/alert-associate-incident-modal.tsx
  keep-ui/app/(keep)/alerts/alert-create-incident-ai-modal.tsx
  keep-ui/app/(keep)/alerts/alert-table-facet-value.tsx
  keep-ui/components/navbar/IncidentLinks.tsx
  keep-ui/features/incident-list/ui/incident-list.tsx
  keep-ui/features/same-incidents-in-the-past/ui/change-same-incident-in-the-past-form.tsx
  keep-ui/features/split-incident-alerts/ui/split-incident-alerts-modal.tsx
  keep-ui/utils/hooks/useIncidents.ts
  keep/api/routes/incidents.py
Labels: UI, API, size:S, lgtm

#3523 fix: allow up to 3 lines in alert description
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
Labels: Bug, UI, size:XS, lgtm

#3528 fix: alert description line clamp in incident/alerts
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
Labels: Bug, size:S

#3532 fix: checkmk
  keep/providers/checkmk_provider/checkmk_provider.py
Labels: Bug, size:XS

#3539 fix: Refactor ViewAlertModal to remove monaco-editor dependency
  keep-ui/app/(keep)/alerts/ViewAlertModal.tsx
Labels: Dependencies, size:S, lgtm

#3542 feat(api): release 0.37.0
  pyproject.toml
Labels: size:XS, lgtm

#3485 feat: Add styles to make Markdown work
  keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
Labels: Feature, UI, 🙋 Bounty claim, size:XS

#3563 feat: execute workflow from slack
  examples/workflows/execute-workflow-example.yml
  keep/api/routes/workflows.py
Labels: Feature, size:M, lgtm

#3564 feat: better grafana provider
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/entities/alerts/model/models.tsx
  keep-ui/entities/alerts/ui/AlertImage/AlertImage.tsx
  keep-ui/entities/alerts/ui/index.ts
  keep/api/models/alert.py
  keep/providers/grafana_provider/docker-compose.yml
  keep/providers/grafana_provider/grafana/grafana.ini
  keep/providers/grafana_provider/grafana/provisioning/alerting/alerts.yml
  keep/providers/grafana_provider/grafana/provisioning/alerting/contact_points.yml
  keep/providers/grafana_provider/grafana/provisioning/alerting/notification_policies.yml
  keep/providers/grafana_provider/grafana_provider.py
Labels: Feature, Provider, size:L, lgtm

#3559 fix: Refactor dismissed enrichments to handle SUPPRESSED status
  keep/api/models/alert.py
  keep/api/models/db/migrations/versions/2025-02-18-18-09_876a424d8f06.py
  keep/api/routes/alerts.py
Labels: size:M, lgtm

#3558 feat: databend provider
  README.md
  docs/mint.json
  docs/providers/documentation/databend-provider.mdx
  docs/providers/overview.mdx
  examples/workflows/query-databend.yml
  keep-ui/public/icons/databend-icon.png
  keep/providers/databend_provider/README.md
  keep/providers/databend_provider/__init__.py
  keep/providers/databend_provider/databend_provider.py
Labels: Documentation, Feature, Provider, size:L, lgtm

#3510 feat(ui): better columns headers
  .gitignore
  keep-ui/app/(keep)/alerts/ViewAlertModal.tsx
  keep-ui/app/(keep)/alerts/alert-grouped-row.tsx
  keep-ui/app/(keep)/alerts/alert-preset-manager.tsx
  keep-ui/app/(keep)/alerts/alert-table-headers.tsx
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/app/(keep)/alerts/alerts-table-body.tsx
  keep-ui/entities/presets/model/types.ts
  keep-ui/features/create-or-update-preset/ui/create-or-update-preset-form.tsx
  keep-ui/shared/ui/DropdownMenu/DropdownMenu.tsx
  pyproject.toml
Labels: Feature, UI, size:XL

#3568 feat: small grafana improvement
  keep/providers/grafana_provider/grafana_provider.py
Labels: Enhancement, size:S

#3567 fix: facet with one option doesn't let you uncheck it
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/app/(keep)/alerts/alerts-table-body.tsx
  keep-ui/components/ui/EmptyStateCard.tsx
  keep-ui/features/filter/facet-panel-server-side.tsx
  keep-ui/features/filter/facet-value.tsx
  keep-ui/features/filter/facet.tsx
  keep-ui/features/filter/facets-panel.tsx
  keep-ui/features/filter/models.tsx
  keep-ui/features/incident-list/ui/incident-list.tsx
  keep/api/core/alerts.py
  keep/api/core/facets.py
Labels: Bug, UI, size:XL, lgtm

#3446 feat: migration for wf executions
  keep/api/models/db/migrations/versions/2025-02-13-17-27_90e2d22edc6a.py
  keep/workflowmanager/workflowscheduler.py
Labels: Feature, size:M, lgtm

#3573 fix: double-headed-migration
  keep/api/models/db/migrations/versions/2025-02-19-15-32_35ebba262eb0.py
Labels: size:S

#3571 feat: datadog snapshot
  keep/providers/datadog_provider/datadog_provider.py
Labels: Feature, Provider, size:M

#3578 fix: context, overriding variables, add: step-preview yaml and types
  keep-ui/components/ui/DynamicProviderIcon.tsx
  keep-ui/entities/workflows/lib/parser.ts
  keep-ui/entities/workflows/model/legacy-workflow.types.ts
  keep-ui/entities/workflows/model/types.ts
  keep-ui/entities/workflows/model/workflow-store.ts
  keep-ui/entities/workflows/model/yaml.types.ts
  keep-ui/features/workflows/builder/ui/BuilderChat/StepPreview.tsx
  keep-ui/features/workflows/builder/ui/BuilderChat/builder-chat.tsx
  keep-ui/features/workflows/builder/ui/Editor/StepEditor.tsx
  keep-ui/features/workflows/builder/ui/Editor/StepTest.tsx
  keep-ui/features/workflows/builder/ui/WorkflowNode.tsx
  keep-ui/features/workflows/builder/ui/WorkflowToolbox.tsx
  keep-ui/shared/ui/ResizableColumns/ui/ResizableColumns.tsx
  keep-ui/widgets/workflow-builder/builder.tsx
Labels: Bug, size:XL, lgtm

#3581 fix: migration
  keep/api/models/db/migrations/versions/2025-02-13-17-27_90e2d22edc6a.py
Labels: size:XS

#3585 fix: remove old incidents
  scripts/simulate_alerts.py
Labels: size:S

#3584 feat: better sign in error page
  keep-ui/app/(signin)/error/authEnvUtils.tsx
  keep-ui/app/(signin)/error/error-client.tsx
  keep-ui/app/(signin)/error/page.tsx
  keep-ui/auth.config.ts
  keep-ui/auth.ts
  keep-ui/entrypoint.sh
  keep-ui/middleware.ts
  proxy/docker-compose-proxy.yml
  pyproject.toml
Labels: Feature, UI, size:L

#3588 fix: entrypoint
  keep-ui/entrypoint.sh
  pyproject.toml
Labels: Bug, size:M, lgtm

#3589 fix(ui): entry
  keep-ui/entrypoint.sh
  pyproject.toml
Labels: UI, size:XS

#3576 chore: several improvements based on feedback
  keep-ui/app/(keep)/alerts/alert-associate-incident-modal.tsx
  keep-ui/app/(keep)/alerts/alert-grouped-row.tsx
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/app/(keep)/alerts/alert-table.tsx
  keep-ui/app/(keep)/alerts/alerts-table-body.tsx
  keep-ui/app/(keep)/incidents/[id]/activity/incident-activity.tsx
  keep-ui/app/(keep)/incidents/[id]/activity/ui/IncidentActivityComment.tsx
  keep-ui/app/(keep)/incidents/[id]/activity/ui/IncidentActivityItem.tsx
  keep-ui/app/(keep)/incidents/[id]/timeline/incident-timeline.tsx
  keep-ui/app/(keep)/workflows/manual-run-workflow-modal.tsx
  keep-ui/entities/incidents/lib/utils.ts
  keep-ui/entities/incidents/model/useIncidentActions.tsx
  keep/api/models/db/alert.py
  keep/api/routes/alerts.py
  keep/api/routes/incidents.py
Labels: UI, Feedback, size:L, lgtm

#3593 fix: wf step test
  keep-ui/features/workflows/builder/ui/BuilderChat/builder-chat.tsx
  keep-ui/features/workflows/builder/ui/Editor/StepEditor.tsx
  keep-ui/features/workflows/builder/ui/Editor/StepTest.tsx
  keep-ui/widgets/workflow-builder/builder.tsx
Labels: Bug, size:M, lgtm

#3600 feat: Make filter empty state reachable when nothing is selected in Facet
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/app/(keep)/alerts/alerts-table-body.tsx
  keep-ui/features/filter/facet.tsx
  keep-ui/features/filter/facets-panel.tsx
  keep-ui/features/filter/models.tsx
Labels: Feature, UI, size:M

#3606 fix: better triggers in workflow ai
  keep-ui/components/ui/DynamicProviderIcon.tsx
  keep-ui/entities/workflows/lib/getHumanReadableInterval.ts
  keep-ui/entities/workflows/lib/getLayoutedWorkflowElements.ts
  keep-ui/entities/workflows/lib/getTriggerDescription.ts
  keep-ui/entities/workflows/model/types.ts
  keep-ui/entities/workflows/model/workflow-store.ts
  keep-ui/entities/workflows/ui/NodeTriggerIcon.tsx
  keep-ui/entities/workflows/ui/WorkflowTriggerBadge.tsx
  keep-ui/features/workflows/builder/ui/BuilderChat/AddStepUI.tsx
  keep-ui/features/workflows/builder/ui/BuilderChat/AddTriggerUI.tsx
  keep-ui/features/workflows/builder/ui/BuilderChat/StepPreview.tsx
  keep-ui/features/workflows/builder/ui/BuilderChat/builder-chat.tsx
  keep-ui/features/workflows/builder/ui/Editor/StepTest.tsx
  keep-ui/features/workflows/builder/ui/Editor/TriggerEditor.tsx
  keep-ui/features/workflows/builder/ui/WorkflowNode.tsx
Labels: Bug, UI, AI, size:L

#3608 fix: wf ai triggers
  keep-ui/entities/workflows/lib/getTriggerDescription.ts
Labels: Bug, UI, AI, size:M

#3612 fix: version
  pyproject.toml
Labels: size:XS

#3617 fix: typo in alertseverityandstatus.mdx
  docs/overview/alertseverityandstatus.mdx
Labels: Documentation, size:XS, lgtm

#3630 feat(rbac): workflowrunner role
  examples/workflows/execute-workflow-example.yml
  keep/api/routes/workflows.py
  keep/identitymanager/rbac.py
Labels: Feature, size:S

#3627 feat: Facet for linked or unlinked past incidents
  docs/incidents/facets.mdx
  keep-ui/features/incident-list/ui/incident-list.tsx
  keep/api/core/incidents.py
Labels: Feature, UI, Incident, size:M

#3628 feat(providers): zoom provider
  README.md
  docs/images/zoom1.png
  docs/images/zoom2.png
  docs/images/zoom3.png
  docs/images/zoom4.png
  docs/images/zoom5.png
  docs/images/zoom6.png
  docs/mint.json
  docs/providers/documentation/zoom-provider.mdx
  docs/providers/overview.mdx
  examples/workflows/zoom_example.yml
  keep-ui/public/icons/zoom-icon.png
  keep/providers/zoom_provider/__init__.py
  keep/providers/zoom_provider/zoom_provider.py
Labels: Documentation, Feature, Provider, size:L, lgtm

#3631 fix: Fix broken facet "Linked incident" in mysql and postgresql
  keep-ui/features/filter/facets-panel.tsx
  keep-ui/features/incident-list/ui/incident-list.tsx
  keep/api/core/incidents.py
Labels: Bug, size:M

#3633 fix: boto3 auth
  keep/providers/amazonsqs_provider/amazonsqs_provider.py
  keep/providers/cloudwatch_provider/cloudwatch_provider.py
  keep/providers/eks_provider/eks_provider.py
  keep/providers/incidentmanager_provider/incidentmanager_provider.py
  keep/providers/s3_provider/s3_provider.py
Labels: size:L

#3636 feat: incident assign to me
  keep-ui/app/(keep)/incidents/[id]/incident-header.tsx
  keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
  keep-ui/entities/incidents/model/useIncidentActions.tsx
  keep/api/routes/incidents.py
Labels: Feature, size:M, lgtm

#3635 feat: youtrack provider
  README.md
  docs/mint.json
  docs/providers/documentation/youtrack-provider.mdx
  docs/providers/overview.mdx
  examples/workflows/create-issue-youtrack.yaml
  keep-ui/public/icons/youtrack-icon.png
  keep/providers/youtrack_provider/README.md
  keep/providers/youtrack_provider/__init__.py
  keep/providers/youtrack_provider/youtrack_provider.py
Labels: Documentation, Feature, Provider, size:L, lgtm

#3643 feat: Add date range filter to incident list
  keep-ui/features/incident-list/ui/incident-list.tsx
  keep-ui/features/incident-list/ui/incidents-table.tsx
Labels: Feature, UI, size:M

#3648 fix: assign to me in incident overview
  keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
Labels: Bug, size:S

#3651 fix: don't allow adding condition in condition or loop in the loop
  keep-ui/entities/workflows/lib/getLayoutedWorkflowElements.ts
  keep-ui/entities/workflows/lib/parser.ts
  keep-ui/entities/workflows/model/__tests__/types.test.ts
  keep-ui/entities/workflows/model/__tests__/workflow-store.test.tsx
  keep-ui/entities/workflows/model/types.ts
  keep-ui/entities/workflows/model/useWorkflowActions.ts
  keep-ui/entities/workflows/model/workflow-store.ts
  keep-ui/entities/workflows/model/yaml.types.ts
  keep-ui/entities/workflows/ui/NodeTriggerIcon.tsx
  keep-ui/features/workflows/ai-assistant/lib/utils.ts
  keep-ui/features/workflows/builder/lib/utils.tsx
  keep-ui/features/workflows/builder/ui/Editor/ReactFlowEditor.tsx
  keep-ui/features/workflows/builder/ui/Editor/StepEditor.tsx
  keep-ui/features/workflows/builder/ui/Editor/TriggerEditor.tsx
  keep-ui/features/workflows/builder/ui/WorkflowEdge.tsx
  keep-ui/features/workflows/builder/ui/WorkflowNode.tsx
  keep-ui/features/workflows/builder/ui/WorkflowToolbox.tsx
  keep-ui/features/workflows/test-run/ui/workflow-test-run-modal.tsx
  keep-ui/utils/reactFlow.ts
  keep-ui/widgets/workflow-builder/workflow-builder.tsx
Labels: Bug, UI, size:XXL

#3657 fix(ui): viewed eye alignment
  keep-ui/app/(keep)/alerts/alert-grouped-row.tsx
Labels: UI, size:XS

#3659 feat(api): support azuread token v2
  ee/identitymanager/identity_managers/azuread/azuread_authverifier.py
  pyproject.toml
Labels: Feature, size:M, lgtm

#3660 feat(api): azurev2
  ee/identitymanager/identity_managers/azuread/azuread_authverifier.py
  pyproject.toml
Labels: API, size:S

#3661 fix: azure
  ee/identitymanager/identity_managers/azuread/azuread_authverifier.py
  pyproject.toml
Labels: Bug, size:S, lgtm

#3667 feat: time select for incidents page
  keep-ui/features/incident-list/ui/incident-list.tsx
  keep-ui/utils/hooks/useIncidents.ts
Labels: Feature, UI, size:M, lgtm

#3665 fix: Use inner join for incident instead of outerjoin and fix "source" facet
  keep/api/core/facets.py
  keep/api/core/incidents.py
Labels: Bug, size:S

#3669 fix: Make `description` and `repository` not-nullable.
  keep/api/models/db/migrations/versions/2025-02-25-14-20_a82154690f35.py
  keep/api/models/db/topology.py
Labels: size:M

#3672 feat: bug to board
  .github/workflows/but-to-project.yml
Labels: Feature, size:S

#3687 fix: providerInfo could be None
  keep/api/routes/providers.py
Labels: Bug, size:XS

#3689 fix: internal workflow for auto resolve
  .github/workflows/auto-resolve-keep.yml
Labels: Internal, size:XS

#3690 fix: pull request to push
  .github/workflows/auto-resolve-keep.yml
Labels: size:S

#3652 feat: workflow provisioning from the env
  docs/deployment/provision/overview.mdx
  keep/api/config.py
  keep/workflowmanager/workflowstore.py
Labels: Documentation, Feature, size:L

#3696 feat: add documentation for manual topology and import/export feature
  docs/images/topology/topology_add_connection.png
  docs/images/topology/topology_add_node.png
  docs/images/topology/topology_add_protocol.png
  docs/images/topology/topology_delete_dependency.png
  docs/images/topology/topology_delete_services.png
  docs/images/topology/topology_edit_dependency.png
  docs/images/topology/topology_import_export.png
  docs/images/topology/topology_new_node.png
  docs/images/topology/topology_protocol_added.png
  docs/images/topology/topology_sidebar_add.png
  docs/images/topology/topology_update_service.png
  docs/overview/servicetopology.mdx
Labels: Documentation, size:L, lgtm

#3703 fix: rely on db when refer to provider secret
  keep/providers/providers_factory.py
  pyproject.toml
Labels: Provider, size:S, lgtm
