Repository keephq/keep, pull requests merged in 2025-09, with the labels that each got.

#5314 feat(provider): add reconcile functionality to fluxcd provider
  docs/snippets/providers/fluxcd-snippet-autogenerated.mdx
  keep/providers/fluxcd_provider/fluxcd_provider.py
Labels: Documentation, Feature, Provider, size:M, lgtm

#5323 fix: added a new pkce string generator and use that in oauth handshake
  keep-ui/app/(keep)/providers/provider-form.tsx
  keep-ui/shared/lib/encodings.ts
Labels: Feature, size:M, lgtm

#5320 fix: Webhook provider uses dummy payload for validation
  keep/providers/webhook_provider/webhook_provider.py
  tests/e2e_tests/test_end_to_end.py
Labels: Bug, Provider, size:S, lgtm

#5337 fix: Searching by incident.id in CEL filter
  keep/api/core/alerts.py
  tests/test_search_alerts.py
Labels: Bug, size:L, lgtm

#5339 feat: Maintenance windows improvements
  keep/api/bl/maintenance_windows_bl.py
  keep/api/core/db.py
  tests/test_maintenance_windows_bl.py
Labels: Feature, size:L, lgtm
