Repository keephq/keep, pull requests merged in 2025-04, with the labels that each got.

#4334 fix: timestamp
  keep/providers/mailgun_provider/mailgun_provider.py
Labels: Bug, size:XS, lgtm

#4270 fix: Add lastReceived handling during deduplication
  keep/api/tasks/process_event_task.py
  tests/conftest.py
  tests/deduplication/test_deduplications.py
Labels: size:L

#4332 feat: add support for topic sending and inline keyboard markup in Telegram message
  docs/snippets/providers/telegram-snippet-autogenerated.mdx
  examples/workflows/telegram_advanced.yml
  examples/workflows/telegram_basic.yml
  keep/providers/telegram_provider/telegram_provider.py
Labels: Feature, Provider, size:M, lgtm

#4337 feat: navbar dense
  keep-ui/app/(keep)/layout.tsx
  keep-ui/components/LinkWithIcon.tsx
  keep-ui/components/navbar/AILink.tsx
  keep-ui/components/navbar/AlertsLinks.tsx
  keep-ui/components/navbar/CustomPresetAlertLinks.tsx
  keep-ui/components/navbar/IncidentLinks.tsx
  keep-ui/components/navbar/NoiseReductionLinks.tsx
  keep-ui/components/navbar/UserInfo.tsx
Labels: Feature, UI, size:M, lgtm

#4340 fix: interval int
  keep/parser/parser.py
Labels: Bug, size:S

#4341 fix: navbar dense
  keep-ui/app/(keep)/layout.tsx
Labels: UI, size:XS, lgtm

#4343 fix: nav dashborad
  keep-ui/components/navbar/DashboardLink.tsx
Labels: UI, size:XS, lgtm

#4348 fix: remove special handling for 'name' column in draggable header
  keep-ui/app/(keep)/alerts/alert-table-headers.tsx
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
Labels: UI, size:S, lgtm

#4201 feat: add support for provisioning provider via YAML configuration and directory
  docs/deployment/provision/provider.mdx
  examples/providers/airflow-prod.yaml
  examples/providers/telegram-bot.yaml
  keep/api/alert_deduplicator/deduplication_rules_provisioning.py
  keep/api/config.py
  keep/providers/providers_service.py
  keep/workflowmanager/workflowstore.py
  tests/test_providers_yaml_provisioning.py
Labels: Documentation, Feature, Provider, size:XL, lgtm

#4311 feat: Multiple sorting columns choice based on priority
  keep-ui/app/(keep)/alerts/alert-table-headers.tsx
  keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
  keep-ui/features/keyboard-shortcuts/index.ts
  keep-ui/features/keyboard-shortcuts/useIsShiftKeyHeld.ts
  keep-ui/utils/hooks/useAlerts.ts
  keep/api/core/alerts.py
  keep/api/core/cel_to_sql/sql_providers/base.py
  keep/api/core/cel_to_sql/sql_providers/mysql.py
  keep/api/core/cel_to_sql/sql_providers/postgresql.py
  keep/api/core/cel_to_sql/sql_providers/sqlite.py
  keep/api/core/workflows.py
  keep/api/models/query.py
  keep/api/routes/alerts.py
  keep/searchengine/searchengine.py
  tests/cel_to_sql/order-by-exp-test-cases.json
  tests/cel_to_sql/test_order_by_exp.py
  tests/e2e_tests/incidents_alerts_tests/incidents_alerts_setup.py
  tests/e2e_tests/incidents_alerts_tests/test_filtering_sort_search_on_alerts.py
  tests/e2e_tests/incidents_alerts_tests/test_filtering_sort_search_on_incidents.py
Labels: Feature, UI, size:XL, lgtm

#4354 fix: run workflow from incident
  keep/api/routes/workflows.py
  pyproject.toml
Labels: size:XS

#4358 fix: remove js2py
  keep/providers/keep_provider/keep_provider.py
  poetry.lock
  pyproject.toml
Labels: Dependencies, size:XS, lgtm

#4362 fix: remove js2py
  tests/test_alert_evaluation.py
Labels: size:M

#4356 fix: workflow execution <null> in page title
  keep-ui/app/(keep)/incidents/[id]/workflows/incident-workflow-sidebar.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-detail-header.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-detail-page.tsx
  keep-ui/entities/workflow-executions/model/useWorkflowExecutionDetail.ts
  keep-ui/entities/workflow-executions/model/workflowExecutionsKeys.ts
  keep-ui/entities/workflows/model/useWorkflowDetail.ts
  keep-ui/features/workflow-execution-results/ui/WorkflowExecutionResults.tsx
  keep-ui/shared/api/workflow-executions.ts
  keep/api/core/db.py
  keep/api/routes/workflows.py
  keep/workflowmanager/workflowstore.py
Labels: Bug, size:L

#4372 feat: add telegram photo
  docs/snippets/providers/http-snippet-autogenerated.mdx
  docs/snippets/providers/telegram-snippet-autogenerated.mdx
  examples/workflows/telegram_basic.yml
  keep/providers/telegram_provider/telegram_provider.py
Labels: Feature, Provider, size:L, lgtm

#4360 feat: autodocument webhooks
  docs/providers/documentation/azuremonitoring-provider.mdx
  docs/providers/documentation/netdata-provider.mdx
  docs/snippets/providers/azuremonitoring-snippet-autogenerated.mdx
  docs/snippets/providers/graylog-snippet-autogenerated.mdx
  docs/snippets/providers/netdata-snippet-autogenerated.mdx
  docs/snippets/providers/parseable-snippet-autogenerated.mdx
  docs/snippets/providers/pingdom-snippet-autogenerated.mdx
  docs/snippets/providers/prometheus-snippet-autogenerated.mdx
  docs/snippets/providers/victoriametrics-snippet-autogenerated.mdx
  keep/providers/airflow_provider/airflow_provider.py
  keep/providers/axiom_provider/axiom_provider.py
  keep/providers/azuremonitoring_provider/azuremonitoring_provider.py
  keep/providers/checkly_provider/checkly_provider.py
  keep/providers/checkmk_provider/checkmk_provider.py
  keep/providers/coralogix_provider/coralogix_provider.py
  keep/providers/dash0_provider/dash0_provider.py
  keep/providers/gcpmonitoring_provider/gcpmonitoring_provider.py
  keep/providers/graylog_provider/graylog_provider.py
  keep/providers/libre_nms_provider/libre_nms_provider.py
  keep/providers/netbox_provider/netbox_provider.py
  keep/providers/netdata_provider/netdata_provider.py
  keep/providers/thousandeyes_provider/thousandeyes_provider.py
  keep/providers/wazuh_provider/wazuh_provider.py
  scripts/docs_render_provider_snippets.py
Labels: Documentation, Feature, size:XL, lgtm

#4380 feat: snow skip scope validation
  docs/providers/documentation/service-now-provider.mdx
  keep/providers/servicenow_provider/servicenow_provider.py
  pyproject.toml
Labels: Documentation, Feature, Provider, size:S

#4386 fix: best effort deleting provisioned provider
  keep/providers/providers_service.py
  pyproject.toml
Labels: Bug, size:S

#4403 fix: Allow OpenObserve to pass row name, which extends alert name
  keep/providers/openobserve_provider/openobserve_provider.py
Labels: Provider, size:XS, lgtm

#4405 fix: Refactor API handling and add retry on BadNamespaceError
  keep/providers/uptimekuma_provider/uptimekuma_provider.py
Labels: API, size:M, lgtm

#4394 feat: add OPENAI_MODEL_NAME environment variable for configurable OpenAI model
  docs/deployment/configuration.mdx
  keep-ui/app/api/copilotkit/route.ts
  keep/api/bl/ai_suggestion_bl.py
  keep/api/bl/incident_reports.py
  keep/api/consts.py
Labels: Documentation, Feature, size:S, lgtm

#4407 fix: Refactor error alert retrieval and improve default handling
  keep/api/core/db.py
  keep/api/routes/alerts.py
Labels: Bug, API, size:XS, lgtm

#4411 fix: enrich could be static values
  keep/providers/base/base_provider.py
  pyproject.toml
Labels: Bug, size:S

#4413 fix: Refactor heartbeat handling to return a list of alerts
  keep/providers/uptimekuma_provider/uptimekuma_provider.py
Labels: size:S, lgtm

#4363 fix: Victoriametrics
  keep/providers/victoriametrics_provider/victoriametrics_provider.py
Labels: Bug, Provider, size:S, lgtm

#4420 fix: prevent fallback icon infinite loop
  keep-ui/components/ui/DynamicProviderIcon.tsx
  keep-ui/shared/api/ApiClient.ts
Labels: Bug, UI, size:XS, lgtm

#4416 fix: provider logs delete cascade
  keep/api/models/db/migrations/versions/2025-04-04-21-48_0dafe96ea97f.py
  keep/api/models/db/provider.py
Labels: Provider, size:L

#4357 feat: simple permission model for workflows
  docs/mint.json
  docs/snippets/providers/http-snippet-autogenerated.mdx
  docs/snippets/providers/slack-snippet-autogenerated.mdx
  docs/workflows/syntax/permissions.mdx
  examples/workflows/permissions_example.yml
  keep-ui/app/(keep)/workflows/workflow-tile.tsx
  keep-ui/entities/workflows/model/yaml.schema.ts
  keep-ui/entities/workflows/ui/WorkflowPermissionsBadge.tsx
  keep-ui/features/workflows/manual-run-workflow/ui/manual-run-workflow-modal.tsx
  keep-ui/shared/api/workflows.ts
  keep/api/core/workflows.py
  keep/api/models/workflow.py
  keep/api/routes/workflows.py
  keep/identitymanager/rbac.py
  keep/parser/parser.py
  keep/workflowmanager/workflow.py
  keep/workflowmanager/workflowstore.py
  pyproject.toml
  tests/test_workflow_execution.py
Labels: Documentation, Feature, size:XL, lgtm

#4425 fix: update incident status commit once
  keep/api/bl/incidents_bl.py
  keep/api/core/db.py
Labels: Bug, size:M

#4426 fix(ui): reset params when not found
  keep-ui/app/(keep)/alerts/[id]/ui/alerts.tsx
Labels: UI, size:S

#4431 fix(dynatrace): url safe
  keep/providers/dynatrace_provider/dynatrace_provider.py
  keep/providers/prometheus_provider/prometheus_provider.py
Labels: Bug, Provider, size:S, lgtm

#4389 fix: add migration to change dashboard_config column type to JSON
  keep/api/models/db/migrations/versions/2025-04-03-12-09_bdf252fbc1be.py
  keep/api/models/db/migrations/versions/2025-04-06-12-18_78777e6b12d3.py
Labels: size:M, lgtm

#4436 fix: Handle OperationalError instead of IntegrityError in db.py
  keep/api/core/db.py
Labels: Bug, size:XS, lgtm

#4434 fix: alignment of alert actions on incident page
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alert-action-tray.tsx
Labels: UI, size:M, lgtm

#4260 feat: add opensearch serverless provider
  README.md
  docs/mint.json
  docs/providers/documentation/opensearchserverless-provider.mdx
  docs/providers/overview.mdx
  docs/snippets/providers/opensearchserverless-snippet-autogenerated.mdx
  examples/workflows/opensearchserverless_basic.yml
  keep-ui/public/icons/opensearchserverless-icon.png
  keep/providers/opensearchserverless_provider/README.md
  keep/providers/opensearchserverless_provider/__init__.py
  keep/providers/opensearchserverless_provider/opensearchserverless_provider.py
  poetry.lock
  pyproject.toml
Labels: Documentation, Feature, Provider, size:XL, lgtm

#4440 fix: Refactor retry logic for database operations
  keep/api/core/db.py
Labels: size:L

#4441 fix: Refactor database session handling and improve retry logic
  keep/api/core/db.py
Labels: Bug, size:L

#4442 feat: a drop of logging for snow
  keep/providers/servicenow_provider/servicenow_provider.py
  pyproject.toml
Labels: size:S

#4447 docs: openapi typo
  docs/deployment/configuration.mdx
Labels: Documentation, size:S

#4430 fix: Join alerts data only when requested in Incident CEL to SQL
  keep-ui/components/ui/DateRangePicker.tsx
  keep-ui/features/incidents/incident-list/ui/incident-list.tsx
  keep-ui/features/incidents/incident-list/ui/useIncidentsTableData.tsx
  keep-ui/utils/hooks/useIncidents.ts
  keep/api/core/alerts.py
  keep/api/core/facets.py
  keep/api/core/incidents.py
  keep/api/core/workflows.py
Labels: Bug, UI, API, Incident, size:XL, lgtm

#4454 fix: Add migration to restore idx_status_started index for workflowexecution table
  keep/api/models/db/migrations/versions/2025-04-08-10-43_59991b568c7d.py
Labels: size:M, lgtm

#4452 docs: sentry improvements
  docs/images/sentry-create-integration.png
  docs/images/sentry-indicative-name.png
  docs/images/sentry-internal-integration.png
  docs/images/sentry-new-token.png
  docs/images/sentry-save-changes.png
  docs/images/sentry-token.png
  docs/providers/documentation/sentry-provider.mdx
  keep/providers/sentry_provider/sentry_provider.py
Labels: Documentation, size:M

#4457 feat: sources
  docker/Dockerfile.ui
  keep-ui/entrypoint.sh
  keep-ui/next.config.js
  pyproject.toml
Labels: size:XS

#4461 chore: upgrade ruff
  poetry.lock
  pyproject.toml
Labels: Dependencies, size:XS, lgtm

#4464 fix: sources
  keep-ui/next.config.js
  pyproject.toml
Labels: Bug, size:XS

#4467 fix: Limit facet options per each facet
  keep/api/core/facets.py
  keep/api/core/incidents.py
Labels: Bug, size:S, lgtm

#4465 fix: Bug in TitleAndFilters component showing live reload is stopped although it's not
  keep-ui/widgets/alerts-table/ui/TitleAndFilters.tsx
Labels: Bug, UI, size:XS

#4475 fix: snow oauth via form-urlencoded
  keep/providers/servicenow_provider/servicenow_provider.py
  pyproject.toml
Labels: Provider, size:S

#4479 fix(ui): alerts count in incident alert table
  keep-ui/app/(keep)/incidents/[id]/incident-layout-client.tsx
  keep-ui/app/(keep)/incidents/[id]/incident-tabs-navigation.tsx
Labels: UI, size:S

#4481 fix(ui): slice first 20 rows in csv preview
  keep-ui/app/(keep)/mapping/[rule_id]/executions/page.tsx
  pyproject.toml
Labels: UI, size:S

#4491 fix: couple of different bugs
  docs/snippets/providers/splunk-snippet-autogenerated.mdx
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationSidebarBody.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationSubmission.tsx
  keep/api/bl/incidents_bl.py
  keep/api/core/db.py
  keep/api/tasks/process_incident_task.py
  keep/providers/cloudwatch_provider/cloudwatch_provider.py
  keep/providers/mailgun_provider/mailgun_provider.py
  keep/providers/splunk_provider/splunk_provider.py
  pyproject.toml
Labels: Bug, size:L, lgtm

#4495 fix: providers validation + test
  keep-ui/entities/workflows/lib/__tests__/validate-yaml.test.ts
  keep-ui/entities/workflows/lib/__tests__/validation.test.ts
  keep-ui/entities/workflows/lib/validate-yaml.ts
  keep-ui/entities/workflows/lib/validation.ts
  keep-ui/shared/ui/WorkflowYAMLEditor/lib/useYamlValidation.ts
Labels: Bug, size:XL

#4470 feat: Add support for incident enrichment and un-enrichment
  keep-ui/app/(keep)/incidents/[id]/enrichments/EnrichmentEditableField.tsx
  keep-ui/app/(keep)/incidents/[id]/enrichments/EnrichmentEditableForm.tsx
  keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
  keep/api/core/db.py
  keep/api/models/action_type.py
  keep/api/models/alert.py
  keep/api/models/db/incident.py
  keep/api/models/incident.py
  keep/api/routes/incidents.py
Labels: Feature, UI, API, size:XL, lgtm

#4497 fix: Facets not working in sqlite
  .github/workflows/run-e2e-tests.yml
  .github/workflows/test-pr-e2e.yml
  keep/api/core/facets.py
  tests/e2e_tests/docker-compose-e2e-sqlite.yml
Labels: Bug, size:XL, lgtm

#4499 feat: Bump version
  pyproject.toml
Labels: size:XS, lgtm

#4504 fix: fix for E2E not running for contributors
  .github/workflows/run-e2e-tests.yml
Labels: Bug, size:XS, lgtm

#4496 fix: support test runs with alert or incident payload
  keep-ui/app/(keep)/workflows/workflow-run-with-alert-modal.tsx
  keep-ui/components/ui/Modal.tsx
  keep-ui/components/ui/TextInput.tsx
  keep-ui/entities/workflow-executions/model/useWorkflowExecutionsRevalidation.ts
  keep-ui/entities/workflow-executions/model/workflowExecutionsKeys.ts
  keep-ui/entities/workflows/lib/__tests__/extractWorkflowYamlDependencies.test.ts
  keep-ui/entities/workflows/lib/__tests__/mustache.test.ts
  keep-ui/entities/workflows/lib/extractWorkflowYamlDependencies.ts
  keep-ui/entities/workflows/lib/mustache.ts
  keep-ui/entities/workflows/lib/parser.ts
  keep-ui/entities/workflows/model/types.ts
  keep-ui/entities/workflows/model/workflow-store.ts
  keep-ui/entities/workflows/model/workflowKeys.ts
  keep-ui/features/workflow-execution-results/ui/WorkflowExecutionLogs.tsx
  keep-ui/features/workflow-execution-results/ui/WorkflowExecutionResults.tsx
  keep-ui/features/workflows/test-run/index.ts
  keep-ui/features/workflows/test-run/lib/buildNestedObject.ts
  keep-ui/features/workflows/test-run/model/useWorkflowTestRun.ts
  keep-ui/features/workflows/test-run/ui/builder-workflow-testrun-modal-content.tsx
  keep-ui/features/workflows/test-run/ui/workflow-alert-incident-dependencies-form.tsx
  keep-ui/features/workflows/test-run/ui/workflow-test-run-button.tsx
  keep-ui/features/workflows/test-run/ui/workflow-test-run-modal.tsx
  keep-ui/shared/ui/JsonCard/JsonCard.tsx
  keep-ui/shared/ui/WorkflowYAMLEditor/ui/WorkflowYAMLEditorStandalone.tsx
  keep-ui/shared/ui/WorkflowYAMLEditor/ui/WorkflowYamlEditorHeader.tsx
  keep-ui/shared/ui/WorkflowYAMLEditorWithLogs/WorkflowYAMLEditorWithLogs.tsx
  keep-ui/utils/hooks/useWorkflowRun.ts
  keep-ui/widgets/workflow-builder/__tests__/workflow-builder.test.tsx
  keep-ui/widgets/workflow-builder/workflow-builder-widget.tsx
  keep/api/routes/workflows.py
Labels: Bug, UI, size:XXL

#4509 feat: provision install webhook and http provider `fail_on_error`
  docs/snippets/providers/http-snippet-autogenerated.mdx
  keep/api/routes/providers.py
  keep/providers/http_provider/http_provider.py
  keep/providers/providers_service.py
  pyproject.toml
Labels: Feature, Provider, size:L, lgtm

#4516 fix: return from http provider in action
  keep/contextmanager/contextmanager.py
  keep/providers/http_provider/http_provider.py
Labels: Bug, Provider, size:XS

#4418 fix: enhance TextField component to handle sensitive configuration
  docs/deployment/configuration.mdx
  keep-ui/app/(keep)/providers/form-fields.tsx
  keep-ui/shared/lib/server/getConfig.ts
  keep-ui/types/internal-config.ts
Labels: Enhancement, UI, size:M, lgtm

#4503 feat: Add columns configuration for alerts preset widget
  keep-ui/app/(keep)/dashboard/widget-types/preset/columns-selection.tsx
  keep-ui/app/(keep)/dashboard/widget-types/preset/constants.ts
  keep-ui/app/(keep)/dashboard/widget-types/preset/preset-grid-item.tsx
  keep-ui/app/(keep)/dashboard/widget-types/preset/preset-widget-form.tsx
  keep-ui/app/(keep)/dashboard/widget-types/preset/widget-alerts-table.tsx
Labels: Feature, UI, size:L, lgtm

#4524 fix: topology not showing alert count and a few more
  keep-ui/app/(keep)/topology/model/models.ts
  keep-ui/app/(keep)/topology/ui/map/getNodesAndEdgesFromTopologyData.ts
  keep-ui/app/(keep)/topology/ui/map/service-node.tsx
  keep-ui/app/(keep)/topology/ui/map/topology-map.tsx
  keep-ui/entities/alerts/model/types.ts
  keep-ui/entities/workflows/model/schema.ts
  keep-ui/widgets/alerts-table/lib/alert-table-utils.tsx
  keep-ui/widgets/alerts-table/ui/ColumnSelection.tsx
  keep-ui/widgets/alerts-table/ui/SettingsSelection.tsx
  keep-ui/widgets/alerts-table/ui/TitleAndFilters.tsx
  keep/api/models/incident.py
  keep/api/tasks/process_incident_task.py
  keep/providers/pagerduty_provider/pagerduty_provider.py
Labels: Bug, size:L, lgtm

#4525 fix: validation for secrets and consts
  docs/snippets/providers/http-snippet-autogenerated.mdx
  keep-ui/entities/workflows/lib/validate-yaml.ts
  keep-ui/entities/workflows/lib/validation.ts
  keep-ui/entities/workflows/model/schema.ts
  keep-ui/shared/ui/WorkflowYAMLEditor/lib/useYamlValidation.ts
  keep-ui/shared/ui/WorkflowYAMLEditor/ui/WorkflowYAMLEditor.tsx
  keep-ui/utils/hooks/useWorkflowSecrets.ts
  keep/providers/http_provider/http_provider.py
  pyproject.toml
Labels: Bug, size:M

#4530 fix: Replace toSorted with slice and sort for consistent column ordering
  keep-ui/app/(keep)/dashboard/widget-types/preset/columns-selection.tsx
  keep-ui/app/(keep)/dashboard/widget-types/preset/widget-alerts-table.tsx
  pyproject.toml
Labels: Bug, size:S

#4527 fix: grafana provider webhook info and provider search
  docs/snippets/providers/grafana-snippet-autogenerated.mdx
  keep-ui/app/(health)/health/check.tsx
  keep-ui/app/(keep)/providers/page.client.tsx
  keep-ui/app/(keep)/providers/provider-semi-automated.tsx
  keep-ui/app/(keep)/providers/providers-tiles.tsx
  keep/providers/grafana_provider/grafana_provider.py
Labels: Provider, UI, size:L

#4535 fix: topology for the incident
  keep-ui/app/(keep)/topology/ui/map/getLayoutedElements.ts
Labels: size:S, lgtm

#4540 fix: pagerduty oauth2 logs
  keep/providers/pagerduty_provider/pagerduty_provider.py
  pyproject.toml
Labels: Provider, size:S

#4544 fix: http provider enrich
  keep/providers/base/base_provider.py
  keep/providers/http_provider/http_provider.py
  pyproject.toml
Labels: Bug, Provider, size:S

#4537 fix: Update backend enrichment to leverage `UUIDType` processing
  keep-ui/app/(keep)/incidents/[id]/enrichments/EnrichmentEditableField.tsx
  keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
  keep/api/routes/incidents.py
Labels: size:XL, lgtm

#4549 feat: more verbose
  docs/snippets/providers/http-snippet-autogenerated.mdx
  docs/snippets/providers/prometheus-snippet-autogenerated.mdx
  keep/providers/grafana_provider/grafana_provider.py
  pyproject.toml
Labels: Enhancement, size:L, lgtm

#4553 feat(logging.py): added RotatingFileHandler settings for log file rollout
  keep/api/logging.py
Labels: size:XS, lgtm

#4552 fix: Update UptimeKuma status handling and datetime formatting
  keep/providers/uptimekuma_provider/uptimekuma_provider.py
Labels: Provider, size:M, lgtm

#4555 fix: Refactor content initialization in GCPMonitoring provider
  keep/providers/gcpmonitoring_provider/gcpmonitoring_provider.py
Labels: Provider, size:XS, lgtm

#4558 fix(opensearch): access key and key secret to not mandatory
  docs/snippets/providers/opensearchserverless-snippet-autogenerated.mdx
  keep/providers/opensearchserverless_provider/opensearchserverless_provider.py
  pyproject.toml
Labels: Bug, size:M, lgtm

#4564 fix: keycloak verify bug
  ee/identitymanager/identity_managers/keycloak/keycloak_authverifier.py
  ee/identitymanager/identity_managers/keycloak/keycloak_identitymanager.py
Labels: Bug, size:M, lgtm

#4562 fix: topology services without names
  keep-ui/app/(keep)/topology/ui/TopologySearchAutocomplete.tsx
  keep-ui/app/(keep)/topology/ui/applications/create-or-update-application-form.tsx
Labels: Bug, UI, size:XS

#4570 fix(pagerduty): pagination fix
  keep/providers/pagerduty_provider/pagerduty_provider.py
  pyproject.toml
Labels: Bug, size:M, lgtm

#4451 feat: workflow versioning
  keep-ui/app/(keep)/extraction/[rule_id]/executions/[execution_id]/page.tsx
  keep-ui/app/(keep)/incidents/[id]/workflows/incident-workflow-sidebar.tsx
  keep-ui/app/(keep)/incidents/[id]/workflows/incident-workflow-table.tsx
  keep-ui/app/(keep)/mapping/[rule_id]/executions/[execution_id]/page.tsx
  keep-ui/app/(keep)/settings/auth/users-table.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/table-filters.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/versions/[revision]/page.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-breadcrumbs.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-detail-header.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-detail-page.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-execution-table.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-executions-table.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-overview.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-secrets.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-sync-status.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-versions.tsx
  keep-ui/components/navbar/UserAvatar.tsx
  keep-ui/components/table/ExecutionsTable.tsx
  keep-ui/components/table/GenericTable.tsx
  keep-ui/entities/workflows/lib/ui-utils.tsx
  keep-ui/entities/workflows/model/__tests__/useWorkflowRevalidation.test.tsx
  keep-ui/entities/workflows/model/index.ts
  keep-ui/entities/workflows/model/useWorkflowDetail.ts
  keep-ui/entities/workflows/model/useWorkflowRevalidation.ts
  keep-ui/entities/workflows/model/useWorkflowRevisions.ts
  keep-ui/entities/workflows/model/workflowKeys.ts
  keep-ui/features/incidents/incident-list/ui/incident-table-component.tsx
  keep-ui/features/workflow-execution-results/ui/WorkflowExecutionResults.tsx
  keep-ui/features/workflows/builder/ui/Editor/StepEditor.tsx
  keep-ui/shared/api/workflow-executions.ts
  keep-ui/shared/api/workflows.ts
  keep-ui/shared/ui/MonacoYAMLEditor/MonacoYAMLEditor.types.ts
  keep-ui/shared/ui/MonacoYAMLEditor/editor.client.tsx
  keep-ui/shared/ui/MonacoYAMLEditor/editor.client.turbopack.tsx
  keep-ui/shared/ui/WorkflowYAMLEditor/index.ts
  keep-ui/shared/ui/WorkflowYAMLEditor/lib/utils.ts
  keep-ui/shared/ui/WorkflowYAMLEditor/model/types.ts
  keep-ui/shared/ui/WorkflowYAMLEditor/ui/WorkflowYAMLEditor.tsx
  keep-ui/shared/ui/WorkflowYAMLEditor/ui/WorkflowYAMLEditorStandalone.tsx
  keep-ui/shared/ui/WorkflowYAMLEditorWithLogs/WorkflowYAMLEditorWithLogs.tsx
  keep-ui/shared/ui/index.ts
  keep-ui/shared/ui/utils/getIconForStatusString.tsx
  keep-ui/widgets/workflow-builder/workflow-builder.tsx
  keep/api/core/db.py
  keep/api/models/db/migrations/versions/2025-04-15-15-30_885ff6b12fed.py
  keep/api/models/db/workflow.py
  keep/api/models/workflow.py
  keep/api/routes/workflows.py
  keep/parser/parser.py
  keep/workflowmanager/workflow.py
  keep/workflowmanager/workflowscheduler.py
  keep/workflowmanager/workflowstore.py
  tests/conftest.py
  tests/test_workflow_execution.py
  tests/test_workflowmanager.py
Labels: Feature, UI, size:XXL

#4572 feat: posthog provider
  docs/mint.json
  docs/providers/documentation/posthog-provider.mdx
  docs/providers/overview.mdx
  docs/snippets/providers/posthog-snippet-autogenerated.mdx
  docs/snippets/providers/slack-snippet-autogenerated.mdx
  examples/workflows/posthog_example.yml
  keep-ui/public/icons/posthog-icon.png
  keep/providers/posthog_provider/__init__.py
  keep/providers/posthog_provider/posthog_provider.py
Labels: Documentation, Feature, Provider, size:XL, lgtm

#4578 fix: pagerduty sort by
  keep/providers/pagerduty_provider/pagerduty_provider.py
  pyproject.toml
Labels: Bug, Provider, size:XS

#4581 feat: self signed cert support for prometheus
  docs/snippets/providers/prometheus-snippet-autogenerated.mdx
  keep/providers/prometheus_provider/prometheus_provider.py
  pyproject.toml
Labels: Feature, Provider, size:S, lgtm

#4584 fix: Update __save_error_alerts to handle single AlertDto input
  keep/api/tasks/process_event_task.py
Labels: Bug, size:XS

#4586 fix: Refactor tenant configurations handling for better robustness
  keep/api/core/db.py
  keep/api/core/tenant_configuration.py
Labels: size:S, lgtm

#4588 fix: Handle race conditions when updating incidents in database
  keep/rulesengine/rulesengine.py
Labels: Bug, size:S, lgtm

#4593 fix(utils): convert string indices to int in index() function to prevent TypeError
  keep/functions/__init__.py
Labels: Bug, size:XS, lgtm

#4575 fix: wf versions migration
  keep/api/models/db/migrations/versions/2025-04-15-15-30_885ff6b12fed.py
  keep/api/models/db/workflow.py
Labels: Bug, size:M, lgtm

#4568 feat: batch alerts enrichment using cel
  keep/api/models/alert.py
  keep/api/models/query.py
  keep/api/routes/alerts.py
  tests/test_batch_enrich_cel.py
  tests/test_enrichments.py
Labels: Documentation, Feature, API, size:XL

#4590 fix: Replace some workflows exception logging with warning and include context
  keep/parser/parser.py
  keep/providers/newrelic_provider/newrelic_provider.py
  keep/workflowmanager/workflowmanager.py
  keep/workflowmanager/workflowscheduler.py
Labels: size:M

#4602 fix: Enhance logging and event handling in Mailgun provider
  keep/providers/mailgun_provider/mailgun_provider.py
Labels: Provider, size:XS

#4609 fix(pagerduty): incident alert is None in some cases
  keep/identitymanager/identity_managers/oauth2proxy/oauth2proxy_authverifier.py
  keep/providers/pagerduty_provider/pagerduty_provider.py
  pyproject.toml
Labels: Bug, Provider, size:M

#4614 fix: Workflow facets stop updating when using search
  keep/api/core/workflows.py
Labels: Bug, size:XS

#4622 fix: workflow-updating-via-s3
  keep/api/core/db.py
  keep/providers/keep_provider/keep_provider.py
  keep/workflowmanager/workflowstore.py
  pyproject.toml
Labels: Bug, size:S

#4620 fix: Incident field cant be queried
  keep/api/core/alerts.py
  keep/api/core/cel_to_sql/properties_mapper.py
  keep/api/core/cel_to_sql/sql_providers/base.py
  keep/api/core/cel_to_sql/sql_providers/mysql.py
  keep/api/core/cel_to_sql/sql_providers/postgresql.py
  keep/api/core/cel_to_sql/sql_providers/sqlite.py
  keep/api/core/incidents.py
  tests/cel_to_sql/cel-to-sql-test-cases.json
  tests/cel_to_sql/test_cel_to_sql.py
Labels: Bug, size:L

#4625 fix: Refactor retry logic to handle additional DB errors
  keep/api/core/db.py
Labels: Bug, size:S, lgtm

#4597 feat: Use monaco editor instead of query builder for CEL
  keep-ui/features/cel-input/cel-input.tsx
  keep-ui/features/filter/index.ts
  keep-ui/features/presets/presets-manager/ui/alerts-rules-builder.tsx
  keep-ui/next.config.js
  keep-ui/shared/ui/MonacoCELEditor/MonacoCel.tsx
  keep-ui/shared/ui/MonacoCELEditor/MonacoCel.turbopack.tsx
  keep-ui/shared/ui/MonacoCELEditor/cel-support.ts
  keep-ui/shared/ui/MonacoCELEditor/editor.scss
  keep-ui/shared/ui/MonacoCELEditor/handle-completions.ts
  keep-ui/shared/ui/MonacoCELEditor/index.ts
  keep-ui/shared/ui/MonacoCELEditor/monaco-cel-editor.tsx
  pyproject.toml
  tests/e2e_tests/incidents_alerts_tests/test_filtering_sort_search_on_alerts.py
Labels: Feature, UI, size:XL, lgtm

#4627 fix: Handle None property metadata in facet selection
  keep/api/core/facets.py
Labels: Bug, size:XS, lgtm

#4634 fix: Improve timeline layout and add alert fingerprint display
  keep-ui/app/(keep)/incidents/[id]/timeline/incident-timeline.tsx
Labels: UI, size:L, lgtm

#4638 fix: Enhance DB retry logic to handle StaleDataError
  keep/api/core/db.py
Labels: Bug, size:XS

#4639 fix: Update middleware to exclude /api/healthcheck from auth
  keep-ui/middleware.ts
Labels: Bug, API, size:XS

#4641 fix: Fix bug causing E2E to fail
  keep-ui/features/presets/presets-manager/ui/alerts-rules-builder.tsx
Labels: Bug, UI, size:XS

#4643 feat: add clipboard functionality to copy alert fingerprint in AlertSidebar
  keep-ui/features/alerts/alert-detail-sidebar/ui/alert-sidebar.tsx
Labels: Feature, UI, size:M, lgtm

#4645 fix: Skip instance-level enrichment for elastic. Ensure enrichments are applied conditionally
  keep/api/bl/enrichments_bl.py
  keep/providers/base/base_provider.py
Labels: Bug, size:S, lgtm

#4600 fix: dummy workflow per tenant
  keep-ui/features/workflows/test-run/ui/workflow-test-run-button.tsx
  keep/api/core/db.py
  keep/api/core/db_utils.py
  keep/api/core/workflows.py
  keep/api/models/db/migrations/versions/2025-04-21-10-18_819927b7ccfa.py
  keep/api/models/db/workflow.py
  keep/api/routes/workflows.py
  keep/parser/parser.py
  keep/workflowmanager/workflow.py
  keep/workflowmanager/workflowstore.py
Labels: Bug, API, size:L, lgtm

#4652 test: duplicate wf provisioning
  .github/workflows/test-pr-integrations.yml
  .github/workflows/test-pr-ut.yml
  .gitignore
  keep/api/core/db.py
  keep/api/routes/workflows.py
  keep/workflowmanager/workflowscheduler.py
  keep/workflowmanager/workflowstore.py
  tests/provision/workflows_3/workflows_with_no_name.yml
  tests/test_workflowstore.py
Labels: size:L, lgtm

#4654 feat: Add linting for cel input
  keep-ui/features/cel-input/cel-input.tsx
  keep-ui/features/presets/presets-manager/ui/alerts-rules-builder.tsx
  keep-ui/shared/ui/MonacoCELEditor/monaco-cel-editor.tsx
  keep-ui/shared/ui/MonacoCELEditor/validation-hook.ts
  keep/api/api.py
  keep/api/routes/cel.py
Labels: Feature, UI, size:L

#4655 feat: add support for user mentions in Adaptive Cards for Teams notifications
  docs/providers/documentation/teams-provider.mdx
  docs/snippets/providers/teams-snippet-autogenerated.mdx
  examples/workflows/keep-teams-adaptive-cards-with-mentions.yaml
  examples/workflows/keep-teams-adaptive-cards.yaml
  keep/providers/teams_provider/teams_provider.py
  tests/test_teams_provider.py
Labels: Documentation, Feature, size:L, lgtm
