Repository keephq/keep, pull requests merged in 2025-06, with the labels that each got.

#4953 fix: validate variable in action inside foreach container
  keep-ui/entities/workflows/lib/__tests__/validate-mustache.test.ts
  keep-ui/entities/workflows/lib/__tests__/validation.test.ts
  keep-ui/entities/workflows/lib/validate-definition.ts
Labels: Bug, size:L, lgtm

#4955 fix: workflow `consts` could be of many types
  examples/workflows/consts_and_dict.yml
  keep-ui/entities/workflows/lib/__tests__/parseWorkflowYamlToJSON.test.ts
  keep-ui/entities/workflows/model/schema.ts
  keep-ui/entities/workflows/model/yaml.schema.ts
  keep/api/routes/workflows.py
Labels: Bug, size:M, lgtm

#4956 fix: Pagination not reset after filtering results in empty page
  keep-ui/app/(keep)/workflows/existing-workflows-state.tsx
  keep-ui/app/(keep)/workflows/workflow-templates/workflow-templates.tsx
  keep-ui/features/filter/pagination.tsx
  keep-ui/features/presets/presets-manager/ui/alerts-rules-builder.tsx
  keep-ui/widgets/alerts-table/ui/alert-pagination-server-side.tsx
  keep-ui/widgets/alerts-table/ui/alert-table-server-side.tsx
Labels: Bug, UI, size:L

#4961 fix: alert evaluation
  keep/providers/keep_provider/keep_provider.py
  pyproject.toml
  tests/test_alert_evaluation.py
  tests/test_workflows.py
Labels: Bug, size:L, lgtm

#4963 fix: return 400 from /run or /test if workflow is invalid
  keep-ui/features/workflows/manual-run-workflow/model/useWorkflowRun.ts
  keep-ui/shared/ui/utils/showErrorToast.tsx
  keep/api/routes/workflows.py
  tests/test_workflow_api.py
Labels: Bug, size:L, lgtm

#4978 docs(auth): capitalize valid options for auth
  docs/deployment/configuration.mdx
Labels: Documentation, size:S

#4969 docs: Create oauth2-proxy-gitlab.md
  docs/deployment/authentication/oauth2-proxy-gitlab.mdx
  docs/mint.json
Labels: Documentation, size:L, lgtm

#4988 chore: bump version from 0.45.1 to 0.45.2
  pyproject.toml
Labels: Dependencies, size:XS, lgtm

#4944 chore: Improve provider docs
  docs/providers/adding-a-new-provider.mdx
  docs/providers/linked-providers.mdx
  docs/providers/provider-methods.mdx
Labels: Documentation, Provider, size:XXL, lgtm

#5001 feat(ui): add alert sidebar to incident table
  keep-ui/app/(keep)/incidents/[id]/alerts/ALERT_SIDEBAR_INTEGRATION.md
  keep-ui/app/(keep)/incidents/[id]/alerts/__tests__/incident-alerts-sidebar.test.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/__tests__/incident-alerts.test.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
  keep-ui/docs/incident-alerts/ALERT_SIDEBAR_INTEGRATION.md
  keep-ui/docs/incident-alerts/CI_CD_FIXES.md
  keep-ui/features/alerts/alert-detail-sidebar/ui/alert-sidebar.tsx
Labels: Feature, UI, size:XXL, lgtm

#5013 fix: get_all_workflows_with_last_execution shouldn't return dummy workflows
  keep/api/core/db.py
  keep/api/core/workflows.py
  pyproject.toml
  tests/test_workflowstore.py
Labels: Bug, size:M, lgtm

#5006 feat: support OPENAI_MODEL_NAME override and fix Copilot runtime init syntax
  keep-ui/app/api/copilotkit/route.ts
Labels: Feature, size:XS, lgtm

#5004 fix: legit html in alert and incident descriptions
  keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
  keep-ui/eslint.config.mjs
  keep-ui/features/incidents/incident-list/ui/incidents-table.tsx
  keep-ui/package-lock.json
  keep-ui/package.json
  keep-ui/shared/ui/FormattedContent/FormattedContent.tsx
  keep-ui/shared/ui/theme/ThemeScript.tsx
  tests/e2e_tests/docker-compose-e2e-postgres.yml
  tests/e2e_tests/incidents_alerts_tests/incidents_alerts_setup.py
  tests/e2e_tests/incidents_alerts_tests/test_xss_protection.py
Labels: Bug, UI, size:L, lgtm

#5021 build: bump version to 0.45.4
  pyproject.toml
Labels: Dependencies, size:XS, lgtm

#5027 fix: Log request headers in case of No valid authentication method found
  keep/identitymanager/authverifierbase.py
Labels: Bug, size:XS, lgtm

#5037 fix: flacky e2e test `test_run_workflow_from_alert_and_incident`
  keep-ui/components/ui/Modal.tsx
  tests/e2e_tests/test_end_to_end.py
Labels: size:S

#5029 fix: bug authentication errors hard to investigate without extra data in logs
  keep/api/core/dependencies.py
  keep/identitymanager/authverifierbase.py
  keep/identitymanager/identity_managers/oauth2proxy/oauth2proxy_authverifier.py
Labels: Bug, size:S, lgtm

#5058 fix: Fix bug on incidents pagination
  keep-ui/features/filter/facet-value.tsx
  keep-ui/features/filter/facet.tsx
  keep-ui/features/filter/pagination.tsx
  keep-ui/features/filter/store/__tests__/facets-store.test.ts
  keep-ui/features/filter/store/create-facets-store.ts
  keep-ui/features/incidents/incident-list/ui/incident-list.tsx
  keep-ui/features/incidents/incident-list/ui/incidents-table.tsx
Labels: Bug, UI, size:L, lgtm

#5054 feat: add end-to-end test for interval workflow
  tests/e2e_tests/test_end_to_end.py
  tests/e2e_tests/workflow-interval.yaml
Labels: Feature, size:M, lgtm

#5031 test: foreach jumps to the end of workflow in UI Builder
  keep-ui/entities/workflows/lib/__tests__/parser.test.ts
  keep-ui/entities/workflows/lib/parser.ts
Labels: UI, size:L, lgtm

#5057 feat: add dbsecretmanager
  docs/deployment/configuration.mdx
  docs/deployment/secret-store.mdx
  keep/api/models/db/migrations/env.py
  keep/api/models/db/migrations/versions/2025-06-18-17-17_9dd1be4539e0.py
  keep/api/models/db/secret.py
  keep/secretmanager/dbsecretmanager.py
  keep/secretmanager/secretmanagerfactory.py
Labels: Documentation, Feature, size:L, lgtm

#5079 feat: support classes
  keep/providers/python_provider/python_provider.py
  pyproject.toml
Labels: Feature, size:M, lgtm

#5081 fix: db write secret error
  keep/secretmanager/dbsecretmanager.py
Labels: Bug, size:XS, lgtm

#5083 fix: UT's
  pyproject.toml
  tests/test_workflows.py
Labels: Bug, size:XS, lgtm

#5065 fix: sort workflow execution logs asc
  keep/api/core/db.py
  tests/test_workflowstore.py
Labels: size:M

#5074 feat: Improve OpenShift provider connection validation using REST API
  docs/snippets/providers/base-snippet-autogenerated.mdx
  docs/snippets/providers/console-snippet-autogenerated.mdx
  docs/snippets/providers/openshift-snippet-autogenerated.mdx
  docs/snippets/providers/slack-snippet-autogenerated.mdx
  examples/workflows/openshift_basic.yml
  examples/workflows/openshift_monitoring_and_remediation.yml
  examples/workflows/openshift_pod_restart.yml
  keep/providers/openshift_provider/openshift_provider.py
Labels: Provider, API, size:XXL

#5109 fix: co-int/str for CELs
  keep/rulesengine/rulesengine.py
  pyproject.toml
  tests/test_alert_evaluation.py
Labels: Bug, size:L, lgtm

#5113 fix: bug with saving presets and default columns
  keep-ui/features/presets/presets-manager/ui/__tests__/alert-preset-manager.test.tsx
  keep-ui/features/presets/presets-manager/ui/__tests__/preset-navigation.test.ts
  keep-ui/features/presets/presets-manager/ui/alert-preset-manager.tsx
  keep-ui/widgets/alerts-table/ui/ColumnSelection.tsx
  pyproject.toml
Labels: Bug, UI, size:L, lgtm
