Repository keephq/keep, pull requests merged in 2025-01, with the labels that each got.

#2958 fix: slow lastalert query
  docs/deployment/getting-started.mdx
  docs/mint.json
  keep/api/core/db.py
  keep/api/middlewares.py
  keep/api/models/db/alert.py
  keep/api/models/db/migrations/versions/2025-01-01-09-59_dcb7f88a04da.py
Labels: Bug, API, size:L, lgtm

#2965 fix: CEL with quote
  keep-ui/app/(keep)/alerts/alerts-rules-builder.tsx
Labels: Bug, size:S, lgtm

#2967 Feat/trace
  keep-ui/app/(keep)/alerts/alert-menu.tsx
  keep-ui/app/(keep)/alerts/alerts-rules-builder.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alert-actions.tsx
  keep-ui/app/(keep)/incidents/[id]/chat/incident-chat.css
  keep-ui/app/(keep)/incidents/[id]/chat/incident-chat.tsx
  keep-ui/app/(keep)/incidents/[id]/chat/page.client.tsx
  keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
  keep-ui/app/(keep)/incidents/[id]/incident-tabs-navigation.tsx
  keep-ui/app/(keep)/incidents/[id]/layout.tsx
  keep-ui/app/(keep)/workflows/builder/editors.tsx
  keep-ui/app/(keep)/workflows/workflow-tile.tsx
  keep-ui/components/ui/DynamicIcon.tsx
  keep-ui/components/ui/index.ts
  keep-ui/entities/incidents/model/models.ts
  keep-ui/entities/incidents/model/useIncidentActions.tsx
  keep-ui/package-lock.json
  keep-ui/package.json
  keep-ui/shared/ui/TraceViewer/Trace.ts
  keep-ui/shared/ui/TraceViewer/TraceViewer.tsx
  keep-ui/shared/ui/TraceViewer/index.ts
  keep/api/api.py
  keep/api/bl/enrichments_bl.py
  keep/api/bl/incidents_bl.py
  keep/api/bl/maintenance_windows_bl.py
  keep/api/core/db.py
  keep/api/core/tracer.py
  keep/api/models/alert.py
  keep/api/models/alert_audit.py
  keep/api/models/db/alert.py
  keep/api/routes/alerts.py
  keep/api/routes/incidents.py
  keep/api/tasks/process_event_task.py
  keep/providers/base/base_provider.py
  keep/providers/datadog_provider/datadog_provider.py
  keep/providers/github_provider/github_provider.py
  keep/providers/models/provider_method.py
  keep/providers/postgres_provider/postgres_provider.py
  poetry.lock
  pyproject.toml
  tests/test_enrichments.py
  tests/test_functions.py
  tests/test_search_alerts.py
Labels: Feature, UI, size:XXL

#2969 fix(smtp): no encryption
  keep/providers/smtp_provider/smtp_provider.py
Labels: Bug, size:XS

#2972 chore(version): bump
  pyproject.toml
Labels: Dependencies, size:XS

#2966 fix: event as list[AlertDTO] not included in the condition
  keep/api/tasks/process_event_task.py
Labels: Bug, size:S, lgtm

#2977 feat(ui): minor changes in the uI
  keep-ui/app/(keep)/alerts/ViewAlertModal.tsx
  keep-ui/app/(keep)/alerts/alerts-rules-builder.tsx
Labels: UI, size:L

#2962 feat(api): change calculation variable for pull data from providers
  keep/api/consts.py
  keep/api/routes/preset.py
Labels: Enhancement, Provider, size:S, lgtm

#2979 feat(api): grafana extra values
  keep/providers/grafana_provider/grafana_provider.py
  pyproject.toml
Labels: Feature, API, size:S, lgtm

#2981 fix: allow clickhouse protocol variaty
  keep/providers/clickhouse_provider/clickhouse_provider.py
Labels: Provider, size:S

#2988 fix(api): workflowdb handler
  keep/api/logging.py
  pyproject.toml
  tests/test_workflow_execution.py
Labels: Bug, size:M, lgtm

#2989 fix: posthog to None if disabled
  keep/api/core/posthog.py
  keep/cli/cli.py
Labels: CLI, size:M

#2971 fix: handle unhealthy backend on frontend
  keep-ui/app/(keep)/error.css
  keep-ui/app/(keep)/error.ts
  keep-ui/app/(keep)/error.tsx
  keep-ui/app/(keep)/loading.tsx
  keep-ui/app/(keep)/settings/auth/users-settings.tsx
  keep-ui/app/(keep)/workflows/workflows.client.tsx
  keep-ui/app/global-error.tsx
  keep-ui/components/navbar/UserInfo.tsx
  keep-ui/features/incident-list/ui/incident-list-error.tsx
  keep-ui/features/incident-list/ui/incident-list.tsx
  keep-ui/shared/api/ApiClient.ts
  keep-ui/shared/api/KeepApiError.ts
  keep-ui/shared/lib/hooks/useHealth.ts
  keep-ui/shared/ui/ErrorComponent/ErrorComponent.tsx
  keep-ui/shared/ui/ErrorComponent/index.ts
  keep-ui/shared/ui/KeepLogoError/KeepLogoError.tsx
  keep-ui/shared/ui/KeepLogoError/index.ts
  keep-ui/shared/ui/KeepLogoError/keep_big.svg
  keep-ui/shared/ui/KeepLogoError/logo-error.css
  keep-ui/shared/ui/index.ts
  keep-ui/shared/ui/utils/showErrorToast.tsx
Labels: UI, size:XL

#2993 fix: test run bug and feat: general UI/UX improvements
  keep-ui/app/(keep)/workflows/[workflow_id]/executions.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/layout.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/page.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/side-nav-bar.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/table-filters.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-detail-header.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-detail-page.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-overview.tsx
  keep-ui/app/(keep)/workflows/builder/CustomNode.tsx
  keep-ui/app/(keep)/workflows/builder/ToolBox.tsx
  keep-ui/app/(keep)/workflows/builder/[workflowId]/page.tsx
  keep-ui/app/(keep)/workflows/builder/builder-modal.tsx
  keep-ui/app/(keep)/workflows/builder/builder-validators.tsx
  keep-ui/app/(keep)/workflows/builder/builder-workflow-testrun-modal.tsx
  keep-ui/app/(keep)/workflows/builder/builder.tsx
  keep-ui/app/(keep)/workflows/builder/page.client.tsx
  keep-ui/app/(keep)/workflows/builder/page.tsx
  keep-ui/app/(keep)/workflows/builder/utils.tsx
  keep-ui/app/(keep)/workflows/builder/workflow-execution-results.tsx
  keep-ui/app/(keep)/workflows/mockworkflows.tsx
  keep-ui/app/(keep)/workflows/preview/[workflowId]/page.tsx
  keep-ui/app/(keep)/workflows/preview/page.tsx
  keep-ui/components/table/GenericTable.tsx
  keep-ui/components/table/Pagination.tsx
  keep-ui/components/ui/discolsure-section.tsx
  keep-ui/shared/ui/TabLinkNavigation/TabNavigationLink.tsx
  keep-ui/shared/ui/YAMLCodeblock/index.ts
  keep-ui/shared/ui/YAMLCodeblock/ui/YAMLCodeblock.tsx
  keep-ui/shared/ui/index.ts
  keep-ui/utils/hooks/useWorkflowExecutions.ts
  keep-ui/utils/hooks/useWorkflowInitialization.ts
  keep-ui/utils/reactFlow.ts
  keep/api/routes/workflows.py
Labels: Bug, UI, size:XXL, lgtm

#2994 docs: Update howdoeskeepgetmyalerts.mdx
  docs/overview/howdoeskeepgetmyalerts.mdx
Labels: Documentation, size:XS, lgtm

#2998 fix: WorkflowExecutionsPaginatedResultsDto expects WorkflowExecutionDTO instances
  keep/api/routes/incidents.py
Labels: Bug, size:XS, lgtm

#3007 fix: interval docs
  docs/workflows/syntax/triggers.mdx
Labels: Documentation, size:S

#3006 feat: workflow execution logs ux
  keep-ui/app/(keep)/incidents/[id]/workflows/incident-workflow-sidebar.tsx
  keep-ui/app/(keep)/incidents/[id]/workflows/incident-workflow-table.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/runs/[workflow_execution_id]/page.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-detail-header.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-detail-page.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-execution-table.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-overview.tsx
  keep-ui/app/(keep)/workflows/builder/builder-workflow-testrun-modal.tsx
  keep-ui/app/(keep)/workflows/builder/builder.tsx
  keep-ui/app/(keep)/workflows/builder/types.ts
  keep-ui/app/(keep)/workflows/builder/workflow-execution-results.tsx
  keep-ui/app/(keep)/workflows/mockworkflows.tsx
  keep-ui/app/(keep)/workflows/noworkflows.tsx
  keep-ui/app/(keep)/workflows/workflow-definition-yaml.tsx
  keep-ui/app/(keep)/workflows/workflow-graph.tsx
  keep-ui/app/(keep)/workflows/workflow-tile.tsx
  keep-ui/app/(keep)/workflows/workflow-utils.ts
  keep-ui/app/(keep)/workflows/workflows.client.tsx
  keep-ui/features/incident-list/ui/incident-pagination.tsx
  keep-ui/features/workflow-execution-results/index.ts
  keep-ui/features/workflow-execution-results/lib/logs-utils.ts
  keep-ui/features/workflow-execution-results/ui/WorkflowDefinitionYAML.tsx
  keep-ui/features/workflow-execution-results/ui/WorkflowExecutionError.tsx
  keep-ui/features/workflow-execution-results/ui/WorkflowExecutionLogs.tsx
  keep-ui/features/workflow-execution-results/ui/WorkflowExecutionResults.tsx
  keep-ui/public/keep-failure.png
  keep-ui/public/keep-pending.png
  keep-ui/public/keep-success.png
  keep-ui/shared/api/workflow-executions.ts
  keep-ui/shared/api/workflows.ts
  keep-ui/shared/ui/utils/favicon.ts
  keep-ui/utils/hooks/useIncidents.ts
  keep-ui/utils/hooks/useWorkflowExecutions.ts
  keep-ui/utils/hooks/useWorkflowRun.ts
  keep-ui/utils/hooks/useWorkflows.ts
  keep/api/logging.py
  keep/step/step.py
  keep/workflowmanager/workflow.py
Labels: Feature, UI, size:XXL, lgtm

#3002 feat: Amazon SQS Provider
  README.md
  docs/mint.json
  docs/providers/documentation/amazonsqs-provider.mdx
  docs/providers/overview.mdx
  keep-ui/public/icons/amazonsqs-icon.png
  keep/providers/amazonsqs_provider/__init__.py
  keep/providers/amazonsqs_provider/amazonsqs_provider.py
  pyproject.toml
Labels: Documentation, Feature, Provider, size:L, lgtm

#3001 docs: update enrichment.mdx
  docs/workflows/syntax/enrichment.mdx
  docs/workflows/syntax/triggers.mdx
Labels: Documentation, size:S, lgtm

#3020 fix(api): add limit log
  keep/api/core/limiter.py
  pyproject.toml
Labels: Bug, size:XS

#3024 fix: incident reoslve on default value
  keep/api/models/alert.py
  pyproject.toml
Labels: Bug, size:S, lgtm

#3026 fix: Add WorkflowExecution.started index
  keep/api/models/db/migrations/versions/2025-01-14-18-41_416155f25854.py
  keep/api/models/db/workflow.py
Labels: size:M, lgtm

#3031 fix(readme): minor change
  README.md
Labels: Documentation, size:XS

#3027 feat: render_without_execution
  docs/workflows/syntax/functions.mdx
  keep/iohandler/iohandler.py
  tests/test_functions.py
Labels: Documentation, Feature, size:M

#3040 fix(ui): pusher
  keep-ui/utils/hooks/usePusher.ts
  pyproject.toml
Labels: UI, size:S, lgtm

#3039 feat: monday provider
  README.md
  docs/mint.json
  docs/providers/documentation/monday-provider.mdx
  docs/providers/overview.mdx
  examples/workflows/monday_create_pulse.yml
  keep-ui/public/icons/monday-icon.png
  keep/providers/monday_provider/__init__.py
  keep/providers/monday_provider/monday_provider.py
Labels: Documentation, Feature, Provider, size:L

#3042 fix: correlation rule `is_deleted`
  keep-ui/app/(keep)/incidents/[id]/incident-header.tsx
  keep-ui/entities/incidents/model/models.ts
  keep/api/core/db.py
  keep/api/models/alert.py
  keep/api/models/db/migrations/versions/2025-01-16-14-00_e3f33e571c3c.py
  keep/api/models/db/rule.py
  keep/api/routes/incidents.py
Labels: Correlation, size:M

#3045 fix: S3 icon
  keep-ui/public/icons/s3-icon.png
Labels: UI, size:XS

#3044 fix: Fix broken provider images all around
  keep-ui/app/(keep)/alerts/alert-assign-ticket-modal.tsx
  keep-ui/app/(keep)/alerts/alert-menu.tsx
  keep-ui/app/(keep)/alerts/alert-push-alert-to-server-modal.tsx
  keep-ui/app/(keep)/alerts/alert-sidebar.tsx
  keep-ui/app/(keep)/alerts/alert-table-facet-value.tsx
  keep-ui/app/(keep)/alerts/alert-table-utils.tsx
  keep-ui/app/(keep)/alerts/alert-timeline.tsx
  keep-ui/app/(keep)/deduplication/DeduplicationPlaceholder.tsx
  keep-ui/app/(keep)/deduplication/DeduplicationTable.tsx
  keep-ui/app/(keep)/incidents/[id]/activity/incident-activity.tsx
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
  keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
  keep-ui/app/(keep)/incidents/[id]/timeline/incident-timeline.tsx
  keep-ui/app/(keep)/incidents/predicted-incidents-table.tsx
  keep-ui/app/(keep)/providers/provider-form.tsx
  keep-ui/app/(keep)/providers/provider-semi-automated.tsx
  keep-ui/app/(keep)/providers/provider-tile.tsx
  keep-ui/app/(keep)/rules/CorrelationPlaceholder.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/AlertsFoundBadge.tsx
  keep-ui/app/(keep)/topology/ui/map/service-node.tsx
  keep-ui/app/(keep)/workflows/builder/CustomNode.tsx
  keep-ui/app/(keep)/workflows/builder/ToolBox.tsx
  keep-ui/app/(keep)/workflows/builder/editors.tsx
  keep-ui/app/(keep)/workflows/mockworkflows.tsx
  keep-ui/app/(keep)/workflows/noworkflows.tsx
  keep-ui/app/(keep)/workflows/workflow-tile.tsx
  keep-ui/components/ImageWithFallback.tsx
  keep-ui/components/ui/DynamicIcon.tsx
  keep-ui/components/ui/DynamicProviderIcon.tsx
  keep-ui/components/ui/RootCauseAnalysis.tsx
  keep-ui/components/ui/index.ts
  keep-ui/features/incident-list/ui/incidents-table.tsx
  keep-ui/public/icons/unknown-icon.png
Labels: Bug, UI, size:L

#3047 feat(docs): add sound.mdx
  docs/alerts/actionmenu.mdx
  docs/alerts/sound.mdx
  docs/mint.json
Labels: Documentation, size:S

#3050 feat(api): uvicorn
  keep/api/logging.py
  pyproject.toml
Labels: Feature, API, size:S, lgtm

#3056 fix: yaml.safe_load is slow as hell
  keep/actions/actions_factory.py
  keep/api/models/workflow.py
  keep/api/routes/actions.py
  keep/api/routes/workflows.py
  keep/cli/cli.py
  keep/functions/cyaml.py
  keep/parser/parser.py
  keep/providers/aks_provider/aks_provider.py
  keep/providers/sendgrid_provider/sendgrid_provider.py
  keep/workflowmanager/workflowstore.py
  tests/test_parser.py
Labels: size:L, lgtm

#3052 fix(api): performance
  docker/Dockerfile.api
  keep/api/alert_deduplicator/alert_deduplicator.py
  keep/api/api.py
  keep/api/core/dependencies.py
  keep/api/core/limiter.py
  keep/api/logging.py
  keep/api/middlewares.py
  keep/api/routes/alerts.py
  keep/api/routes/providers.py
  poetry.lock
  pyproject.toml
  tests/fixtures/client.py
Labels: Bug, size:L, lgtm

#3062 fix(grafana): print number of alerts in payload
  keep/providers/grafana_provider/grafana_provider.py
  pyproject.toml
Labels: Bug, size:XS, lgtm

#3064 fix(ui): svg dynamic provider is not working
  keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
  keep-ui/app/(keep)/workflows/builder/editors.tsx
  keep-ui/app/(keep)/workflows/workflow-tile.tsx
  keep-ui/components/ui/DynamicProviderIcon.tsx
  keep-ui/components/ui/index.ts
Labels: Bug, UI, size:L

#3068 chore: add sqs scope to doc
  docs/providers/documentation/amazonsqs-provider.mdx
Labels: Documentation, size:S, lgtm

#3060 feat: Add facets filtering for Incidents
  docs/images/incidents/add_facet_for_incident.png
  docs/incidents/facets.mdx
  docs/mint.json
  keep-ui/app/(keep)/alerts/alert-create-incident-ai-modal.tsx
  keep-ui/app/(keep)/alerts/alert-table-facet-value.tsx
  keep-ui/app/(keep)/incidents/page.tsx
  keep-ui/components/navbar/IncidentLinks.tsx
  keep-ui/features/filter/add-facet-modal.tsx
  keep-ui/features/filter/api.ts
  keep-ui/features/filter/facet-panel-server-side.tsx
  keep-ui/features/filter/facet-value.tsx
  keep-ui/features/filter/facet.tsx
  keep-ui/features/filter/facets-panel.tsx
  keep-ui/features/filter/hooks.tsx
  keep-ui/features/filter/index.ts
  keep-ui/features/filter/models.tsx
  keep-ui/features/incident-list/ui/incident-list.tsx
  keep-ui/utils/hooks/useIncidents.ts
  keep/api/core/cel_to_sql/ast_nodes.py
  keep/api/core/cel_to_sql/cel_ast_converter.py
  keep/api/core/cel_to_sql/properties_mapper.py
  keep/api/core/cel_to_sql/properties_metadata.py
  keep/api/core/cel_to_sql/sql_providers/base.py
  keep/api/core/cel_to_sql/sql_providers/get_cel_to_sql_provider_for_dialect.py
  keep/api/core/cel_to_sql/sql_providers/mysql.py
  keep/api/core/cel_to_sql/sql_providers/postgresql.py
  keep/api/core/cel_to_sql/sql_providers/sqlite.py
  keep/api/core/db.py
  keep/api/core/facets.py
  keep/api/core/incidents.py
  keep/api/models/db/facet.py
  keep/api/models/db/migrations/env.py
  keep/api/models/db/migrations/versions/2025-01-08-19-20_8a4ec08f2d6b.py
  keep/api/models/db/migrations/versions/2025-01-19-10-44_d359baaf0836.py
  keep/api/models/facet.py
  keep/api/routes/incidents.py
  tests/cel_to_sql/cel-to-sql-test-cases.json
  tests/cel_to_sql/test_cel_to_ast.py
  tests/cel_to_sql/test_cel_to_sql.py
Labels: Documentation, Feature, size:XXL, lgtm

#3076 fix: zabbix 7.2
  keep-ui/app/(keep)/providers/provider-form.tsx
  keep/providers/zabbix_provider/zabbix_provider.py
Labels: Provider, size:S

#3072 fix(ui,be): minor bugs on Incidents after facets
  keep-ui/app/(keep)/incidents/page.tsx
  keep-ui/entities/incidents/api/incidents.ts
  keep-ui/features/filter/add-facet-modal.tsx
  keep-ui/features/filter/facet-panel-server-side.tsx
  keep-ui/features/filter/facet.tsx
  keep-ui/features/filter/facets-panel.tsx
  keep-ui/features/incident-list/ui/incident-list.tsx
  keep-ui/features/incident-list/ui/incidents-not-found.tsx
  keep/api/models/facet.py
Labels: Bug, UI, size:L, lgtm

#3078 fix: replace SINGLE_TENANT with DB
  docker-compose-with-auth.yml
  docs/development/getting-started.mdx
Labels: size:S

#3087 fix(pusher): self signed certificate
  keep/api/core/dependencies.py
  pyproject.toml
Labels: Bug, size:S, lgtm

#3084 fix: provider id
  keep/api/routes/alerts.py
  keep/providers/base/base_provider.py
Labels: Provider, size:S, lgtm

#3089 feat(api): add keep.dictget
  examples/workflows/consts_and_dict.yml
  keep/functions/__init__.py
  tests/test_functions.py
Labels: Feature, API, size:L, lgtm

#3096 feat: workflow to create alerts
  examples/workflows/create_alert_in_keep.yml
  keep/providers/keep_provider/keep_provider.py
Labels: Feature, size:M, lgtm

#3090 feat: query graylog
  keep-ui/app/(keep)/incidents/[id]/chat/incident-chat.tsx
  keep/providers/graylog_provider/README.md
  keep/providers/graylog_provider/graylog_provider.py
  keep/providers/zabbix_provider/README.md
Labels: Documentation, Feature, Provider, size:L

#3095 fix: override default username
  keep/api/core/db_on_start.py
Labels: size:M, lgtm

#3098 feat(victoriametrics): support both vmalert and vmmetrics
  examples/workflows/create_alert_from_vm_metric.yml
  keep/contextmanager/contextmanager.py
  keep/providers/victoriametrics_provider/victoriametrics_provider.py
  keep/step/step.py
  poetry.lock
  pyproject.toml
Labels: Feature, Provider, size:L, lgtm

#3105 docs: Added instructions for installing new Keep from scratch in docker
  docs/deployment/docker.mdx
Labels: Documentation, size:M, lgtm

#3107 fix(vm): skip validate scopes
  keep/providers/victoriametrics_provider/victoriametrics_provider.py
  pyproject.toml
Labels: Bug, size:S, lgtm

#3110 docs(fix): error of missing highline code mark
  docs/deployment/docker.mdx
Labels: Documentation, size:XS, lgtm

#3117 chore(deps): remove python-jose
  poetry.lock
  pyproject.toml
Labels: Dependencies, size:XS

#3119 feat(api): customize fingerprint
  examples/workflows/create_alert_from_vm_metric.yml
  keep/providers/keep_provider/keep_provider.py
Labels: Feature, API, size:M, lgtm

#3123 chore(deps): bump asteval from 0.9.33 to 1.0.6
  poetry.lock
  pyproject.toml
Labels: Dependencies, size:XS

#3128 fix(api): otelTraceId
  keep/api/logging.py
Labels: Bug, size:XS

#3130 fix(api): 'NoneType' object is not iterable
  keep/workflowmanager/workflowmanager.py
Labels: Bug, size:XS, lgtm

#3102 feat: enhance scope validation in opsgenie
  docs/images/opsgenie-provider_1.png
  docs/images/opsgenie-provider_2.png
  docs/images/opsgenie-provider_3.png
  docs/images/opsgenie-provider_4.png
  docs/providers/documentation/opsgenie-provider.mdx
  keep/providers/opsgenie_provider/opsgenie_provider.py
Labels: Enhancement, Provider, 🙋 Bounty claim, size:M

#3140 feat: trigger workflow on manual status change
  keep/api/routes/alerts.py
  keep/api/tasks/process_event_task.py
  keep/api/tasks/process_topology_task.py
  keep/functions/__init__.py
Labels: size:M, lgtm

#3132 feat(slack): add reactions
  keep/providers/slack_provider/slack_provider.py
Labels: Feature, Provider, size:M

#3122 feat(ui): add `pre` tag to description
  keep-ui/app/(keep)/alerts/alert-sidebar.tsx
Labels: size:XS, lgtm

#3145 fix: fingerprint docs wrong ling
  keep-ui/app/(keep)/alerts/alert-sidebar.tsx
  keep-ui/entities/alerts/ui/AlertName/AlertName.tsx
Labels: UI, size:S, lgtm

#3148 docs: example wf, pull wf from HTTP
  examples/workflows/update_workflows_from_http.yml
  keep/providers/keep_provider/keep_provider.py
Labels: Feature, size:S

#3134 fix: AI workflow examples
  examples/workflows/conditionally_run_if_ai_says_so.yaml
  examples/workflows/enrich_using_structured_output_from_openai.yaml
Labels: size:S

#3151 feat(ui): show provider id in provider form
  examples/workflows/slack-message-reaction.yml
  keep-ui/app/(keep)/providers/provider-form.tsx
Labels: Feature, UI, size:M

#3153 fix(ui): timeline endless loading when no alerts
  .github/workflows/auto-resolve-keep.yml
  keep-ui/app/(keep)/incidents/[id]/chat/incident-chat.tsx
  keep-ui/app/(keep)/incidents/[id]/incident-layout-client.tsx
  keep-ui/app/(keep)/incidents/[id]/timeline/incident-timeline.tsx
  keep-ui/components/ui/EmptyStateCard.tsx
  keep-ui/components/ui/ResizableColumns.tsx
Labels: Bug, UI, size:S, lgtm

#3154 feat: checkly provider
  README.md
  docs/images/checkly-provider_1.png
  docs/images/checkly-provider_10.png
  docs/images/checkly-provider_11.png
  docs/images/checkly-provider_12.png
  docs/images/checkly-provider_2.png
  docs/images/checkly-provider_3.png
  docs/images/checkly-provider_4.png
  docs/images/checkly-provider_5.png
  docs/images/checkly-provider_6.png
  docs/images/checkly-provider_7.png
  docs/images/checkly-provider_8.png
  docs/images/checkly-provider_9.png
  docs/mint.json
  docs/providers/documentation/checkly-provider.mdx
  docs/providers/overview.mdx
  keep-ui/public/icons/checkly-icon.png
  keep/providers/checkly_provider/__init__.py
  keep/providers/checkly_provider/alerts_mock.py
  keep/providers/checkly_provider/checkly_provider.py
Labels: Documentation, Feature, Provider, 🙋 Bounty claim, size:L, hacktoberfest-accepted

#3158 fix(docs): readme broken
  README.md
  docs/providers/documentation/checkly-provider.mdx
Labels: Documentation, size:S, lgtm

#3161 fix(ui): RCA and Group By Value
  examples/workflows/slack-message-reaction.yml
  keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
  keep-ui/components/ui/RootCauseAnalysis.tsx
  keep/api/routes/workflows.py
Labels: Bug, UI, size:S, lgtm

#3167 fix(api): checkmk service
  keep/providers/checkmk_provider/checkmk_provider.py
Labels: Bug, API, size:XS, lgtm

#3171 feat(clickhouse): optional SSL verification
  keep/providers/clickhouse_provider/clickhouse_provider.py
  pyproject.toml
Labels: Feature, Provider, size:M

#3174 feat(ui): workflow yaml editor
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-detail-page.tsx
  keep-ui/entities/workflows/model/useWorkflowActions.ts
  keep-ui/package-lock.json
  keep-ui/package.json
  keep-ui/shared/ui/YAMLCodeblock/ui/MonacoYAMLEditor.tsx
  keep-ui/utils/hooks/useWorkflowExecutions.ts
Labels: Feature, UI, size:L, lgtm

#3177 feat: recursive render
  keep/iohandler/iohandler.py
  tests/test_iohandler.py
Labels: Feature, size:L

#3178 feat(api): workflows cache
  keep/api/observability.py
  keep/parser/parser.py
  keep/workflowmanager/workflowmanager.py
  pyproject.toml
Labels: Feature, API, size:M, lgtm

#3188 fix(ui): missing columns in history
  keep-ui/app/(keep)/alerts/alert-history-charts.tsx
  keep-ui/app/(keep)/alerts/alert-history.tsx
  keep-ui/app/(keep)/alerts/alert-menu.tsx
Labels: Bug, UI, size:M, lgtm

#3180 feat: deepseek provider
  README.md
  docs/mint.json
  docs/providers/documentation/deepseek-provider.mdx
  docs/providers/overview.mdx
  examples/workflows/enrich_using_structured_output_from_deepseek.yaml
  keep-ui/public/icons/deepseek-icon.png
  keep/providers/deepseek_provider/__init__.py
  keep/providers/deepseek_provider/deepseek_provider.py
Labels: Documentation, Feature, Provider, size:L

#3194 fix: don't render providers
  keep/iohandler/iohandler.py
  pyproject.toml
  tests/test_alert_evaluation.py
  tests/test_iohandler.py
Labels: Bug, size:M, lgtm

#3195 fix: iohandler tests
  keep/api/routes/incidents.py
  tests/test_alert_evaluation.py
  tests/test_iohandler.py
Labels: Bug, size:L

#3198 feat(ui): allow nested labels on grouped by
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationForm.tsx
Labels: UI, size:S, lgtm

#3185 fix: Add incident resolution logic for enriched alerts
  keep/api/routes/alerts.py
  tests/test_incidents.py
Labels: Bug, Incident, size:M, lgtm

#3200 fix(checkmk): last received
  keep/providers/checkmk_provider/checkmk_provider.py
  keep/providers/checkmk_provider/webhook-keep.py
Labels: Bug, Provider, size:M, lgtm

#3206 feat(api): eks provider
  docs/mint.json
  docs/providers/documentation/eks-provider.mdx
  docs/providers/overview.mdx
  examples/workflows/eks_advanced.yml
  examples/workflows/eks_basic.yml
  keep-ui/public/icons/eks-icon.png
  keep/iohandler/iohandler.py
  keep/providers/eks_provider/eks_provider.py
Labels: Documentation, Feature, Provider, size:XL, lgtm

#3209 fix(api): preset tabs
  keep/api/routes/preset.py
Labels: API, Incident, size:XS

#3211 fix(checkmk): long_date_time
  keep/providers/checkmk_provider/checkmk_provider.py
Labels: Bug, Provider, size:S

#3204 feat(pagerduty): flexibility in events
  .github/workflows/test-pr.yml
  keep/parser/parser.py
  keep/providers/pagerduty_provider/pagerduty_provider.py
Labels: Feature, Provider, size:L, lgtm

#3214 feat(api): gke improvements
  keep/providers/gke_provider/gke_provider.py
  pyproject.toml
Labels: Feature, API, size:XL, lgtm

#3215 fix: renaming for cloud run
  keep/api/logging.py
  keep/api/observability.py
  keep/providers/checkmk_provider/checkmk_provider.py
Labels: size:S, lgtm

#3219 chore: more otel improvements
  keep/api/observability.py
Labels: size:XS

#3222 feat: kibana 8.16.0
  keep/providers/kibana_provider/kibana_provider.py
  pyproject.toml
Labels: Feature, Provider, size:L, lgtm

#3217 feat: add grafana tempo topology
  docs/providers/documentation/grafana-provider.mdx
  keep/providers/argocd_provider/argocd_provider.py
  keep/providers/grafana_provider/README.md
  keep/providers/grafana_provider/grafana_provider.py
Labels: Feature, Provider, size:L, lgtm

#3225 fix: incident is not closing automatically
  keep/api/models/db/migrations/versions/2025-01-16-14-00_e3f33e571c3c.py
  keep/api/routes/alerts.py
Labels: Bug, size:XS, lgtm

#3184 fix: better performance in dedup process
  keep/api/alert_deduplicator/alert_deduplicator.py
  keep/api/core/db.py
  keep/api/tasks/process_event_task.py
Labels: Bug, size:M, lgtm

#3169 feat: Provider Health functionality
  keep-ui/app/(health)/health/modal.tsx
  keep-ui/app/(health)/health/page.tsx
  keep-ui/app/(health)/layout.tsx
  keep-ui/app/(keep)/ai/model.ts
  keep-ui/app/(keep)/alerts/alert-create-incident-ai-modal.tsx
  keep-ui/app/(keep)/alerts/alert-table-facet-value.tsx
  keep-ui/app/(keep)/alerts/alerts-rules-builder.tsx
  keep-ui/app/(keep)/deduplication/DeduplicationPlaceholder.tsx
  keep-ui/app/(keep)/deduplication/DeduplicationTable.tsx
  keep-ui/app/(keep)/incidents/[id]/chat/incident-chat.tsx
  keep-ui/app/(keep)/incidents/page.tsx
  keep-ui/app/(keep)/providers/page.client.tsx
  keep-ui/app/(keep)/providers/provider-form.tsx
  keep-ui/app/(keep)/providers/providers-tiles.tsx
  keep-ui/app/(keep)/providers/providers.tsx
  keep-ui/app/(keep)/settings/settings.client.tsx
  keep-ui/app/(keep)/topology/ui/map/service-node.tsx
  keep-ui/app/(keep)/workflows/workflow-tile.tsx
  keep-ui/app/api/healthcheck/route.ts
  keep-ui/app/frigade-provider.tsx
  keep-ui/middleware.ts
  keep-ui/shared/api/ApiClient.ts
  keep-ui/shared/lib/hooks/useApi.tsx
  keep-ui/types/auth.d.ts
  keep-ui/utils/hooks/useProviders.ts
  keep/api/models/provider.py
  keep/api/routes/providers.py
  keep/providers/base/base_provider.py
  keep/providers/datadog_provider/datadog_provider.py
  keep/providers/providers_factory.py
  keep/providers/providers_service.py
Labels: Feature, Provider, size:XL

#3239 fix: migration
  keep/api/models/db/migrations/versions/2025-01-16-14-00_e3f33e571c3c.py
Labels: size:XS

#3242 feat(api): kibana 8.16.0
  keep/providers/kibana_provider/kibana_provider.py
  pyproject.toml
Labels: API, size:M, lgtm

#3238 fix: error processing event
  keep/api/bl/maintenance_windows_bl.py
  tests/test_maintenance_windows_bl.py
Labels: Bug, size:M, lgtm

#3245 feat(api): kibana SIEM
  keep/providers/kibana_provider/kibana_provider.py
  pyproject.toml
Labels: Feature, size:M, lgtm

#3247 fix(api): metrics convention
  keep/api/routes/metrics.py
  pyproject.toml
Labels: Bug, API, size:XS

#3252 chore(api): better wf logs
  keep/api/routes/alerts.py
  keep/api/routes/workflows.py
  keep/providers/providers_factory.py
  keep/step/step.py
  keep/workflowmanager/workflowscheduler.py
  tests/test_metrics.py
Labels: API, size:M, lgtm
