Repository keephq/keep, pull requests merged in 2025-05, with the labels that each got.

#4664 fix: delete workflows that are not provisioned anymore
  keep/api/core/db.py
  keep/api/models/workflow.py
  keep/parser/parser.py
  keep/workflowmanager/workflowstore.py
  tests/provision/workflows_4/console_example.yml
  tests/test_workflow_execution.py
  tests/test_workflowstore.py
Labels: Bug, size:L, lgtm

#4672 chore: bump version `0.42.2`
  .gitignore
  pyproject.toml
Labels: Dependencies, size:XS, lgtm

#4675 fix: graylog and zabbix provider verify ssl switch
  docs/snippets/providers/graylog-snippet-autogenerated.mdx
  docs/snippets/providers/zabbix-snippet-autogenerated.mdx
  keep-ui/entrypoint.sh
  keep/iohandler/iohandler.py
  keep/providers/graylog_provider/graylog_provider.py
  keep/providers/zabbix_provider/zabbix_provider.py
  pyproject.toml
Labels: Provider, size:M, lgtm

#4677 fix: 4238 bug zabbix provider is not compatible with zabbix 60 and zabbix 62
  keep/providers/kubernetes_provider/kubernetes_provider.py
  keep/providers/zabbix_provider/zabbix_provider.py
  pyproject.toml
Labels: Bug, size:M, lgtm

#4682 fix: pagerduty with `unkown` title
  keep/providers/pagerduty_provider/pagerduty_provider.py
Labels: Bug, Provider, size:S, lgtm

#4685 fix: Fix bug when clicking on severity/status 0 matched option showed all alerts
  keep-ui/features/filter/build-cel.test.ts
  keep-ui/features/filter/build-cel.ts
Labels: Bug, UI, size:M, lgtm

#4686 fix: Use INCIDENT_TIME_ISO instead of INCIDENT_TIME for site24x7 provider
  keep/providers/site24x7_provider/site24x7_provider.py
Labels: Bug, size:XS, lgtm

#4688 chore: log failing parsed events
  keep/api/routes/alerts.py
  keep/providers/kibana_provider/kibana_provider.py
Labels: size:S, lgtm

#4689 fix: kibana name
  keep/providers/kibana_provider/kibana_provider.py
Labels: Bug, size:XS

#4693 feat: grafana datasource-managed alerts
  keep/providers/grafana_provider/grafana_provider.py
  pyproject.toml
Labels: Feature, Provider, size:XL, lgtm

#4695 feat: show provider version
  keep-ui/app/(keep)/providers/provider-tile.tsx
  keep-ui/shared/api/providers.ts
  keep/api/models/db/migrations/versions/2025-05-04-15-02_eddcb77eb6f3.py
  keep/api/models/db/provider.py
  keep/api/models/provider.py
  keep/providers/base/base_provider.py
  keep/providers/grafana_provider/grafana_provider.py
  keep/providers/providers_factory.py
  keep/providers/providers_service.py
Labels: Feature, Provider, size:M, lgtm

#4697 fix: test wf provisioning
  keep/api/core/db.py
  tests/provision/workflows_4/console_example.yml
  tests/test_workflow_execution.py
Labels: size:M

#4577 feat: workflow trigger with cel expression
  docs/snippets/providers/cloudwatch-snippet-autogenerated.mdx
  docs/snippets/providers/console-snippet-autogenerated.mdx
  docs/snippets/providers/datadog-snippet-autogenerated.mdx
  docs/snippets/providers/newrelic-snippet-autogenerated.mdx
  docs/snippets/providers/opsgenie-snippet-autogenerated.mdx
  docs/snippets/providers/prometheus-snippet-autogenerated.mdx
  docs/snippets/providers/slack-snippet-autogenerated.mdx
  docs/workflows/examples/create-servicenow-tickets.mdx
  docs/workflows/examples/highsev.mdx
  docs/workflows/examples/update-servicenow-tickets.mdx
  docs/workflows/syntax/triggers.mdx
  examples/workflows/complex-conditions-cel.yml
  examples/workflows/multi-condition-cel.yml
  examples/workflows/opsgenie-create-alert-cel.yml
  examples/workflows/pattern-matching-cel.yml
  examples/workflows/slack_basic_cel.yml
  keep-ui/app/(keep)/workflows/workflow-tile.tsx
  keep-ui/entities/workflows/lib/__tests__/validation.test.ts
  keep-ui/entities/workflows/lib/getTriggerDescription.ts
  keep-ui/entities/workflows/lib/parser.ts
  keep-ui/entities/workflows/lib/validation.ts
  keep-ui/entities/workflows/model/schema.ts
  keep-ui/entities/workflows/model/yaml.schema.ts
  keep-ui/entities/workflows/ui/NodeTriggerIcon.tsx
  keep-ui/entities/workflows/ui/WorkflowTriggerBadge.tsx
  keep-ui/features/cel-input/cel-input.tsx
  keep-ui/features/presets/create-or-update-preset/ui/alerts-count-badge.tsx
  keep-ui/features/presets/create-or-update-preset/ui/create-or-update-preset-form.tsx
  keep-ui/features/presets/presets-manager/ui/alerts-rules-builder.tsx
  keep-ui/features/workflows/ai-assistant/ui/AddTriggerUI.tsx
  keep-ui/features/workflows/ai-assistant/ui/StepPreview.tsx
  keep-ui/features/workflows/ai-assistant/ui/WorkflowBuilderChat.tsx
  keep-ui/features/workflows/builder/lib/utils.tsx
  keep-ui/features/workflows/builder/ui/Editor/TriggerEditor.tsx
  keep-ui/features/workflows/builder/ui/WorkflowEdge.tsx
  keep-ui/features/workflows/builder/ui/WorkflowNode.tsx
  keep-ui/features/workflows/builder/ui/debug-settings.ts
  keep-ui/shared/api/workflows.ts
  keep-ui/shared/lib/server/getConfig.ts
  keep-ui/shared/ui/MonacoCELEditor/editor.scss
  keep-ui/types/internal-config.ts
  keep/api/core/db.py
  keep/workflowmanager/workflowmanager.py
  keep/workflowmanager/workflowstore.py
  pyproject.toml
  tests/test_workflow_filters.py
Labels: Documentation, Feature, size:L, lgtm

#4534 feat: Toggle noise reduction features via tenant configuration
  keep-ui/components/navbar/NoiseReductionLinks.tsx
Labels: Documentation, Feature, UI, size:L

#4633 fix: provisioned provider should update with the latest configurations
  keep/providers/providers_service.py
  tests/test_provider_reprovisioning.py
Labels: Bug, Provider, size:L, lgtm

#4707 chore(deps): add awscli
  poetry.lock
  pyproject.toml
Labels: Dependencies, size:XS, lgtm

#4646 feat: Add support for displaying incident details in alerts
  keep-ui/app/(keep)/incidents/[id]/alerts/incident-alert-actions.tsx
  keep-ui/entities/alerts/model/types.ts
  keep-ui/features/alerts/alert-detail-sidebar/ui/alert-sidebar.tsx
  keep-ui/widgets/alerts-table/lib/alert-table-utils.tsx
  keep/api/core/elastic.py
  keep/api/utils/enrichment_helpers.py
Labels: Feature, UI, size:M

#4670 fix: labels namespace filtering in rules not working
  keep-ui/app/(keep)/rules/CorrelationSidebar/AlertsFoundBadge.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationSidebarBody.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/RuleFields.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/convert-cel-ast-to-query-builder-ast/convert-cel-ast-to-query-builder-ast.function.test.ts
  keep-ui/app/(keep)/rules/CorrelationSidebar/convert-cel-ast-to-query-builder-ast/convert-cel-ast-to-query-builder-ast.function.ts
  keep-ui/app/(keep)/rules/CorrelationSidebar/index.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/useMatchingAlerts.ts
  keep-ui/app/(keep)/rules/CorrelationTable.tsx
  keep-ui/app/(keep)/rules/FormattedQueryCell.tsx
  keep-ui/app/(keep)/rules/flatten-cel-ast.ts
  keep-ui/entities/alerts/model/useAlerts.ts
  keep-ui/features/cel-input/cel-input.tsx
  keep-ui/shared/ui/MonacoCELEditor/monaco-cel-editor.tsx
  keep-ui/shared/ui/MonacoCELEditor/validation-hook.ts
  keep-ui/utils/cel-ast.ts
  keep-ui/utils/hooks/useRules.ts
  keep/api/core/alerts.py
  keep/api/core/cel_to_sql/ast_nodes.py
  keep/api/core/cel_to_sql/cel_ast_converter.py
  keep/api/core/cel_to_sql/properties_mapper.py
  keep/api/core/cel_to_sql/properties_metadata.py
  keep/api/core/cel_to_sql/sql_providers/base.py
  keep/api/core/cel_to_sql/sql_providers/mysql.py
  keep/api/core/cel_to_sql/sql_providers/postgresql.py
  keep/api/core/cel_to_sql/sql_providers/sqlite.py
  keep/api/core/facets.py
  keep/api/core/incidents.py
  keep/api/routes/rules.py
  tests/cel_to_sql/cel-to-sql-test-cases.json
  tests/cel_to_sql/test_cel_to_ast.py
  tests/cel_to_sql/test_cel_to_sql.py
  tests/cel_to_sql/test_order_by_exp.py
Labels: Bug, UI, Correlation, size:XXL, lgtm

#4701 fix: Can't query unicode characters like ± using CEL / Facets
  keep/api/core/cel_to_sql/cel_ast_converter.py
  pyproject.toml
  tests/cel_to_sql/test_cel_to_ast.py
Labels: Bug, size:S, lgtm

#4708 fix: Fix incorrectly set value to monaco editor in CelInput
  keep-ui/shared/ui/MonacoCELEditor/monaco-cel-editor.tsx
  pyproject.toml
Labels: Bug, UI, size:XS, lgtm

#4714 fix: k8s failed to run `list_namespaced_event`
  keep/providers/kubernetes_provider/kubernetes_provider.py
  pyproject.toml
Labels: Bug, size:M, lgtm

#4716 feat(auth): keycloak multi org
  .gitignore
  ee/identitymanager/identity_managers/keycloak/keycloak_authverifier.py
  ee/identitymanager/identity_managers/keycloak/keycloak_identitymanager.py
  keep-ui/auth.config.ts
  keep-ui/auth.ts
  keep-ui/package-lock.json
  keep-ui/package.json
  keep-ui/types/auth.d.ts
  keep/api/core/db.py
  keycloak/KEYCLOAK_LDAP.md
  keycloak/docker-compose.yaml
  keycloak/jsons/group-claim.json
  keycloak/jsons/group-mapper.json
  keycloak/jsons/tenant-ids-js-mapper.json
  keycloak/ldif/ldap_orgs.ldif
  pyproject.toml
Labels: Feature, Provider, size:XL, lgtm

#4718 fix: fail safely when CEL conversion fails in wf manager
  keep/workflowmanager/workflowmanager.py
  pyproject.toml
  tests/test_workflow_filters.py
Labels: Bug, size:M, lgtm

#4720 fix: CEL query with dictionary like property access work incorrectly
  keep/api/core/cel_to_sql/cel_ast_converter.py
  tests/cel_to_sql/test_cel_to_ast.py
Labels: Bug, size:L, lgtm

#4727 fix: keycloak multiorg
  ee/identitymanager/identity_managers/keycloak/keycloak_authverifier.py
  keycloak/KEYCLOAK_LDAP.md
  keycloak/ldif/ldap_orgs_new.ldif
  pyproject.toml
Labels: Documentation, Feature, size:L, lgtm

#4729 fix(typo): cleanup for consistency with official naming
  docs/providers/documentation/elastic-provider.mdx
  keep/providers/elastic_provider/elastic_provider.py
  scripts/migrate_to_elastic.py
  tests/conftest.py
Labels: Documentation, size:S, lgtm

#4735 fix: oauth2 proxy with user/pass auth
  keep/identitymanager/identity_managers/oauth2proxy/oauth2proxy_authverifier.py
  pyproject.toml
Labels: size:XS, lgtm

#4741 fix: provisioning providers with no auth config
  keep/providers/providers_service.py
  pyproject.toml
  tests/conftest.py
  tests/test_provisioning.py
Labels: Bug, size:M, lgtm

#4745 fix: slack oauth2 provider name
  keep/providers/slack_provider/slack_provider.py
  pyproject.toml
Labels: Bug, size:XS

#4751 fix: slack oauth2 no_auth error
  keep/providers/slack_provider/slack_provider.py
Labels: Provider, size:M, lgtm

#4756 fix: `psycopg2.errors.NotNullViolation` while updating workflows
  keep/api/core/db.py
Labels: Bug, size:M, lgtm

#4760 chore: loki provider SSL verification
  docs/snippets/providers/grafana_loki-snippet-autogenerated.mdx
  keep/identitymanager/identity_managers/oauth2proxy/oauth2proxy_authverifier.py
  keep/providers/grafana_loki_provider/grafana_loki_provider.py
  keep/providers/slack_provider/slack_provider.py
  pyproject.toml
Labels: Provider, size:L

#4709 fix: Replace alerts_count calculation with subquery and add recalculation migration
  keep/api/core/db.py
  keep/api/models/db/migrations/versions/2025-05-06-13-09_7b687c555318.py
  tests/test_incidents.py
Labels: Bug, size:L, lgtm

#4763 fix: incident is UUID
  keep/api/models/db/migrations/versions/2025-05-06-13-09_7b687c555318.py
Labels: Bug, size:S, lgtm

#4748 fix: disappearing workflow inputs in UI builder
  keep-ui/entities/workflows/lib/__tests__/parser.test.ts
  keep-ui/entities/workflows/lib/parser.ts
  keep-ui/entities/workflows/lib/yaml-utils.ts
  keep-ui/entities/workflows/model/schema.ts
  keep-ui/entities/workflows/model/yaml.schema.ts
  keep-ui/entities/workflows/model/yaml.types.ts
  keep-ui/entities/workflows/ui/WorkflowInputFields.tsx
  keep-ui/features/workflows/manual-run-workflow/ui/manual-run-workflow-modal.tsx
  keep-ui/utils/hooks/useWorkflowRun.ts
  keep-ui/widgets/workflow-builder/__tests__/workflow-builder.test.tsx
Labels: Bug, UI, size:L, lgtm

#4768 fix: Fix hidden "Enable SSL verification" for Grafana Loki provider
  keep/providers/grafana_loki_provider/grafana_loki_provider.py
  pyproject.toml
Labels: size:XS, lgtm

#4724 fix: check yaml editor has unsaved changes on click "Run now"
  keep-ui/app/(keep)/alerts/[id]/ui/alerts.tsx
  keep-ui/app/(keep)/incidents/[id]/incident-header.tsx
  keep-ui/app/(keep)/incidents/[id]/workflows/incident-workflow-empty.tsx
  keep-ui/app/(keep)/layout.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-detail-header.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-detail-page.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-versions.tsx
  keep-ui/app/(keep)/workflows/__tests__/workflows.client.test.tsx
  keep-ui/app/(keep)/workflows/workflow-tile.tsx
  keep-ui/entities/workflows/lib/extractWorkflowYamlDependencies.ts
  keep-ui/entities/workflows/lib/yaml-utils.ts
  keep-ui/entities/workflows/model/useWorkflowsV2.ts
  keep-ui/entities/workflows/model/workflow-store.ts
  keep-ui/entities/workflows/model/workflow-yaml-editor-store.ts
  keep-ui/entities/workflows/model/yaml.schema.ts
  keep-ui/entities/workflows/ui/WorkflowAlertIncidentDependenciesForm.tsx
  keep-ui/entities/workflows/ui/WorkflowInputFields.tsx
  keep-ui/features/incidents/incident-list/ui/incidents-table.tsx
  keep-ui/features/workflow-execution-results/ui/WorkflowExecutionLogs.tsx
  keep-ui/features/workflows/ai-assistant/ui/WorkflowBuilderChat.tsx
  keep-ui/features/workflows/builder/ui/Editor/StepEditor.tsx
  keep-ui/features/workflows/builder/ui/WorkflowNode.tsx
  keep-ui/features/workflows/manual-run-workflow/index.ts
  keep-ui/features/workflows/manual-run-workflow/model/WorkflowModalContext.tsx
  keep-ui/features/workflows/manual-run-workflow/model/types.ts
  keep-ui/features/workflows/manual-run-workflow/model/useWorkflowRun.ts
  keep-ui/features/workflows/manual-run-workflow/ui/WorkflowInputsForm.tsx
  keep-ui/features/workflows/manual-run-workflow/ui/WorkflowUnsavedChangesForm.tsx
  keep-ui/features/workflows/manual-run-workflow/ui/manual-run-workflow-modal.tsx
  keep-ui/features/workflows/manual-run-workflow/ui/workflow-run-with-alert-modal.tsx
  keep-ui/features/workflows/test-run/ui/workflow-test-run-button.tsx
  keep-ui/shared/lib/buildNestedObject.ts
  keep-ui/shared/ui/WorkflowYAMLEditor/ui/WorkflowYAMLEditorStandalone.tsx
  keep-ui/utils/hooks/useWorkflowRun.ts
  keep-ui/widgets/workflow-builder/workflow-builder-widget.tsx
  keep-ui/widgets/workflow-builder/workflow-builder.tsx
  tests/e2e_tests/test_end_to_end.py
  tests/e2e_tests/workflow-inputs-alert.yaml
  tests/e2e_tests/workflow-inputs.yaml
Labels: Bug, UI, size:XXL

#4725 feat: Improve user interaction with workflow templates
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-overview.tsx
  keep-ui/app/(keep)/workflows/__tests__/existing-workflows-state.test.tsx
  keep-ui/app/(keep)/workflows/create-workflow-modal.tsx
  keep-ui/app/(keep)/workflows/existing-workflows-state.tsx
  keep-ui/app/(keep)/workflows/no-workflows-state.tsx
  keep-ui/app/(keep)/workflows/page.tsx
  keep-ui/app/(keep)/workflows/upload-workflows-modal.tsx
  keep-ui/app/(keep)/workflows/workflow-templates/index.ts
  keep-ui/app/(keep)/workflows/workflow-templates/workflow-template-card.tsx
  keep-ui/app/(keep)/workflows/workflow-templates/workflow-templates.tsx
  keep-ui/app/(keep)/workflows/workflows-steps.tsx
  keep-ui/app/(keep)/workflows/workflows-templates.tsx
  keep-ui/app/(keep)/workflows/workflows.page.tsx
  keep-ui/components/ui/Modal.tsx
  keep-ui/entities/workflows/lib/use-query-workflow-template.ts
  keep-ui/entities/workflows/model/useWorkflowsV2.ts
  keep-ui/entities/workflows/model/workflowKeys.ts
  keep/api/routes/workflows.py
  keep/workflowmanager/workflowstore.py
  tests/e2e_tests/test_end_to_end.py
Labels: Feature, UI, size:XXL

#4733 fix: Change source/services facets behavior for Incident
  keep/api/core/cel_to_sql/sql_providers/base.py
  keep/api/core/cel_to_sql/sql_providers/mysql.py
  keep/api/core/cel_to_sql/sql_providers/postgresql.py
  keep/api/core/cel_to_sql/sql_providers/sqlite.py
  keep/api/core/facets.py
  keep/api/core/incidents.py
  tests/cel_to_sql/cel-to-sql-test-cases.json
  tests/cel_to_sql/test_cel_to_sql.py
Labels: Bug, size:XL

#4781 fix: cant save a valid CEL expression
  keep-ui/features/presets/presets-manager/ui/alerts-rules-builder.tsx
Labels: Bug, size:M

#4783 fix: use 0.01 for 0s executions and use log scale in wf graphs
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-overview.tsx
  keep-ui/app/(keep)/workflows/workflow-graph.tsx
  keep-ui/app/(keep)/workflows/workflow-utils.ts
Labels: Bug, size:L, lgtm

#4793 feat: Add threshold support for Correlation Rule
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationForm.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationSidebarBody.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/index.tsx
  keep-ui/app/(keep)/rules/CorrelationSidebar/types.ts
  keep-ui/utils/hooks/useRules.ts
  keep/api/core/db.py
  keep/api/models/db/migrations/versions/2025-05-15-00-34_fcef2c58b21c.py
  keep/api/models/db/rule.py
  keep/api/routes/rules.py
  keep/rulesengine/rulesengine.py
  tests/test_rules_engine.py
Labels: Feature, UI, Correlation, size:L

#4761 feat: add arithmetic operations to keep built in functions
  docs/workflows/syntax/functions.mdx
  keep/functions/__init__.py
  tests/test_functions.py
  tests/test_iohandler.py
Labels: Documentation, Feature, size:L

#4704 docs: update required Zabbix scopes
  docs/images/zabbix_role.png
  docs/providers/documentation/zabbix-provider.mdx
  docs/snippets/providers/zabbix-snippet-autogenerated.mdx
  keep/providers/zabbix_provider/zabbix_provider.py
Labels: Documentation, Provider, size:L, lgtm

#4680 feat: Pagerduty Provider: incident enrichments #4663
  keep/providers/pagerduty_provider/pagerduty_provider.py
Labels: Feature, Provider, size:XS

#4770 fix: Fixed recalculate alerts_count for incidents migration
  keep/api/models/db/migrations/versions/2025-05-06-13-09_7b687c555318.py
  keep/api/models/db/migrations/versions/2025-05-12-17-49_c2f78c69e9cf.py
Labels: Bug, size:M

#4798 fix: merge migrations heads
  keep/api/models/db/migrations/versions/2025-05-15-14-18_bedb5f07417b.py
Labels: size:S

#4811 fix: Revert "feat: Pagerduty Provider: incident enrichments #4663"
  keep/providers/pagerduty_provider/pagerduty_provider.py
Labels: size:XS

#4820 feat: Make elastic index refresh strategy configurable via env variable
  keep/api/core/elastic.py
Labels: Feature, size:XS, lgtm

#4815 feat: Add slack message with attachment and updates workflow example
  docs/snippets/providers/slack-snippet-autogenerated.mdx
  examples/workflows/slack_message_update.yml
Labels: Feature, size:M, lgtm

#4805 fix: Slack oAuth handling fixes
  keep/providers/slack_provider/slack_provider.py
Labels: size:S, lgtm

#4801 fix: workflow-graph caused by type: "linear"
  keep-ui/app/(keep)/workflows/workflow-graph.tsx
Labels: Bug, UI, size:XS, lgtm

#4810 fix(mysql): client commit when insert/update/delete
  docs/workflows/syntax/functions.mdx
  keep-ui/app/(keep)/incidents/[id]/chat/incident-chat.tsx
  keep-ui/package-lock.json
  keep-ui/package.json
  keep/providers/mysql_provider/mysql_provider.py
Labels: Provider, size:L, lgtm

#4826 fix: permissions on `cli.py`
  keep/cli/cli.py
  pyproject.toml
Labels: CLI, size:S, lgtm

#4827 fix: delete_user
  keep/identitymanager/identity_managers/oauth2proxy/oauth2proxy_identitymanager.py
Labels: Bug, size:XS, lgtm

#4824 fix: handle nested object fields in alerts table widget
  keep-ui/app/(keep)/dashboard/widget-types/preset/widget-alerts-table.tsx
  keep-ui/shared/lib/__tests__/object-utils.test.ts
  keep-ui/shared/lib/object-utils.ts
  keep-ui/widgets/alerts-table/lib/alert-table-utils.tsx
Labels: Bug, size:L, lgtm

#4818 fix: Catch also IntegrityError, StaleDataError in retry_on_db_error
  keep/api/core/db.py
Labels: Bug, size:XS, lgtm

#4831 chore: remove wip workflow (kubernetes)
  docs/snippets/providers/kubernetes-snippet-autogenerated.mdx
  docs/snippets/providers/prometheus-snippet-autogenerated.mdx
  docs/snippets/providers/slack-snippet-autogenerated.mdx
  examples/workflows/kubernetes.yml
Labels: Bug, size:L, lgtm

#4728 feat: Add Icinga2 Provider to Push Monitoring Alerts from Icinga2 to Keep
  README.md
  docs/mint.json
  docs/providers/documentation/icinga2-provider.mdx
  docs/providers/overview.mdx
  docs/snippets/providers/icinga2-snippet-autogenerated.mdx
  keep-ui/public/icons/icinga2-icon.png
  keep/providers/icinga2_provider/icinga2_provider.py
Labels: Documentation, Feature, Provider, 🙋 Bounty claim, size:L, lgtm, hacktoberfest-accepted

#4835 fix: alert evaluation
  keep/api/core/db.py
  keep/api/core/db_utils.py
  keep/providers/keep_provider/keep_provider.py
  pyproject.toml
  tests/test_alert_evaluation.py
  tests/test_alert_tenrary.py
  tests/test_workflows.py
Labels: Bug, size:L, lgtm

#4838 feat: wf alert postgres
  keep/providers/keep_provider/keep_provider.py
  pyproject.toml
  tests/test_workflows.py
Labels: Feature, size:L, lgtm

#4848 fix: catch no origin in PD
  keep/providers/pagerduty_provider/pagerduty_provider.py
  pyproject.toml
Labels: Bug, Provider, size:S, lgtm

#4832 fix: last executions in get_all_workflows_with_last_execution
  keep-ui/shared/api/workflows.ts
  keep/api/core/workflows.py
  keep/api/routes/workflows.py
  keep/workflowmanager/workflowstore.py
  tests/test_workflow_execution.py
Labels: Bug, API, size:L

#4843 chore: Add unit tests for shared lib utils and relocate buildNestedObject
  keep-ui/entities/workflows/ui/WorkflowAlertIncidentDependenciesForm.tsx
  keep-ui/features/workflows/manual-run-workflow/ui/workflow-run-with-alert-modal.tsx
  keep-ui/shared/lib/__tests__/getIconForStatusString.test.tsx
  keep-ui/shared/lib/__tests__/logs-utils.test.ts
  keep-ui/shared/lib/__tests__/object-utils.test.ts
  keep-ui/shared/lib/__tests__/provider-utils.test.ts
  keep-ui/shared/lib/__tests__/severity-utils.test.ts
  keep-ui/shared/lib/__tests__/status-utils.test.ts
  keep-ui/shared/lib/buildNestedObject.ts
  keep-ui/shared/lib/capture.ts
  keep-ui/shared/lib/downloadFileFromString.ts
  keep-ui/shared/lib/encodings.ts
  keep-ui/shared/lib/getApiUrlFromConfig.ts
  keep-ui/shared/lib/logs-utils.ts
  keep-ui/shared/lib/object-utils.ts
  keep-ui/shared/lib/provider-utils.ts
  keep-ui/shared/lib/state-utils.ts
  keep-ui/shared/lib/status-utils.ts
  keep-ui/shared/lib/tremor-utils.ts
Labels: Documentation, size:XL, lgtm

#4845 fix: message about failure to write to clipboard
  docs/images/faq/faq-browser-settings.png
  docs/images/faq/faq-clipboard-blocked.png
  docs/mint.json
  docs/overview/faq.mdx
  keep-ui/app/(keep)/settings/webhook-settings.tsx
  keep-ui/app/(keep)/workflows/[workflow_id]/workflow-executions-table.tsx
  keep-ui/features/alerts/alert-detail-sidebar/ui/alert-sidebar.tsx
  keep-ui/features/alerts/view-raw-alert/ui/ViewAlertModal.tsx
  keep-ui/features/workflow-execution-results/ui/WorkflowExecutionError.tsx
  keep-ui/shared/constants.ts
  keep-ui/shared/ui/WorkflowYAMLEditor/ui/WorkflowYAMLEditor.tsx
  keep-ui/shared/ui/utils/showErrorToast.tsx
Labels: Bug, UI, size:L, lgtm

#4858 fix: no workflows found for execution from alert or incident
  keep-ui/components/ui/Modal.tsx
  keep-ui/features/workflows/manual-run-workflow/ui/manual-run-workflow-modal.tsx
  keep-ui/widgets/alerts-table/ui/alert-table-server-side.tsx
  pyproject.toml
  tests/e2e_tests/test_end_to_end.py
  tests/e2e_tests/workflow-alert-log.yaml
  tests/e2e_tests/workflow-incident-log.yaml
Labels: Bug, size:L

#4861 docs: installation.mdx to fix helm upgrade values for TLS
  docs/deployment/kubernetes/installation.mdx
Labels: Documentation, size:XS, lgtm

#4721 feat: Add Flux CD provider for service topology and alert integration
  README.md
  docs/mint.json
  docs/providers/documentation/fluxcd-provider.mdx
  docs/providers/overview.md
  docs/providers/overview.mdx
  docs/snippets/providers/console-snippet-autogenerated.mdx
  docs/snippets/providers/fluxcd-snippet-autogenerated.mdx
  docs/snippets/providers/keep-snippet-autogenerated.mdx
  docs/snippets/providers/test_fluxcd-snippet-autogenerated.mdx
  examples/workflows/fluxcd_example.yml
  keep-ui/package-lock.json
  keep-ui/package.json
  keep-ui/public/icons/fluxcd-icon.png
  keep-ui/scripts/validate-workflow-examples.ts
  keep/providers/base/base_provider.py
  keep/providers/fluxcd_provider/README.md
  keep/providers/fluxcd_provider/__init__.py
  keep/providers/fluxcd_provider/example.yaml
  keep/providers/fluxcd_provider/fluxcd_provider.py
  keep/providers/fluxcd_provider/requirements.txt
  keep/providers/fluxcd_provider/setup.py
  keep/providers/fluxcd_provider/test_fluxcd_provider.py
  scripts/docs_get_providers_list.py
  scripts/docs_render_provider_snippets.py
  tests/e2e_tests/incidents_alerts_tests/incidents_alerts_setup.py
  tests/e2e_tests/incidents_alerts_tests/test_filtering_sort_search_on_alerts.py
Labels: Documentation, Feature, Provider, 🙋 Bounty claim, size:XXL, lgtm, hacktoberfest-accepted

#4867 fix: event body in workflow test runs
  keep-ui/entities/workflows/model/workflow-yaml-editor-store.ts
  keep-ui/features/workflows/test-run/model/useWorkflowTestRun.ts
  keep-ui/features/workflows/test-run/ui/workflow-test-run-button.tsx
  keep-ui/widgets/workflow-builder/workflow-builder.tsx
  tests/e2e_tests/test_end_to_end.py
Labels: Bug, size:L, lgtm

#4833 fix: Introduce zustand state to FacetsPanel to improve maintainability
  keep-ui/app/(keep)/alerts/[id]/ui/alert-table-tab-panel-server-side.tsx
  keep-ui/app/(keep)/incidents/page.tsx
  keep-ui/components/ui/DateRangePickerV2.tsx
  keep-ui/components/ui/useTimeframeState.ts
  keep-ui/entities/incidents/model/models.ts
  keep-ui/features/cel-input/use-cel-state.ts
  keep-ui/features/filter/build-cel.test.ts
  keep-ui/features/filter/build-cel.ts
  keep-ui/features/filter/facet-panel-server-side.tsx
  keep-ui/features/filter/facet-value.tsx
  keep-ui/features/filter/facet.tsx
  keep-ui/features/filter/facets-panel.tsx
  keep-ui/features/filter/models.tsx
  keep-ui/features/filter/store/__tests__/use-initial-state-handler.test.ts
  keep-ui/features/filter/store/__tests__/use-queries-handler.test.ts
  keep-ui/features/filter/store/__tests__/utils.test.ts
  keep-ui/features/filter/store/create-facets-store.ts
  keep-ui/features/filter/store/index.ts
  keep-ui/features/filter/store/use-facets-config.tsx
  keep-ui/features/filter/store/use-facets-loading-state-handler.ts
  keep-ui/features/filter/store/use-initial-state-handler.ts
  keep-ui/features/filter/store/use-queries-handler.ts
  keep-ui/features/filter/store/use-query-params/__tests__/split-facet-values.test.ts
  keep-ui/features/filter/store/use-query-params/__tests__/use-query-params.test.ts
  keep-ui/features/filter/store/use-query-params/split-facet-values.ts
  keep-ui/features/filter/store/use-query-params/use-query-params.ts
  keep-ui/features/filter/store/use-store.tsx
  keep-ui/features/filter/store/utils.ts
  keep-ui/features/incidents/incident-list/ui/incident-list.tsx
  keep-ui/features/incidents/incident-list/ui/useIncidentsTableData.tsx
  keep-ui/features/presets/presets-manager/ui/alerts-rules-builder.tsx
  keep-ui/widgets/alerts-table/ui/alert-table-server-side.tsx
  keep-ui/widgets/alerts-table/ui/useAlertsTableData.ts
  pyproject.toml
  tests/e2e_tests/incidents_alerts_tests/incidents_alerts_setup.py
  tests/e2e_tests/incidents_alerts_tests/test_filtering_sort_search_on_alerts.py
  tests/e2e_tests/incidents_alerts_tests/test_filtering_sort_search_on_incidents.py
Labels: Bug, UI, size:XXL

#4873 fix: status not getting updated after acknowledged
  keep-ui/features/alerts/alert-change-status/ui/alert-change-status-modal.tsx
  keep/api/routes/alerts.py
Labels: Bug, size:M, lgtm

#4864 fix: lookup_by_name if updating workflows from a workflow
  keep/api/core/db.py
  keep/providers/keep_provider/keep_provider.py
  keep/workflowmanager/workflowstore.py
  pyproject.toml
  tests/fixtures/workflow_manager.py
  tests/test_workflow_execution.py
  tests/test_workflows_update.py
Labels: Bug, size:XL, lgtm

#4891 fix: statuscake uptime alerts
  keep/providers/statuscake_provider/statuscake_provider.py
  pyproject.toml
Labels: Feature, Provider, size:M, lgtm

#4899 fix(ui): prevent AlertSideBar when selecting text
  keep-ui/widgets/alerts-table/ui/alert-table-server-side.tsx
Labels: Bug, UI, size:S, lgtm

#4896 fix(ui): incidents group by incident name
  keep-ui/widgets/alerts-table/ui/alert-grouped-row.tsx
Labels: Bug, UI, size:S, lgtm

#4898 fix: minor fixes in CEL filters
  keep/workflowmanager/workflowmanager.py
  tests/test_workflow_cel_filter.py
Labels: Bug, size:XL, lgtm

#4904 fix: update user exceptions
  keep/api/routes/auth/users.py
  keep/identitymanager/identity_managers/db/db_identitymanager.py
  keep/identitymanager/identitymanager.py
  tests/test_auth_new.py
Labels: Bug, size:L, lgtm

#4917 fix: statuscake
  keep/providers/statuscake_provider/statuscake_provider.py
  pyproject.toml
Labels: Bug, size:M, lgtm

#4909 fix: flaky tests
  tests/conftest.py
  tests/e2e_tests/test_end_to_end_db_auth.py
  tests/e2e_tests/test_pushing_prometheus_alerts.py
  tests/test_enrichments.py
Labels: Bug, size:M, lgtm

#4915 feat: aws SM rotation policy
  docs/deployment/secret-store.mdx
  keep/secretmanager/awssecretmanager.py
Labels: Feature, size:M, lgtm

#4911 feat: firingStartTimeSinceLastResolved
  keep-ui/features/alerts/view-raw-alert/ui/ViewAlertModal.tsx
  keep-ui/widgets/alerts-table/lib/alert-table-time-format.tsx
  keep/api/models/alert.py
  keep/api/tasks/process_event_task.py
  keep/api/utils/enrichment_helpers.py
Labels: size:M, lgtm

#4924 fix: Implement "has" CEL operator support
  keep/api/core/cel_to_sql/ast_nodes.py
  keep/api/core/cel_to_sql/cel_ast_converter.py
  keep/api/core/cel_to_sql/properties_mapper.py
  keep/api/core/cel_to_sql/properties_metadata.py
  keep/api/core/cel_to_sql/sql_providers/base.py
  keep/api/core/cel_to_sql/sql_providers/mysql.py
  keep/api/core/cel_to_sql/sql_providers/postgresql.py
  keep/api/core/cel_to_sql/sql_providers/sqlite.py
  tests/cel_to_sql/cel-to-sql-test-cases.json
  tests/cel_to_sql/test_cel_to_ast.py
Labels: size:L, lgtm

#4894 fix: Fix boolean handling in CEL-to-SQL and in facets
  keep/api/core/alerts.py
  keep/api/core/cel_to_sql/sql_providers/base.py
  keep/api/core/cel_to_sql/sql_providers/mysql.py
  keep/api/core/cel_to_sql/sql_providers/postgresql.py
  keep/api/core/cel_to_sql/sql_providers/sqlite.py
  keep/api/core/facets.py
  keep/api/core/facets_query_builder/base_facets_query_builder.py
  keep/api/core/facets_query_builder/get_facets_query_builder.py
  keep/api/core/facets_query_builder/mysql.py
  keep/api/core/facets_query_builder/postgresql.py
  keep/api/core/facets_query_builder/sqlite.py
  keep/api/core/facets_query_builder/utils.py
  keep/api/core/incidents.py
  keep/api/core/workflows.py
  tests/cel_to_sql/cel-to-sql-test-cases.json
  tests/cel_to_sql/test_cel_to_sql.py
Labels: Bug, size:XXL, lgtm

#4932 fix: Add logging for errors in CEL to AST conversion
  keep/api/core/cel_to_sql/cel_ast_converter.py
Labels: Bug, size:S

#4935 feat: support enrich array
  keep/providers/base/base_provider.py
  pyproject.toml
  tests/test_workflows.py
Labels: Feature, size:L

#4936 fix: sorting for startedAt field
  keep/api/core/alerts.py
Labels: Bug, size:XS
