Repository keephq/keep, pull requests merged in 2025-07, with the labels that each got.

#5128 fix: correlation rule threshold counts already resolved alerts
  keep/api/core/alerts.py
  keep/api/models/alert.py
  keep/api/tasks/process_event_task.py
  keep/api/utils/enrichment_helpers.py
  keep/rulesengine/rulesengine.py
  tests/test_counting.py
  tests/test_counting_integration.py
  tests/test_rules_engine.py
Labels: Bug, size:XL

#5133 fix: Add alert body sanitizer
  keep/api/tasks/process_event_task.py
  keep/api/utils/alert_utils.py
  tests/test_alert_utils.py
Labels: size:M, lgtm

#5132 fix: Sort dict keys before generating the hash
  keep/api/alert_deduplicator/alert_deduplicator.py
  tests/deduplication/test_deduplications.py
Labels: Bug, size:L, lgtm

#5145 fix: update release-workflow-schema.yml, skip schema repo checkout for forks
  .github/workflows/release-workflow-schema.yml
Labels: size:M, lgtm

#5140 fix: Use integer severities for zabbix provider
  docs/snippets/providers/zabbix-snippet-autogenerated.mdx
  keep/providers/zabbix_provider/zabbix_provider.py
Labels: Provider, size:L, lgtm

#5162 fix(provider): loki auth
  keep/providers/grafana_loki_provider/grafana_loki_provider.py
  pyproject.toml
  tests/test_functions.py
Labels: Bug, size:S

#5164 fix: grafana description
  keep/providers/grafana_provider/grafana_provider.py
  pyproject.toml
Labels: Bug, size:XS

#5170 fix: Make tests more stable
  keep-ui/components/navbar/IncidentLinks.tsx
  keep-ui/components/navbar/NoiseReductionLinks.tsx
  tests/e2e_tests/test_end_to_end.py
Labels: size:M

#5159 feat: Add clickable link to URL in Alert side panel
  keep-ui/features/alerts/alert-detail-sidebar/ui/alert-sidebar.tsx
Labels: Feature, UI, size:M

#5183 fix: Improve date manage in Windows Maintenance
  keep-ui/app/(keep)/maintenance/maintenance-rules-table.tsx
  keep/api/bl/maintenance_windows_bl.py
  tests/test_maintenance_windows_bl.py
Labels: Bug, size:S, lgtm

#5195 feat: add Okta authentication support
  docs/authentication/okta.md
  docs/deployment/authentication/overview.mdx
  docs/deployment/configuration.mdx
  keep-ui/app/(signin)/error/authEnvUtils.tsx
  keep-ui/app/(signin)/signin/SignInForm.tsx
  keep-ui/auth.config.ts
  keep-ui/utils/authenticationType.ts
  keep/identitymanager/identity_managers/okta/__init__.py
  keep/identitymanager/identity_managers/okta/okta_authverifier.py
  keep/identitymanager/identity_managers/okta/okta_identitymanager.py
  keep/identitymanager/identitymanagerfactory.py
Labels: Documentation, Feature, Provider, size:XL

#5209 feat: Bringing back the OG Alerts Count Widget + Adding optional additional link functionality
  keep-ui/app/(keep)/dashboard/GridLayout.tsx
  keep-ui/app/(keep)/dashboard/types.tsx
  keep-ui/app/(keep)/dashboard/widget-types/preset/preset-grid-item.tsx
  keep-ui/app/(keep)/dashboard/widget-types/preset/preset-widget-form.tsx
  keep-ui/app/(keep)/dashboard/widget-types/preset/widget-alert-count-panel.tsx
  pyproject.toml
Labels: Feature, UI, size:L, lgtm

#5211 feat: add sound and priority support to pushover provider
  keep/providers/pushover_provider/pushover_provider.py
Labels: Enhancement, Provider, size:S, lgtm
